// Context wraps the WIT-generated import bindings for ergonomic host interaction.
//
// Import packages are generated by wit-bindgen-go from wit/flow-like-node.wit.
// Run `mise run generate` (or `wit-bindgen-go generate --world flow-like-node --out gen ./wit`)
// before building. If the generated package paths differ from those below, update the imports.
package main

import (
	"strconv"

	"go.bytecodealliance.org/cm"

	"github.com/example/flow-like-wasm-node/gen/flow-like/node/auth"
	"github.com/example/flow-like-wasm-node/gen/flow-like/node/cache"
	"github.com/example/flow-like-wasm-node/gen/flow-like/node/http"
	"github.com/example/flow-like-wasm-node/gen/flow-like/node/logging"
	"github.com/example/flow-like-wasm-node/gen/flow-like/node/metadata"
	"github.com/example/flow-like-wasm-node/gen/flow-like/node/models"
	"github.com/example/flow-like-wasm-node/gen/flow-like/node/pins"
	"github.com/example/flow-like-wasm-node/gen/flow-like/node/storage"
	"github.com/example/flow-like-wasm-node/gen/flow-like/node/streaming"
	"github.com/example/flow-like-wasm-node/gen/flow-like/node/variables"
)

type Context struct {
	result ExecutionResult
}

func NewContext() *Context {
	return &Context{result: SuccessResult()}
}

// ── Inputs (via WIT pins interface) ─────────────────────────────────────

func (c *Context) GetInputRaw(name string) (string, bool) {
	opt := pins.GetInput(name)
	if v := opt.Some(); v != nil {
		return *v, true
	}
	return "", false
}

func (c *Context) GetString(name, defaultValue string) string {
	v, ok := c.GetInputRaw(name)
	if !ok {
		return defaultValue
	}
	if len(v) >= 2 && v[0] == '"' && v[len(v)-1] == '"' {
		return v[1 : len(v)-1]
	}
	return v
}

func (c *Context) GetI64(name string, defaultValue int64) int64 {
	v, ok := c.GetInputRaw(name)
	if !ok {
		return defaultValue
	}
	n, err := strconv.ParseInt(v, 10, 64)
	if err != nil {
		return defaultValue
	}
	return n
}

func (c *Context) GetF64(name string, defaultValue float64) float64 {
	v, ok := c.GetInputRaw(name)
	if !ok {
		return defaultValue
	}
	f, err := strconv.ParseFloat(v, 64)
	if err != nil {
		return defaultValue
	}
	return f
}

func (c *Context) GetBool(name string, defaultValue bool) bool {
	v, ok := c.GetInputRaw(name)
	if !ok {
		return defaultValue
	}
	return v == "true"
}

// ── Outputs ─────────────────────────────────────────────────────────────

func (c *Context) SetOutput(name, value string) {
	pins.SetOutput(name, value)
	c.result.Outputs[name] = value
}

func (c *Context) ActivateExec(name string) {
	pins.ActivateExec(name)
	c.result.ActivateExec = append(c.result.ActivateExec, name)
}

// ── Logging ─────────────────────────────────────────────────────────────

func (c *Context) Debug(msg string) { logging.Log(0, msg) }
func (c *Context) Info(msg string)  { logging.Log(1, msg) }
func (c *Context) Warn(msg string)  { logging.Log(2, msg) }
func (c *Context) Error(msg string) { logging.Log(3, msg) }

// ── Streaming ───────────────────────────────────────────────────────────

func (c *Context) StreamText(text string)                { streaming.Text(text) }
func (c *Context) StreamEvent(eventType, data string)    { streaming.Emit(eventType, data) }

// ── Variables ───────────────────────────────────────────────────────────

func (c *Context) GetVar(name string) (string, bool) {
	opt := variables.GetVar(name)
	if v := opt.Some(); v != nil {
		return *v, true
	}
	return "", false
}

func (c *Context) SetVar(name, value string) { variables.SetVar(name, value) }
func (c *Context) DeleteVar(name string)     { variables.DeleteVar(name) }
func (c *Context) HasVar(name string) bool   { return variables.HasVar(name) }

// ── Cache ───────────────────────────────────────────────────────────────

func (c *Context) CacheGet(key string) (string, bool) {
	opt := cache.CacheGet(key)
	if v := opt.Some(); v != nil {
		return *v, true
	}
	return "", false
}

func (c *Context) CacheSet(key, value string) { cache.CacheSet(key, value) }
func (c *Context) CacheDelete(key string)     { cache.CacheDelete(key) }
func (c *Context) CacheHas(key string) bool   { return cache.CacheHas(key) }

// ── Metadata ────────────────────────────────────────────────────────────

func (c *Context) NodeID() string    { return metadata.GetNodeID() }
func (c *Context) RunID() string     { return metadata.GetRunID() }
func (c *Context) AppID() string     { return metadata.GetAppID() }
func (c *Context) BoardID() string   { return metadata.GetBoardID() }
func (c *Context) UserID() string    { return metadata.GetUserID() }
func (c *Context) IsStreaming() bool { return metadata.IsStreaming() }
func (c *Context) TimeNow() uint64   { return metadata.TimeNow() }
func (c *Context) Random() float64   { return metadata.Random() }
func (c *Context) LogLevel() uint8   { return metadata.GetLogLevel() }

// ── Storage ─────────────────────────────────────────────────────────────

func (c *Context) StorageDir(nodeScoped bool) (string, bool) {
	opt := storage.StorageDir(nodeScoped)
	if v := opt.Some(); v != nil {
		return *v, true
	}
	return "", false
}

func (c *Context) UploadDir() (string, bool) {
	opt := storage.UploadDir()
	if v := opt.Some(); v != nil {
		return *v, true
	}
	return "", false
}

func (c *Context) CacheDir(nodeScoped, userScoped bool) (string, bool) {
	opt := storage.CacheDir(nodeScoped, userScoped)
	if v := opt.Some(); v != nil {
		return *v, true
	}
	return "", false
}

func (c *Context) UserDir(nodeScoped bool) (string, bool) {
	opt := storage.UserDir(nodeScoped)
	if v := opt.Some(); v != nil {
		return *v, true
	}
	return "", false
}

func (c *Context) ReadFile(flowPath string) ([]byte, bool) {
	opt := storage.ReadFile(flowPath)
	if v := opt.Some(); v != nil {
		return v.Slice(), true
	}
	return nil, false
}

func (c *Context) WriteFile(flowPath string, data []byte) bool {
	return storage.WriteFile(flowPath, cm.ToList(data))
}

func (c *Context) ListFiles(flowPath string) (string, bool) {
	opt := storage.ListFiles(flowPath)
	if v := opt.Some(); v != nil {
		return *v, true
	}
	return "", false
}

// ── Models ──────────────────────────────────────────────────────────────

func (c *Context) EmbedText(bitJSON, textsJSON string) (string, bool) {
	opt := models.EmbedText(bitJSON, textsJSON)
	if v := opt.Some(); v != nil {
		return *v, true
	}
	return "", false
}

// ── Auth ────────────────────────────────────────────────────────────────

func (c *Context) GetOAuthToken(provider string) (string, bool) {
	opt := auth.GetOauthToken(provider)
	if v := opt.Some(); v != nil {
		return *v, true
	}
	return "", false
}

func (c *Context) HasOAuthToken(provider string) bool {
	return auth.HasOauthToken(provider)
}

// ── HTTP ────────────────────────────────────────────────────────────────
// For raw TCP/UDP/DNS, Component Model enables net.Dial directly.

func (c *Context) HTTPRequest(method uint8, url, headers string, body []byte) (string, bool) {
	var bodyOpt cm.Option[cm.List[uint8]]
	if body != nil {
		bodyOpt = cm.Some(cm.ToList(body))
	}
	opt := http.Request(method, url, headers, bodyOpt)
	if v := opt.Some(); v != nil {
		return *v, true
	}
	return "", false
}

// ── Result Finalization ─────────────────────────────────────────────────

func (c *Context) Finish() ExecutionResult { return c.result }

func (c *Context) Success() ExecutionResult {
	c.ActivateExec("exec_out")
	return c.Finish()
}

func (c *Context) Fail(err string) ExecutionResult {
	c.result.Error = &err
	return c.Finish()
}
