/* global Buffer, TextDecoder, TextEncoder, URL */
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";
import { webcrypto, createHash, createPrivateKey, sign, X509Certificate } from "node:crypto";

globalThis.crypto ??= webcrypto;
const generated = new URL("../../../apps/web/public/device-crypto/flow_like_device_crypto.js", import.meta.url);
const crypto = await import(generated.href);
await crypto.default({ module_or_path: await readFile(new URL("flow_like_device_crypto_bg.wasm", generated)) });

test("generated browser WASM creates fresh tunnel epochs and closes them with the controller", () => {
  const password = new TextEncoder().encode("browser tunnel integration password");
  const created = crypto.createControllerVault("device-tunnel", password);
  const unlocked = crypto.unlockControllerVault("device-tunnel", password, Uint8Array.from(created.vault));
  const deviceKey = new Uint8Array(32);
  deviceKey[0] = 9;
  try {
    const first = unlocked.beginTunnelNoise("owner", deviceKey, 100);
    const renewed = unlocked.beginTunnelNoise("owner", deviceKey, 340);
    const certificate = (handshake) => JSON.parse(Buffer.from(handshake.certificate().split(".")[1], "base64url"));
    const oldCertificate = certificate(first);
    const newCertificate = certificate(renewed);
    assert.equal(oldCertificate.expires_at, 400);
    assert.equal(newCertificate.expires_at, 640);
    assert.notEqual(first.sessionId(), renewed.sessionId());
    assert.notDeepEqual(oldCertificate.management_key, newCertificate.management_key);
    assert.equal(first.write(100).length, 32);
    assert.equal(renewed.write(340).length, 32);
    assert.throws(() => first.write(400));
    unlocked.close();
    assert.throws(() => renewed.write(341));
    first.free();
    renewed.free();
  } finally {
    unlocked.close();
    unlocked.free();
    password.fill(0);
  }
});

// Public PKCS#10 fixtures generated by OpenSSL. Their private keys were discarded.
const serviceCsr = `-----BEGIN CERTIFICATE REQUEST-----
MIIBPTCB5AIBADAbMRkwFwYDVQQDDBBhcGkuZXhhbXBsZS50ZXN0MFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEs520fTfVIIpyMc8nRf3YXf1OrjzBrsvBsmTEUFCn
m2AFnjS3YGjSR0/GkTPM0seNl/pdjOYgXEFyWMM2PAHF2aBnMGUGCSqGSIb3DQEJ
DjFYMFYwIQYDVR0RBBowGIIQYXBpLmV4YW1wbGUudGVzdIcEfwAAATAMBgNVHRMB
Af8EAjAAMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDATAKBggq
hkjOPQQDAgNIADBFAiBF8PNN9fqUQqHxb7azlIqCZzJI4VgBmaeJYv4BAMXiVwIh
AIl+YfirFAPqmSvvmKWItsTMFIGWIV36AJORwQxzM8EV
-----END CERTIFICATE REQUEST-----`;
const issuerCsr = `-----BEGIN CERTIFICATE REQUEST-----
MIIBUjCB+QIBADAqMSgwJgYDVQQDDB9hcGkuZXhhbXBsZS50ZXN0IHNlcnZpY2Ug
aXNzdWVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEaOeKuK/GyIJCUej0lkV0
uV1jAqqZ/vgxMvrPXrAnhRMcYpIx4aGZtgfrT1mddbP5juapaOT22r4yCKBviF44
NaBtMGsGCSqGSIb3DQEJDjFeMFwwIQYDVR0RBBowGIIQYXBpLmV4YW1wbGUudGVz
dIcEfwAAATASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjATBgNV
HSUEDDAKBggrBgEFBQcDATAKBggqhkjOPQQDAgNIADBFAiEApvD4hZYpiKpYPxlY
EznvhGNqSj4abOnuHvC/K5NvG70CIBZDLZogwoTFMAHDvLnGAZy+QPN1CMOUCahz
MeQvD8n3
-----END CERTIFICATE REQUEST-----`;

test("generated browser WASM keeps CA keys in scoped vaults and signs only approved service CSRs", () => {
  const password = new TextEncoder().encode("organisation CA browser password");
  const replacement = new TextEncoder().encode("replacement organisation password");
  const account = JSON.stringify(["https://auth.example", "owner", "https://hub.example", "profile"]);
  const authorityId = "bce0a1fe-7055-4131-8e08-ec9b3b4b3975";
  const now = 1_790_000_000;
  try {
    const created = crypto.createCertificateAuthorityVault({
      account_binding: account, authority_id: authorityId, label: "Browser organisation",
      dns_suffixes: ["example.test"], ip_addresses: ["127.0.0.1"], validity_days: 3650,
    }, password, now);
    const imported = JSON.parse(JSON.stringify(created));
    assert.equal(JSON.stringify(imported).includes("PRIVATE KEY"), false);
    const vault = Uint8Array.from(imported.vault);
    const rootVault = Uint8Array.from(imported.root_vault);
    assert.deepEqual(crypto.inspectCertificateAuthorityVault(account, authorityId, password, vault), created.public_bundle);
    assert.deepEqual(crypto.inspectCertificateAuthorityBackup(account, authorityId, password, vault, rootVault), created.public_bundle);
    const damagedRoot = rootVault.slice();
    damagedRoot[damagedRoot.length - 1] ^= 1;
    assert.throws(() => crypto.inspectCertificateAuthorityBackup(account, authorityId, password, vault, damagedRoot));
    assert.throws(() => crypto.inspectCertificateAuthorityBackup(account, authorityId, password, vault, vault));
    assert.throws(() => crypto.inspectCertificateAuthorityVault("different account", authorityId, password, vault));
    assert.throws(() => crypto.inspectCertificateAuthorityVault(account, authorityId, replacement, vault));
    assert.throws(() => crypto.inspectCertificateAuthorityVault(account, authorityId, password, rootVault));
    const request = { csr_pem: serviceCsr, dns_names: ["api.example.test"], ip_addresses: ["127.0.0.1"], validity_days: 90 };
    const signed = crypto.signServiceCertificate(account, authorityId, password, vault, request, now);
    const leaf = new X509Certificate(signed.certificate_chain_pem);
    const intermediate = new X509Certificate(created.public_bundle.issuer_certificate_pem);
    const root = new X509Certificate(created.public_bundle.root_certificate_pem);
    assert.equal(root.ca, true);
    assert.equal(leaf.ca, false);
    assert.equal(leaf.checkHost("api.example.test"), "api.example.test");
    assert.equal(leaf.checkIP("127.0.0.1"), "127.0.0.1");
    assert.equal(leaf.verify(intermediate.publicKey), true);
    assert.equal(intermediate.verify(root.publicKey), true);
    assert.equal(root.verify(root.publicKey), true);
    assert.equal(root.fingerprint256.replaceAll(":", "").toLowerCase(), created.public_bundle.sha256_fingerprint);
    assert.equal(signed.not_after, now + 90 * 86400);
    assert.throws(() => crypto.signServiceCertificate(account, authorityId, password, vault, { ...request, dns_names: ["other.example.test"] }, now));
    assert.throws(() => crypto.signServiceCertificate(account, authorityId, password, vault, { ...request, csr_pem: issuerCsr }, now));
    const delegated = crypto.signDeviceCertificateIssuer(account, authorityId, password, vault, { ...request, csr_pem: issuerCsr }, now);
    assert.equal(new X509Certificate(delegated.certificate_chain_pem).ca, true);
    assert.equal(new X509Certificate(delegated.certificate_chain_pem).verify(intermediate.publicKey), true);
    const renewed = crypto.renewCertificateAuthorityVault(account, authorityId, password, vault, rootVault, now + 86400);
    assert.equal(renewed.public_bundle.root_certificate_pem, created.public_bundle.root_certificate_pem);
    assert.notEqual(renewed.public_bundle.issuer_certificate_pem, created.public_bundle.issuer_certificate_pem);
    assert.throws(() => crypto.rewrapCertificateAuthorityVault(account, authorityId, password, replacement, Uint8Array.from(renewed.vault), rootVault));
    const rewrapped = crypto.rewrapCertificateAuthorityVault(account, authorityId, password, replacement, Uint8Array.from(renewed.vault), Uint8Array.from(renewed.root_vault));
    assert.deepEqual(crypto.inspectCertificateAuthorityVault(account, authorityId, replacement, Uint8Array.from(rewrapped.vault)), renewed.public_bundle);
    assert.throws(() => crypto.inspectCertificateAuthorityVault(account, authorityId, password, Uint8Array.from(rewrapped.vault)));
  } finally {
    password.fill(0);
    replacement.fill(0);
  }
});

test("generated browser WASM preserves long-term keys and replaces restored MLS endpoints", () => {
  const password = new TextEncoder().encode("browser integration test password");
  const created = crypto.createControllerVault("device-test", password);
  const invitation = crypto.createInvitationVault("device-test", password);
  assert.throws(() => crypto.unlockControllerVault("other-device", password, Uint8Array.from(created.vault)));
  const unlocked = crypto.unlockControllerVault("device-test", password, Uint8Array.from(created.vault));
  assert.deepEqual(unlocked.publicBundle(), created.public_bundle);
  const endpoint = unlocked.createTelemetry({
    scope: "device", owner_invitation_key: invitation.public_key,
    publisher: { endpoint_id: "device-test", signing_key: crypto.createBootstrapKey().public_key },
  });
  const initial = endpoint.preparedSnapshot();
  assert.throws(() => endpoint.prepareKeyPackage());
  endpoint.confirmCommit(initial.checkpoint);
  endpoint.prepareKeyPackage();
  const pending = endpoint.preparedSnapshot();
  assert.notDeepEqual(pending.checkpoint, initial.checkpoint);
  const publishedPackage = endpoint.confirmCommit(pending.checkpoint);
  assert.equal(publishedPackage.kind, "key_package");
  assert.ok(Buffer.from(publishedPackage.wire, "base64url").length > 32);
  const restored = unlocked.freshEndpointVault(password);
  assert.deepEqual(restored.public_bundle.controller_key, created.public_bundle.controller_key);
  assert.deepEqual(restored.public_bundle.archive_key, created.public_bundle.archive_key);
  assert.notEqual(restored.public_bundle.endpoint_id, created.public_bundle.endpoint_id);
  assert.notDeepEqual(restored.public_bundle.telemetry_member, created.public_bundle.telemetry_member);
  assert.throws(() => endpoint.position());
  const resumed = crypto.unlockControllerVault("device-test", password, Uint8Array.from(restored.vault));
  assert.deepEqual(resumed.publicBundle(), restored.public_bundle);
  resumed.close();
  assert.throws(() => resumed.publicBundle());
  unlocked.close();
  password.fill(0);
});

test("generated browser WASM rewraps both password vaults and reopens the same MLS snapshot", () => {
  const previous = new TextEncoder().encode("previous browser integration password");
  const replacement = new TextEncoder().encode("replacement browser integration password");
  const handles = [];
  try {
    const created = crypto.createControllerVault("device-password", previous);
    const invitation = crypto.createInvitationVault("device-password", previous);
    const controllerCiphertext = Uint8Array.from(created.vault);
    const invitationCiphertext = Uint8Array.from(invitation.vault);
    const original = crypto.unlockControllerVault("device-password", previous, controllerCiphertext);
    handles.push(original);
    const audience = {
      scope: "device",
      owner_invitation_key: invitation.public_key,
      publisher: { endpoint_id: "device-password", signing_key: crypto.createBootstrapKey().public_key },
    };
    const endpoint = original.createTelemetry(audience);
    handles.push(endpoint);
    endpoint.confirmCommit(endpoint.preparedSnapshot().checkpoint);
    endpoint.prepareKeyPackage();
    const persisted = endpoint.preparedSnapshot();
    endpoint.confirmCommit(persisted.checkpoint);
    const position = endpoint.position();
    endpoint.close();
    original.close();
    const policy = {
      version: 1, device_id: "device-password", policy_version: 1,
      previous_policy_digest: null, grants: [], issued_at: 100, expires_at: 200,
    };
    const signedBefore = crypto.signManagementPolicy(policy, previous, invitationCiphertext);
    assert.throws(() => crypto.rewrapControllerVaults(
      "device-password", replacement, previous, controllerCiphertext, invitationCiphertext,
    ));
    assert.throws(() => crypto.rewrapControllerVaults(
      "device-password", previous, replacement, controllerCiphertext, controllerCiphertext,
    ));
    const changed = crypto.rewrapControllerVaults(
      "device-password", previous, replacement, controllerCiphertext, invitationCiphertext,
    );
    assert.deepEqual(changed.controller.public_bundle, created.public_bundle);
    assert.deepEqual(changed.invitation.public_key, invitation.public_key);
    assert.notDeepEqual(changed.controller.vault, created.vault);
    assert.notDeepEqual(changed.invitation.vault, invitation.vault);
    const nextController = Uint8Array.from(changed.controller.vault);
    const nextInvitation = Uint8Array.from(changed.invitation.vault);
    assert.throws(() => crypto.unlockControllerVault("device-password", previous, nextController));
    assert.throws(() => crypto.signManagementPolicy(policy, previous, nextInvitation));
    assert.throws(() => crypto.unlockControllerVault("device-password", replacement, nextInvitation));
    const resumed = crypto.unlockControllerVault("device-password", replacement, nextController);
    handles.push(resumed);
    assert.deepEqual(resumed.publicBundle(), created.public_bundle);
    const reopened = resumed.openTelemetry(audience, persisted.snapshot, persisted.checkpoint);
    handles.push(reopened);
    assert.deepEqual(reopened.checkpoint(), persisted.checkpoint);
    assert.deepEqual(reopened.position(), position);
    const signedAfter = crypto.signManagementPolicy(policy, replacement, nextInvitation);
    assert.equal(signedAfter, signedBefore);
    assert.equal(crypto.verifyManagementPolicy(signedAfter, invitation.public_key).device_id, "device-password");
    // Rewrapping local storage does not revoke previously exported encrypted backups.
    const backup = crypto.unlockControllerVault("device-password", previous, controllerCiphertext);
    handles.push(backup);
    assert.deepEqual(backup.publicBundle(), created.public_bundle);
    assert.equal(crypto.signManagementPolicy(policy, previous, invitationCiphertext), signedBefore);
  } finally {
    for (const handle of handles.reverse()) { handle.close(); handle.free(); }
    previous.fill(0);
    replacement.fill(0);
  }
});

test("generated browser WASM changes a shared user's password without invitation authority", () => {
  const previous = new TextEncoder().encode("previous shared browser password");
  const replacement = new TextEncoder().encode("replacement shared browser password");
  let unlocked;
  try {
    const created = crypto.createControllerVault("shared-device", previous);
    const changed = crypto.rewrapControllerVaults(
      "shared-device", previous, replacement, Uint8Array.from(created.vault), new Uint8Array(),
    );
    assert.ok(changed.invitation === undefined || changed.invitation === null);
    assert.deepEqual(changed.controller.public_bundle, created.public_bundle);
    assert.notDeepEqual(changed.controller.vault, created.vault);
    assert.throws(() => crypto.unlockControllerVault("shared-device", previous, Uint8Array.from(changed.controller.vault)));
    unlocked = crypto.unlockControllerVault("shared-device", replacement, Uint8Array.from(changed.controller.vault));
    assert.deepEqual(unlocked.publicBundle(), created.public_bundle);
  } finally {
    unlocked?.close();
    unlocked?.free();
    previous.fill(0);
    replacement.fill(0);
  }
});

test("generated browser WASM retains private inventory across password recovery and fresh endpoints", () => {
  const password = new TextEncoder().encode("inventory account recovery password");
  const wrong = new TextEncoder().encode("incorrect account recovery password");
  const handles = [];
  try {
    const initial = crypto.createOnboardingVaults(password);
    const controller = crypto.unlockControllerVault(initial.controller.public_bundle.device_id, password, Uint8Array.from(initial.controller.vault));
    handles.push(controller);
    const manifest = {
      version: 1, enrollment_id: "inventory-enrollment", device_id: "inventory-device", owner_id: "owner",
      name: "Inventory recovery test", api_base_url: "https://hub.example/api/v1",
      bootstrap_key: crypto.createBootstrapKey().public_key,
      controller_key: initial.controller.public_bundle.controller_key,
      owner_invitation_key: initial.invitation.public_key, issued_at: 100, expires_at: 200,
    };
    const completed = controller.completeOnboarding(manifest, password, Uint8Array.from(initial.invitation.vault));
    const context = { issuer: "https://auth.example", account: "owner", api_origin: "https://hub.example", device_id: manifest.device_id, controller_key: manifest.controller_key, revision: 1 };
    const binding = { issuer: context.issuer, account_id: context.account, api_origin: context.api_origin, device_id: context.device_id, controller_key: context.controller_key, scope: { kind: "project", project_id: "project" }, revision: 2 };
    const plaintext = new TextEncoder().encode(JSON.stringify({ device_id: manifest.device_id, placements: [{ id: "placement", project_id: "project", observed_state: "running" }], observed_at: 1000 }));
    const encrypted = controller.sealInventory(binding, plaintext);
    assert.equal(new TextDecoder().decode(controller.openInventory(binding, encrypted)), new TextDecoder().decode(plaintext));
    for (const changed of [{ account_id: "other" }, { api_origin: "https://other.example" }, { issuer: "https://other-auth.example" }, { device_id: "other-device" }, { revision: 1 }, { scope: {kind: "device"} }]) {
      assert.throws(() => controller.openInventory({ ...binding, ...changed }, encrypted));
      assert.throws(() => controller.openInventory({ ...binding, ...changed }, { ...encrypted, binding: { ...binding, ...changed } }));
    }
    const backup = {
      version: 1, apiOrigin: context.api_origin, deviceId: context.device_id,
      controllerPublic: completed.controller.public_bundle, controllerVault: Array.from(completed.controller.vault),
      invitationVault: Array.from(completed.invitation_vault), manifestJws: completed.manifest_jws,
      grantId: "owner", ownerControllerKey: null,
    };
    const encoded = new TextEncoder().encode(JSON.stringify(backup));
    const sealed = crypto.sealAccountRecovery(context, password, encoded);
    assert.equal(sealed.proof_jws.split(".").length, 3);
    const ciphertext = Uint8Array.from(sealed.ciphertext);
    assert.throws(() => crypto.openAccountRecovery(context, wrong, ciphertext));
    for (const changed of [{account:"other"}, {issuer:"https://elsewhere.example"}, {api_origin:"https://other.example"}, {device_id:"other-device"}, {revision:2}]) {
      assert.throws(() => crypto.openAccountRecovery({ ...context, ...changed }, password, ciphertext));
    }
    controller.close();
    const recovered = crypto.openAccountRecovery(context, password, ciphertext);
    const unlocked = crypto.unlockControllerVault(context.device_id, password, Uint8Array.from(recovered.controllerVault));
    handles.push(unlocked);
    const fresh = unlocked.freshEndpointVault(password);
    const reopened = crypto.unlockControllerVault(context.device_id, password, Uint8Array.from(fresh.vault));
    handles.push(reopened);
    assert.equal(new TextDecoder().decode(reopened.openInventory(binding, encrypted)), new TextDecoder().decode(plaintext));
    assert.notEqual(fresh.public_bundle.endpoint_id, completed.controller.public_bundle.endpoint_id);
    plaintext.fill(0); encoded.fill(0);
  } finally {
    for (const handle of handles.reverse()) { handle.close(); handle.free(); }
    password.fill(0); wrong.fill(0);
  }
});

test("generated browser WASM validates unattended fleet readers against the pinned device bootstrap", () => {
  const password = new TextEncoder().encode("fleet browser onboarding password");
  const handles = [];
  const digest = (bytes) => createHash("sha256").update(bytes).digest("base64url");
  const compact = (payload, type, key) => {
    const jwk = key.public_key;
    const kid = digest(JSON.stringify({crv:jwk.crv,kty:jwk.kty,x:jwk.x}));
    const input = `${Buffer.from(JSON.stringify({alg:"EdDSA",typ:type,kid})).toString("base64url")}.${Buffer.from(JSON.stringify(payload)).toString("base64url")}`;
    const privateKey = createPrivateKey({format:"der",type:"pkcs8",key:Buffer.concat([Buffer.from("302e020100300506032b657004220420","hex"),Buffer.from(key.secret_base64,"base64url")])});
    return `${input}.${sign(null,Buffer.from(input),privateKey).toString("base64url")}`;
  };
  try {
    const vaults = crypto.createOnboardingVaults(password);
    const controller = crypto.unlockControllerVault(vaults.controller.public_bundle.device_id,password,Uint8Array.from(vaults.controller.vault));
    handles.push(controller);
    const bootstrap = crypto.createBootstrapKey();
    const manifest = {version:1,enrollment_id:"fleet-enrollment",device_id:"fleet-device",owner_id:"owner",name:"Fleet test",api_base_url:"https://hub.example/api/v1",bootstrap_key:bootstrap.public_key,controller_key:vaults.controller.public_bundle.controller_key,owner_invitation_key:vaults.invitation.public_key,issued_at:100,expires_at:200};
    const completed = controller.completeOnboarding(manifest,password,Uint8Array.from(vaults.invitation.vault));
    const identity = {auth_key:crypto.createBootstrapKey().public_key,telemetry_key:crypto.createBootstrapKey().public_key,management_key:Array(32).fill(13)};
    const binding = {version:1,enrollment_id:manifest.enrollment_id,device_id:manifest.device_id,identity,manifest_digest:digest(completed.manifest_jws),challenge_id:"challenge",challenge_nonce:"abcdefghijklmnopqrstuvwx12345678",issued_at:100,expires_at:150};
    const receipt = {enrollment_id:manifest.enrollment_id,device_id:manifest.device_id,owner_id:manifest.owner_id,name:manifest.name,identity,manifest_jws:completed.manifest_jws,binding_jws:compact(binding,"flow-like-device-enrollment-binding+jwt",bootstrap),registered_at:110,auth_epoch:1};
    const trusted = {api_base_url:manifest.api_base_url,user_id:"owner",onboarding_manifest_jws:completed.manifest_jws,owner_controller_key:manifest.controller_key};
    const reader = controller.createFleetReader(manifest.api_base_url,"owner",1n,100n,300n);
    const view = {reader_jws:reader,policy_jws:null,snapshots:[]};
    assert.equal(controller.verifyFleetReader(trusted,receipt,reader).revision,1);
    assert.deepEqual(controller.verifyFleetView(trusted,receipt,view,120n).audiences.map((a)=>a.kind),["status","metrics"]);
    assert.throws(()=>controller.verifyFleetView(trusted,receipt,view,300n));
    assert.throws(()=>controller.verifyFleetReader({...trusted,user_id:"other"},receipt,reader));
    assert.throws(()=>controller.verifyFleetReader({...trusted,api_base_url:"https://other.example/api/v1"},receipt,reader));
    assert.throws(()=>controller.verifyFleetReader(trusted,{...receipt,identity:{...identity,telemetry_key:crypto.createBootstrapKey().public_key}},reader));
    assert.throws(()=>controller.verifyFleetReader({...trusted,owner_controller_key:crypto.createBootstrapKey().public_key},receipt,reader));
    const restored = controller.freshEndpointVault(password);
    const fresh = crypto.unlockControllerVault(manifest.device_id,password,Uint8Array.from(restored.vault));
    handles.push(fresh);
    assert.equal(fresh.verifyFleetView(trusted,receipt,view,120n).reader_revision,1);
    assert.equal(fresh.createFleetReader(manifest.api_base_url,"owner",1n,100n,300n),reader);
    const sharedVault = crypto.createControllerVault(manifest.device_id,password);
    const shared = crypto.unlockControllerVault(manifest.device_id,password,Uint8Array.from(sharedVault.vault));
    handles.push(shared);
    const sharedReader = shared.createFleetReader(manifest.api_base_url,"reader",1n,100n,300n);
    const sharedTrusted = {...trusted,user_id:"reader"};
    const sharedPolicy = {version:1,device_id:manifest.device_id,policy_version:1,previous_policy_digest:null,issued_at:100,expires_at:200,grants:[{grant_id:"status-only",user_id:"reader",controller_key:sharedVault.public_bundle.controller_key,scope:{kind:"project",project_id:"project"},capabilities:["status"],expires_at:190,group_id:null,group_version:null}]};
    const sharedView = {reader_jws:sharedReader,policy_jws:crypto.signManagementPolicy(sharedPolicy,password,Uint8Array.from(completed.invitation_vault)),snapshots:[]};
    assert.deepEqual(shared.verifyFleetView(sharedTrusted,receipt,sharedView,120n).audiences.map((a)=>a.kind),["status"]);
    assert.throws(()=>shared.verifyFleetView(sharedTrusted,receipt,{...sharedView,policy_jws:null},120n));
    assert.throws(()=>fresh.verifyFleetReader(sharedTrusted,receipt,sharedReader));
  } finally {
    for(const handle of handles.reverse()){handle.close();handle.free();}
    password.fill(0);
  }
});

test("generated browser WASM signs for the owner with a held invitation key until it is detached or closed", () => {
  const password = new TextEncoder().encode("held signer browser password");
  const wrong = new TextEncoder().encode("another browser password");
  const device = "device-held";
  const handles = [];
  try {
    const created = crypto.createControllerVault(device, password);
    const invitation = crypto.createInvitationVault(device, password);
    const foreign = crypto.createInvitationVault("other-device", password);
    const controllerVault = Uint8Array.from(created.vault);
    const invitationVault = Uint8Array.from(invitation.vault);
    const controller = crypto.unlockControllerVault(device, password, controllerVault);
    handles.push(controller);
    const policy = {version:1,device_id:device,policy_version:1,previous_policy_digest:null,grants:[{grant_id:"reader",user_id:"colleague",controller_key:created.public_bundle.controller_key,scope:{kind:"device"},capabilities:["status"],expires_at:200,group_id:null,group_version:null}],issued_at:100,expires_at:200};
    const telemetry = {version:1,device_id:device,scope:"device",policy_version:1,previous_policy_digest:null,management_policy_digest:null,publisher:created.public_bundle.telemetry_member,members:[created.public_bundle.telemetry_member],issued_at:100,expires_at:200};
    const archive = {version:1,device_id:device,scope:"device",project_id:null,kind:"logs",policy_version:1,previous_policy_digest:null,management_policy_digest:null,recipients:[{recipient_id:"owner",user_id:"owner",public_key:created.public_bundle.archive_key}],issued_at:100,expires_at:200};
    const held = () => [controller.signManagementPolicyHeld(policy), controller.signTelemetryRosterHeld(telemetry), controller.signArchiveRosterHeld(archive)];
    const notHeld = (pattern) => {
      assert.throws(() => controller.signManagementPolicyHeld(policy), pattern);
      assert.throws(() => controller.signTelemetryRosterHeld(telemetry), pattern);
      assert.throws(() => controller.signArchiveRosterHeld(archive), pattern);
    };

    notHeld(/not held/);
    assert.throws(() => controller.attachInvitation(wrong, invitationVault));
    assert.throws(() => controller.attachInvitation(password, controllerVault));
    assert.throws(() => controller.attachInvitation(password, Uint8Array.from(foreign.vault)));
    notHeld(/not held/);

    controller.attachInvitation(password, invitationVault);
    assert.equal(new TextDecoder().decode(password), "held signer browser password");
    const signed = held();
    assert.deepEqual(signed, [
      crypto.signManagementPolicy(policy, password, invitationVault),
      crypto.signTelemetryRoster(telemetry, password, invitationVault),
      crypto.signArchiveRoster(archive, password, invitationVault),
    ]);
    assert.deepEqual(crypto.verifyManagementPolicy(signed[0], invitation.public_key), policy);
    assert.deepEqual(crypto.verifyTelemetryRoster(signed[1], invitation.public_key, 100), telemetry);
    assert.deepEqual(crypto.verifyArchiveRosterHead(signed[2], invitation.public_key), archive);
    assert.throws(() => crypto.verifyManagementPolicy(signed[0], created.public_bundle.controller_key));

    assert.throws(() => controller.signManagementPolicyHeld({...policy, device_id: "other-device"}), /other-device/);
    assert.throws(() => controller.signTelemetryRosterHeld({...telemetry, device_id: "other-device"}));
    assert.throws(() => controller.signArchiveRosterHeld({...archive, device_id: "other-device"}));

    assert.throws(() => controller.attachInvitation(wrong, invitationVault));
    assert.deepEqual(held(), signed);
    controller.freshEndpointVault(password);
    assert.deepEqual(held(), signed);

    controller.detachInvitation();
    controller.detachInvitation();
    notHeld(/not held/);
    controller.attachInvitation(password, invitationVault);
    assert.deepEqual(held(), signed);

    controller.close();
    notHeld(/locked/);
    assert.throws(() => controller.attachInvitation(password, invitationVault), /locked/);
    controller.detachInvitation();

    const onboarding = crypto.createOnboardingVaults(password);
    const provisional = crypto.unlockControllerVault(onboarding.controller.public_bundle.device_id, password, Uint8Array.from(onboarding.controller.vault));
    handles.push(provisional);
    assert.throws(() => provisional.attachInvitation(password, Uint8Array.from(onboarding.invitation.vault)), /onboarding/);

    assert.equal(crypto.signManagementPolicy(policy, password, invitationVault), signed[0]);
    assert.throws(() => crypto.signManagementPolicy(policy, wrong, invitationVault));
  } finally {
    for (const handle of handles.reverse()) { handle.close(); handle.free(); }
    password.fill(0);
    wrong.fill(0);
  }
});
