import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createInterface } from "node:readline";
import { webcrypto, randomUUID } from "node:crypto";

globalThis.crypto ??= webcrypto;
const lines = createInterface({ input: process.stdin })[Symbol.asyncIterator]();
const receive = async () => JSON.parse((await lines.next()).value);
const send = (value) => process.stdout.write(`${JSON.stringify(value)}\n`);
const generated = new URL("../../../apps/web/public/device-crypto/flow_like_device_crypto.js", import.meta.url);
const crypto = await import(generated.href);
await crypto.default({ module_or_path: await readFile(new URL("flow_like_device_crypto_bg.wasm", generated)) });
const password = new TextEncoder().encode("native-browser integration password");
const vault = crypto.createControllerVault("device", password);
const controller = crypto.unlockControllerVault("device", password, Uint8Array.from(vault.vault));
password.fill(0);
send(controller.publicBundle());
const device = await receive();
const now = Math.floor(Date.now() / 1000);
const handshake = controller.beginNoise("owner", Uint8Array.from(device.management_key), now);
send({ certificate: handshake.certificate(), session_id: handshake.sessionId(), data: Buffer.from(handshake.write(now)).toString("base64url") });
handshake.read(Buffer.from((await receive()).data, "base64url"), now);
send({ data: Buffer.from(handshake.write(now)).toString("base64url") });
const session = handshake.finish(now);
const ready = JSON.parse(new TextDecoder().decode(session.decrypt(Buffer.from((await receive()).data, "base64url"), now)));
assert.equal(ready.device_id, "device");
assert.equal(ready.ready, true);
const operation_id = randomUUID();
const request = { operation_id, device_id: "device", issued_at: now, expires_at: now + 60, command: { type: "inspect" } };
const ciphertext = session.encrypt(new TextEncoder().encode(JSON.stringify(request)), now);
send({ data: Buffer.from(ciphertext).toString("base64url") });
const response = JSON.parse(new TextDecoder().decode(session.decrypt(Buffer.from((await receive()).data, "base64url"), now)));
assert.equal(response.operation_id, operation_id);
assert.equal(response.state, "completed");
assert.equal(response.result.device_id, "device");
send({ data: Buffer.from(ciphertext).toString("base64url") });
assert.equal((await receive()).closed, true);
controller.close();
assert.throws(() => session.encrypt(new Uint8Array([1]), now));
