[package]
name = "flow-like-wasm-sdk-macros"
version = "0.3.6"
edition = "2021"
description = "Proc macros for the Flow-Like WASM SDK"
license = "MIT"
repository = "https://github.com/Rheosoph/flow-like"

[workspace]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
