packages:
  - "packages/*"
  - "packages/dexie-tauri-adapter/*"
  - "apps/*"
  - "libs/*/*"

minimumReleaseAge: 4320
savePrefix: ""
minimumReleaseAgeExclude:
  - "@flow-like/*"
  - "@flow-like/flow-like-ui"
  - "flow-like"
  - "flow-like-*"
blockExoticSubdeps: true
strictDepBuilds: true
allowBuilds:
  core-js: false
  esbuild: true
  fsevents: true
  sharp: true
