# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def embed_text(bit_json: str, texts_json: str) -> Optional[str]:
    raise NotImplementedError
def embed_text_query(model_json: str, texts_json: str) -> Optional[str]:
    raise NotImplementedError
def embed_text_document(model_json: str, texts_json: str) -> Optional[str]:
    raise NotImplementedError
def embed_image(model_json: str, image_data: bytes) -> Optional[str]:
    raise NotImplementedError
def llm_prompt(bit_json: str, messages_json: str, do_stream: bool) -> Optional[str]:
    raise NotImplementedError
