# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def storage_dir(node_scoped: bool) -> Optional[str]:
    raise NotImplementedError
def upload_dir() -> Optional[str]:
    raise NotImplementedError
def cache_dir(node_scoped: bool, user_scoped: bool) -> Optional[str]:
    raise NotImplementedError
def user_dir(node_scoped: bool) -> Optional[str]:
    raise NotImplementedError
def read_file(flow_path: str) -> Optional[bytes]:
    raise NotImplementedError
def write_file(flow_path: str, data: bytes) -> bool:
    raise NotImplementedError
def list_files(flow_path: str) -> Optional[str]:
    raise NotImplementedError
