# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def connect(url: str, headers_json: str) -> Optional[str]:
    raise NotImplementedError
def send(session_id: str, message: bytes, is_binary: bool) -> bool:
    raise NotImplementedError
def receive(session_id: str, timeout_ms: int) -> Optional[str]:
    raise NotImplementedError
def close(session_id: str) -> bool:
    raise NotImplementedError
