cmake_minimum_required(VERSION 3.15)
project(flow_ethercat_peer LANGUAGES C CXX)
set(BUILD_MASTER_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_SLAVE_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(BUILD_SIMULATION ON CACHE BOOL "" FORCE)
set(ENABLE_ESI_PARSER ON CACHE BOOL "" FORCE)
set(KICKCAT_INSTALL OFF CACHE BOOL "" FORCE)
add_subdirectory(/opt/kickcat kickcat)
add_executable(ethercat-peer peer.cc)
target_compile_features(ethercat-peer PRIVATE cxx_std_17)
target_link_libraries(ethercat-peer PRIVATE kickcat_simulation)
