[package]
name = "board-decoder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = {version="4.5.44", features = ["derive"]}
flow-like.workspace = true
flow-like-types-proto.workspace = true
flow-like-storage.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
