/**
 * Runtime prop manifest for every A2UI component type.
 *
 * `types.ts` is the source of truth; this file mirrors it into a value that
 * validators (validateComponents.ts and the Rust emit_ui validator in
 * apps/desktop/src-tauri/src/functions/ai/copilot_sdk_tools.rs) can consume.
 *
 * Drift protection is enforced at compile time:
 * - the `satisfies` clause fails when a component type is missing an entry or
 *   an entry lists a prop that does not exist on the interface, and
 * - the `ExpectNever` assertions fail when an interface gains a prop (or
 *   ComponentBase gains a base prop) that is not listed here.
 */

import type { A2UIComponent, ComponentBase } from "./types";

export type A2UIComponentType = A2UIComponent["type"];

type ComponentOf<K extends A2UIComponentType> = Extract<
	A2UIComponent,
	{ type: K }
>;

/** Own props of a component type, excluding shared base props and `type`. */
type PropsOf<K extends A2UIComponentType> = Exclude<
	keyof ComponentOf<K>,
	keyof ComponentBase | "type"
>;

type ExpectNever<T extends never> = T;

/** Shared props every component supports (besides the `type` discriminant). */
export const COMPONENT_BASE_PROPS = [
	"id",
	"style",
	"children",
	"actions",
	"eventHandlers",
	"hidden",
] as const satisfies readonly (keyof ComponentBase)[];

export type _EnsureBasePropsComplete = ExpectNever<
	Exclude<keyof ComponentBase, (typeof COMPONENT_BASE_PROPS)[number]>
>;

export const COMPONENT_PROPS = {
	// Layout
	row: ["gap", "align", "justify", "wrap", "reverse"],
	column: ["gap", "align", "justify", "reverse", "wrap"],
	stack: ["align", "width", "height"],
	grid: ["columns", "rows", "gap", "columnGap", "rowGap", "autoFlow"],
	scrollArea: ["direction"],
	aspectRatio: ["ratio"],
	overlay: ["baseComponentId", "overlays"],
	absolute: ["width", "height"],
	box: ["as"],
	center: ["inline"],
	spacer: ["size", "flex"],

	// Display
	text: [
		"content",
		"variant",
		"size",
		"weight",
		"color",
		"align",
		"truncate",
		"maxLines",
	],
	image: ["src", "alt", "fit", "fallback", "loading", "aspectRatio"],
	icon: ["name", "size", "color", "strokeWidth"],
	video: [
		"src",
		"poster",
		"autoplay",
		"loop",
		"muted",
		"controls",
		"width",
		"height",
	],
	lottie: ["src", "autoplay", "loop", "speed", "width", "height"],
	markdown: ["content", "allowHtml"],
	divider: ["orientation", "thickness", "color"],
	badge: ["content", "variant", "color"],
	avatar: ["src", "fallback", "size"],
	userProfile: [
		"value",
		"variant",
		"avatarSize",
		"showHover",
		"showEmail",
		"showDescription",
		"showUserId",
		"showProfileLink",
		"fallbackLabel",
		"muted",
	],
	progress: ["value", "max", "showLabel", "variant", "color"],
	spinner: ["size", "color"],
	skeleton: ["width", "height", "rounded"],

	// Tables
	table: [
		"columns",
		"data",
		"caption",
		"striped",
		"bordered",
		"hoverable",
		"compact",
		"stickyHeader",
		"sortable",
		"searchable",
		"paginated",
		"pageSize",
		"selectable",
		"onRowClick",
	],
	tableRow: ["cells", "selected", "disabled"],
	tableCell: ["content", "isHeader", "colSpan", "rowSpan", "align"],

	// Interactive
	button: [
		"label",
		"variant",
		"size",
		"disabled",
		"loading",
		"icon",
		"iconPosition",
		"tooltip",
	],
	feedback: [
		"mode",
		"size",
		"title",
		"description",
		"positiveLabel",
		"negativeLabel",
		"positiveRating",
		"negativeRating",
		"showComment",
		"commentMode",
		"commentLabel",
		"commentPlaceholder",
		"commentTitle",
		"commentDescription",
		"commentSubmitLabel",
		"commentCancelLabel",
		"feedbackId",
		"includeState",
		"pageContextMode",
		"pageContextQueryParamAllowlist",
		"pageContextQueryParamDenylist",
		"includePageHash",
		"successMessage",
		"disabled",
	],
	appLink: [
		"target",
		"label",
		"variant",
		"size",
		"icon",
		"iconPosition",
		"appId",
		"eventId",
		"disabled",
	],
	textField: [
		"value",
		"placeholder",
		"label",
		"helperText",
		"error",
		"disabled",
		"inputType",
		"multiline",
		"rows",
		"maxLength",
		"required",
	],
	select: [
		"value",
		"options",
		"placeholder",
		"label",
		"disabled",
		"multiple",
		"searchable",
	],
	slider: ["value", "min", "max", "step", "disabled", "showValue", "label"],
	checkbox: ["checked", "label", "disabled", "indeterminate"],
	switch: ["checked", "label", "disabled"],
	radioGroup: ["value", "options", "disabled", "orientation", "label"],
	dateTimeInput: ["value", "mode", "min", "max", "disabled", "label"],
	fileInput: [
		"value",
		"label",
		"helperText",
		"accept",
		"multiple",
		"maxSize",
		"maxFiles",
		"disabled",
		"error",
	],
	imageInput: [
		"value",
		"label",
		"helperText",
		"accept",
		"multiple",
		"maxSize",
		"maxFiles",
		"disabled",
		"error",
		"aspectRatio",
		"showPreview",
	],
	voiceInput: [
		"value",
		"label",
		"helperText",
		"maxDuration",
		"autoStop",
		"silenceThreshold",
		"silenceDuration",
		"disabled",
		"error",
		"visualizer",
		"variant",
		"size",
		"mode",
		"invoke",
		"color",
		"recordingColor",
		"resultMode",
		"src",
		"url",
	],
	link: [
		"href",
		"label",
		"route",
		"queryParams",
		"external",
		"target",
		"variant",
		"underline",
		"disabled",
	],

	// Container
	card: [
		"title",
		"description",
		"footer",
		"hoverable",
		"clickable",
		"variant",
		"padding",
		"headerImage",
		"headerIcon",
	],
	modal: [
		"open",
		"title",
		"description",
		"closeOnOverlay",
		"closeOnEscape",
		"showCloseButton",
		"size",
		"centered",
	],
	tabs: [
		"value",
		"tabs",
		"orientation",
		"variant",
		"listStyle",
		"triggerStyle",
		"contentStyle",
	],
	accordion: ["items", "multiple", "defaultExpanded", "collapsible"],
	drawer: ["open", "side", "title", "size", "overlay", "closable"],
	tooltip: ["content", "side", "delayMs", "maxWidth"],
	popover: [
		"open",
		"contentComponentId",
		"side",
		"trigger",
		"closeOnClickOutside",
	],

	// Game
	canvas2d: ["width", "height", "backgroundColor", "pixelPerfect"],
	sprite: [
		"src",
		"x",
		"y",
		"width",
		"height",
		"rotation",
		"scale",
		"opacity",
		"flipX",
		"flipY",
		"zIndex",
	],
	shape: [
		"shapeType",
		"x",
		"y",
		"width",
		"height",
		"radius",
		"points",
		"fill",
		"stroke",
		"strokeWidth",
	],
	scene3d: [
		"width",
		"height",
		"cameraType",
		"cameraPosition",
		"backgroundColor",
		"controlMode",
		"fixedView",
		"autoRotateSpeed",
		"enableControls",
		"enableZoom",
		"enablePan",
		"fov",
		"near",
		"far",
		"target",
		"ambientLight",
		"directionalLight",
		"showGrid",
		"showAxes",
	],
	model3d: [
		"src",
		"position",
		"rotation",
		"scale",
		"castShadow",
		"receiveShadow",
		"animation",
		"autoRotate",
		"rotateSpeed",
		"viewerHeight",
		"backgroundColor",
		"cameraDistance",
		"fov",
		"cameraAngle",
		"cameraPosition",
		"cameraTarget",
		"enableControls",
		"enableZoom",
		"enablePan",
		"autoRotateCamera",
		"cameraRotateSpeed",
		"ambientLight",
		"directionalLight",
		"fillLight",
		"rimLight",
		"lightColor",
		"lightingPreset",
		"showGround",
		"groundColor",
		"enableReflections",
		"environment",
		"environmentSource",
		"useHdrBackground",
		"polyhavenHdri",
		"polyhavenResolution",
		"hdriUrl",
		"groundSize",
		"groundOffsetY",
		"groundFollowCamera",
	],
	dialogue: [
		"text",
		"speakerName",
		"speakerPortraitId",
		"typewriter",
		"typewriterSpeed",
	],
	characterPortrait: ["image", "expression", "position", "size", "dimmed"],
	choiceMenu: ["choices", "title", "layout"],
	inventoryGrid: ["items", "columns", "rows", "cellSize"],
	healthBar: [
		"value",
		"maxValue",
		"label",
		"showValue",
		"fillColor",
		"backgroundColor",
		"variant",
	],
	miniMap: [
		"mapImage",
		"width",
		"height",
		"markers",
		"playerX",
		"playerY",
		"playerRotation",
	],

	// Media
	iframe: [
		"src",
		"srcdoc",
		"width",
		"height",
		"sandbox",
		"allow",
		"title",
		"loading",
		"referrerPolicy",
		"border",
	],
	filePreview: [
		"src",
		"url",
		"filename",
		"mimeType",
		"fileType",
		"showControls",
		"fit",
		"fallbackText",
		"height",
		"showDownload",
		"loading",
		"variant",
		"autoPlay",
	],
	diffView: [
		"original",
		"modified",
		"mode",
		"kind",
		"language",
		"markdownMode",
		"showLineNumbers",
		"wordWrap",
		"wordLevel",
		"collapseUnchanged",
		"contextLines",
		"showStats",
		"originalLabel",
		"modifiedLabel",
		"ignoreWhitespace",
		"ignoreCase",
		"trimTrailingWhitespace",
		"swapSides",
	],

	// Charts
	plotlyChart: [
		"chartType",
		"title",
		"series",
		"xAxis",
		"yAxis",
		"data",
		"layout",
		"config",
		"width",
		"height",
		"responsive",
		"showLegend",
		"legendPosition",
	],
	nivoChart: [
		"chartType",
		"title",
		"data",
		"height",
		"colors",
		"animate",
		"showLegend",
		"legendPosition",
		"indexBy",
		"keys",
		"margin",
		"axisBottom",
		"axisLeft",
		"axisTop",
		"axisRight",
		"config",
		"barStyle",
		"lineStyle",
		"pieStyle",
		"radarStyle",
		"heatmapStyle",
		"scatterStyle",
		"funnelStyle",
		"treemapStyle",
		"sankeyStyle",
		"calendarStyle",
		"chordStyle",
	],

	// Computer vision / ML
	boundingBoxOverlay: [
		"src",
		"alt",
		"boxes",
		"showLabels",
		"showConfidence",
		"strokeWidth",
		"fontSize",
		"fit",
		"normalized",
		"interactive",
	],
	imageLabeler: [
		"src",
		"alt",
		"boxes",
		"labels",
		"disabled",
		"showLabels",
		"minBoxSize",
	],
	imageHotspot: [
		"src",
		"alt",
		"hotspots",
		"showMarkers",
		"markerStyle",
		"fit",
		"normalized",
		"showTooltips",
	],

	// Geo
	geoMap: [
		"viewport",
		"markers",
		"routes",
		"showControls",
		"showZoom",
		"showCompass",
		"showLocate",
		"showFullscreen",
		"interactive",
		"controlPosition",
		"clusterMarkers",
		"clusterRadius",
		"clusterMaxZoom",
	],

	// Graphs
	graph: [
		"nodes",
		"edges",
		"labelStyles",
		"showToolbar",
		"showSearch",
		"showLegend",
		"showInspector",
		"height",
	],
	ontologyGraph: [
		"ontologyId",
		"appId",
		"limit",
		"allowExpand",
		"allowSearch",
		"allowPaths",
		"allowActions",
		"allowCypher",
		"allowStyleEdit",
		"allowLimitChange",
		"showToolbar",
		"showLegend",
		"height",
	],

	// Planning
	calendar: [
		"events",
		"view",
		"date",
		"title",
		"density",
		"editable",
		"selectable",
		"firstDayOfWeek",
		"minTime",
		"maxTime",
		"slotDuration",
		"showWeekends",
		"showNowIndicator",
		"showAllDay",
		"showViewSwitcher",
		"locale",
		"height",
		"responsive",
		"compactBreakpoint",
	],
	gantt: [
		"tasks",
		"view",
		"title",
		"density",
		"editable",
		"draggable",
		"resizable",
		"showDependencies",
		"showProgress",
		"showToday",
		"showViewSwitcher",
		"showTaskList",
		"taskListWidth",
		"shadeWeekends",
		"rowHeight",
		"columns",
		"height",
		"responsive",
		"compactBreakpoint",
	],

	// Widget system
	widgetInstance: [
		"instanceId",
		"widgetId",
		"appId",
		"exposedPropValues",
		"actionBindings",
		"styleOverride",
	],
	microWidgetInstance: [
		"instanceId",
		"packageId",
		"widgetId",
		"packageVersion",
		"bundleHash",
		"contract",
		"props",
		"preview",
		"actionBindings",
	],
} as const satisfies {
	[K in A2UIComponentType]: readonly PropsOf<K>[];
};

type MissingProps = {
	[K in A2UIComponentType]: Exclude<
		PropsOf<K>,
		(typeof COMPONENT_PROPS)[K][number]
	>;
}[A2UIComponentType];

export type _EnsureComponentPropsComplete = ExpectNever<MissingProps>;
