/**
 * HTML elements that an A2UI box may render as.
 *
 * Keep this deliberately narrow: `box.as` can be generated by an agent or
 * resolved from runtime data, so accepting arbitrary tag names would allow
 * executable/resource elements such as `script`, `style`, or `object` into
 * the React tree.
 */
export const SEMANTIC_BOX_TAGS = [
	"div",
	"section",
	"article",
	"main",
	"aside",
	"header",
	"footer",
	"nav",
	"figure",
	"figcaption",
	"span",
] as const;

export type SemanticBoxTag = (typeof SEMANTIC_BOX_TAGS)[number];

const SEMANTIC_BOX_TAG_SET = new Set<string>(SEMANTIC_BOX_TAGS);

export function isSemanticBoxTag(value: unknown): value is SemanticBoxTag {
	return typeof value === "string" && SEMANTIC_BOX_TAG_SET.has(value);
}

/** Resolve an untrusted/generated box tag to a safe intrinsic element. */
export function normalizeSemanticBoxTag(value: unknown): SemanticBoxTag {
	return isSemanticBoxTag(value) ? value : "div";
}
