-- Aurora DSQL migration "device_console"
-- Generated by packages/api/scripts/dsql-migration.ts (--from-schema prisma/migrations-dsql/schema.snapshot.prisma) and rewritten by dsql-lint 0.2.17.
-- Every statement runs in its own transaction; apps/backend/aws/migration applies them one by one,
-- waits for the async index/validation jobs and records the migration in _prisma_migrations.
-- tables=2 indexes=1 foreign_keys=0 validations=0 statements=4
ALTER TABLE "ManagedDevice" ADD COLUMN     "displayName" TEXT,
ADD COLUMN     "revokedAt" BIGINT;

CREATE TABLE "DeviceCertificateNoticeMute" (
    "userId" TEXT NOT NULL,
    "deviceId" TEXT NOT NULL,
    "certificateId" TEXT NOT NULL,
    "until" BIGINT,
    "createdAt" BIGINT NOT NULL,

    CONSTRAINT "DeviceCertificateNoticeMute_pkey" PRIMARY KEY ("userId","deviceId","certificateId")
);

CREATE TABLE "DeviceAuthRejection" (
    "deviceId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "skewSeconds" BIGINT,
    "count" BIGINT NOT NULL DEFAULT 1,
    "firstAt" BIGINT NOT NULL,
    "lastAt" BIGINT NOT NULL,

    CONSTRAINT "DeviceAuthRejection_pkey" PRIMARY KEY ("deviceId")
);

CREATE INDEX ASYNC "DeviceCertificateNoticeMute_deviceId_idx" ON "DeviceCertificateNoticeMute"("deviceId");
