"use client";

import { motion } from "framer-motion";
import { AlertTriangleIcon } from "lucide-react";
import { useCallback, useRef } from "react";
import { toast } from "sonner";
import { useAssistantSurface } from "../../index";
import type { AssistantWidgetSurface } from "../../state/assistant-surface";
import { useGlobalChatStore } from "../../state/global-chat/global-chat-store";
import { PendingComponentsView } from "../flowpilot/PendingComponentsView";

/**
 * The builder's `applyComponents` applies its OWN staged components (it ignores the passed array),
 * closing over the staged state at publish time. After staging via `componentsGenerated`, wait for
 * the builder to republish the SAME surface (fresh object, same surfaceId) so the apply callback
 * sees the freshly staged components. Resolves null when no matching republish arrives — applying
 * through a stale or unrelated surface would silently no-op while reporting success.
 */
function waitForSurfaceRestage(
	previous: AssistantWidgetSurface,
	timeoutMs = 1500,
): Promise<AssistantWidgetSurface | null> {
	const isRestaged = (surface: AssistantWidgetSurface | null) =>
		surface !== null &&
		surface !== previous &&
		surface.surfaceId === previous.surfaceId;

	const current = useAssistantSurface.getState().widgetSurface;
	if (current && isRestaged(current)) return Promise.resolve(current);
	return new Promise((resolve) => {
		const settle = (surface: AssistantWidgetSurface | null) => {
			clearTimeout(timer);
			unsubscribe();
			resolve(surface);
		};
		const unsubscribe = useAssistantSurface.subscribe((state) => {
			if (isRestaged(state.widgetSurface)) settle(state.widgetSurface);
		});
		const timer = setTimeout(() => settle(null), timeoutMs);
	});
}

/**
 * Inline review card for UI components generated by a flowpilot_widget run: preview + Apply/Dismiss.
 * Apply stages the components in the open widget/page builder and applies them through the
 * surface's own pipeline; nothing touches the canvas until the user approves here. Components are
 * bound to the builder they were generated for (surfaceId) and never apply to a different one.
 */
export function PendingComponentsCard() {
	const pending = useGlobalChatStore((s) => s.pendingComponents);
	const setPendingComponents = useGlobalChatStore(
		(s) => s.setPendingComponents,
	);
	const widgetSurface = useAssistantSurface((s) => s.widgetSurface);
	const applyingRef = useRef(false);

	const handleApply = useCallback(async () => {
		if (applyingRef.current) return;
		const current = useGlobalChatStore.getState().pendingComponents;
		const surface = useAssistantSurface.getState().widgetSurface;
		if (!current) return;
		if (!surface) {
			toast.error(
				"The widget/page builder is closed — reopen it to apply the components.",
			);
			return;
		}
		if (current.surfaceId && surface.surfaceId !== current.surfaceId) {
			toast.error(
				"These components were generated for a different builder. Open that builder again to apply them.",
			);
			return;
		}
		applyingRef.current = true;
		try {
			surface.componentsGenerated(current.components);
			const restaged = await waitForSurfaceRestage(surface);
			if (!restaged) {
				// Keep the pending card — the components are the only copy.
				toast.error(
					"The builder did not pick up the components (it may have closed). Nothing was applied — try again with the builder open.",
				);
				return;
			}
			restaged.applyComponents(current.components, current.canvasSettings);
			setPendingComponents(null);
			toast.success(
				`Applied ${current.components.length} component${current.components.length === 1 ? "" : "s"} to the builder.`,
			);
		} finally {
			applyingRef.current = false;
		}
	}, [setPendingComponents]);

	const handleDismiss = useCallback(
		() => setPendingComponents(null),
		[setPendingComponents],
	);

	if (!pending || pending.components.length === 0) return null;

	const surfaceMismatch =
		widgetSurface !== null &&
		Boolean(pending.surfaceId) &&
		widgetSurface.surfaceId !== pending.surfaceId;

	return (
		<motion.div
			layout
			initial={{ opacity: 0, y: 8, scale: 0.98 }}
			animate={{ opacity: 1, y: 0, scale: 1 }}
			exit={{ opacity: 0, y: 8, scale: 0.98 }}
			transition={{ type: "spring", stiffness: 380, damping: 32 }}
			className="mx-3 mb-2 rounded-xl border border-border/50 bg-background/80 backdrop-blur-xl shadow-lg overflow-hidden shrink-0"
		>
			{!widgetSurface && (
				<div className="flex items-center gap-2 px-3 py-2 text-[11px] text-amber-600 dark:text-amber-400 bg-amber-500/5 border-b border-amber-500/15">
					<AlertTriangleIcon className="size-3.5 shrink-0" />
					The widget/page builder is closed — reopen it to apply these
					components.
				</div>
			)}
			{surfaceMismatch && (
				<div className="flex items-center gap-2 px-3 py-2 text-[11px] text-amber-600 dark:text-amber-400 bg-amber-500/5 border-b border-amber-500/15">
					<AlertTriangleIcon className="size-3.5 shrink-0" />
					These components were generated for a different builder — open that
					builder to apply them.
				</div>
			)}
			<PendingComponentsView
				components={pending.components}
				canvasSettings={pending.canvasSettings}
				warnings={pending.warnings}
				onApply={() => void handleApply()}
				onDismiss={handleDismiss}
			/>
		</motion.div>
	);
}
