// Derived from Playwright packages/playwright-core/src/server/usKeyboardLayout.ts @5f47e4f, Copyright Microsoft Corporation / Google Inc., Apache-2.0; modified by Rheosoph GmbH. See NOTICE.
pub(crate) struct KeyDefinition {
    pub code: &'static str,
    pub key: &'static str,
    pub key_code: u16,
    pub key_code_without_location: Option<u16>,
    pub shift_key: Option<&'static str>,
    pub shift_key_code: Option<u16>,
    pub text: Option<&'static str>,
    pub location: Option<u8>,
}

#[rustfmt::skip]
pub(crate) static US_KEYBOARD_LAYOUT: &[KeyDefinition] = &[
    KeyDefinition { code: "Escape", key: "Escape", key_code: 27, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "F1", key: "F1", key_code: 112, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "F2", key: "F2", key_code: 113, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "F3", key: "F3", key_code: 114, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "F4", key: "F4", key_code: 115, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "F5", key: "F5", key_code: 116, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "F6", key: "F6", key_code: 117, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "F7", key: "F7", key_code: 118, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "F8", key: "F8", key_code: 119, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "F9", key: "F9", key_code: 120, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "F10", key: "F10", key_code: 121, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "F11", key: "F11", key_code: 122, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "F12", key: "F12", key_code: 123, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Backquote", key: "`", key_code: 192, key_code_without_location: None, shift_key: Some("~"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Digit1", key: "1", key_code: 49, key_code_without_location: None, shift_key: Some("!"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Digit2", key: "2", key_code: 50, key_code_without_location: None, shift_key: Some("@"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Digit3", key: "3", key_code: 51, key_code_without_location: None, shift_key: Some("#"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Digit4", key: "4", key_code: 52, key_code_without_location: None, shift_key: Some("$"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Digit5", key: "5", key_code: 53, key_code_without_location: None, shift_key: Some("%"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Digit6", key: "6", key_code: 54, key_code_without_location: None, shift_key: Some("^"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Digit7", key: "7", key_code: 55, key_code_without_location: None, shift_key: Some("&"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Digit8", key: "8", key_code: 56, key_code_without_location: None, shift_key: Some("*"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Digit9", key: "9", key_code: 57, key_code_without_location: None, shift_key: Some("("), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Digit0", key: "0", key_code: 48, key_code_without_location: None, shift_key: Some(")"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Minus", key: "-", key_code: 189, key_code_without_location: None, shift_key: Some("_"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Equal", key: "=", key_code: 187, key_code_without_location: None, shift_key: Some("+"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Backslash", key: "\\", key_code: 220, key_code_without_location: None, shift_key: Some("|"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Backspace", key: "Backspace", key_code: 8, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Tab", key: "Tab", key_code: 9, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyQ", key: "q", key_code: 81, key_code_without_location: None, shift_key: Some("Q"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyW", key: "w", key_code: 87, key_code_without_location: None, shift_key: Some("W"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyE", key: "e", key_code: 69, key_code_without_location: None, shift_key: Some("E"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyR", key: "r", key_code: 82, key_code_without_location: None, shift_key: Some("R"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyT", key: "t", key_code: 84, key_code_without_location: None, shift_key: Some("T"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyY", key: "y", key_code: 89, key_code_without_location: None, shift_key: Some("Y"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyU", key: "u", key_code: 85, key_code_without_location: None, shift_key: Some("U"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyI", key: "i", key_code: 73, key_code_without_location: None, shift_key: Some("I"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyO", key: "o", key_code: 79, key_code_without_location: None, shift_key: Some("O"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyP", key: "p", key_code: 80, key_code_without_location: None, shift_key: Some("P"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "BracketLeft", key: "[", key_code: 219, key_code_without_location: None, shift_key: Some("{"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "BracketRight", key: "]", key_code: 221, key_code_without_location: None, shift_key: Some("}"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "CapsLock", key: "CapsLock", key_code: 20, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyA", key: "a", key_code: 65, key_code_without_location: None, shift_key: Some("A"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyS", key: "s", key_code: 83, key_code_without_location: None, shift_key: Some("S"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyD", key: "d", key_code: 68, key_code_without_location: None, shift_key: Some("D"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyF", key: "f", key_code: 70, key_code_without_location: None, shift_key: Some("F"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyG", key: "g", key_code: 71, key_code_without_location: None, shift_key: Some("G"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyH", key: "h", key_code: 72, key_code_without_location: None, shift_key: Some("H"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyJ", key: "j", key_code: 74, key_code_without_location: None, shift_key: Some("J"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyK", key: "k", key_code: 75, key_code_without_location: None, shift_key: Some("K"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyL", key: "l", key_code: 76, key_code_without_location: None, shift_key: Some("L"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Semicolon", key: ";", key_code: 186, key_code_without_location: None, shift_key: Some(":"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Quote", key: "'", key_code: 222, key_code_without_location: None, shift_key: Some("\""), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Enter", key: "Enter", key_code: 13, key_code_without_location: None, shift_key: None, shift_key_code: None, text: Some("\r"), location: None },
    KeyDefinition { code: "ShiftLeft", key: "Shift", key_code: 160, key_code_without_location: Some(16), shift_key: None, shift_key_code: None, text: None, location: Some(1) },
    KeyDefinition { code: "KeyZ", key: "z", key_code: 90, key_code_without_location: None, shift_key: Some("Z"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyX", key: "x", key_code: 88, key_code_without_location: None, shift_key: Some("X"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyC", key: "c", key_code: 67, key_code_without_location: None, shift_key: Some("C"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyV", key: "v", key_code: 86, key_code_without_location: None, shift_key: Some("V"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyB", key: "b", key_code: 66, key_code_without_location: None, shift_key: Some("B"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyN", key: "n", key_code: 78, key_code_without_location: None, shift_key: Some("N"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "KeyM", key: "m", key_code: 77, key_code_without_location: None, shift_key: Some("M"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Comma", key: ",", key_code: 188, key_code_without_location: None, shift_key: Some("<"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Period", key: ".", key_code: 190, key_code_without_location: None, shift_key: Some(">"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Slash", key: "/", key_code: 191, key_code_without_location: None, shift_key: Some("?"), shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "ShiftRight", key: "Shift", key_code: 161, key_code_without_location: Some(16), shift_key: None, shift_key_code: None, text: None, location: Some(2) },
    KeyDefinition { code: "ControlLeft", key: "Control", key_code: 162, key_code_without_location: Some(17), shift_key: None, shift_key_code: None, text: None, location: Some(1) },
    KeyDefinition { code: "MetaLeft", key: "Meta", key_code: 91, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: Some(1) },
    KeyDefinition { code: "AltLeft", key: "Alt", key_code: 164, key_code_without_location: Some(18), shift_key: None, shift_key_code: None, text: None, location: Some(1) },
    KeyDefinition { code: "Space", key: " ", key_code: 32, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "AltRight", key: "Alt", key_code: 165, key_code_without_location: Some(18), shift_key: None, shift_key_code: None, text: None, location: Some(2) },
    KeyDefinition { code: "AltGraph", key: "AltGraph", key_code: 225, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "MetaRight", key: "Meta", key_code: 92, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: Some(2) },
    KeyDefinition { code: "ContextMenu", key: "ContextMenu", key_code: 93, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "ControlRight", key: "Control", key_code: 163, key_code_without_location: Some(17), shift_key: None, shift_key_code: None, text: None, location: Some(2) },
    KeyDefinition { code: "PrintScreen", key: "PrintScreen", key_code: 44, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "ScrollLock", key: "ScrollLock", key_code: 145, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Pause", key: "Pause", key_code: 19, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "PageUp", key: "PageUp", key_code: 33, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "PageDown", key: "PageDown", key_code: 34, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Insert", key: "Insert", key_code: 45, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Delete", key: "Delete", key_code: 46, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "Home", key: "Home", key_code: 36, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "End", key: "End", key_code: 35, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "ArrowLeft", key: "ArrowLeft", key_code: 37, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "ArrowUp", key: "ArrowUp", key_code: 38, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "ArrowRight", key: "ArrowRight", key_code: 39, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "ArrowDown", key: "ArrowDown", key_code: 40, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "AudioVolumeMute", key: "AudioVolumeMute", key_code: 173, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "AudioVolumeDown", key: "AudioVolumeDown", key_code: 174, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "AudioVolumeUp", key: "AudioVolumeUp", key_code: 175, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "MediaTrackNext", key: "MediaTrackNext", key_code: 176, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "MediaTrackPrevious", key: "MediaTrackPrevious", key_code: 177, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "MediaPlayPause", key: "MediaPlayPause", key_code: 179, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "NumLock", key: "NumLock", key_code: 144, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: None },
    KeyDefinition { code: "NumpadDivide", key: "/", key_code: 111, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: Some(3) },
    KeyDefinition { code: "NumpadMultiply", key: "*", key_code: 106, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: Some(3) },
    KeyDefinition { code: "NumpadSubtract", key: "-", key_code: 109, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: Some(3) },
    KeyDefinition { code: "Numpad7", key: "Home", key_code: 36, key_code_without_location: None, shift_key: Some("7"), shift_key_code: Some(103), text: None, location: Some(3) },
    KeyDefinition { code: "Numpad8", key: "ArrowUp", key_code: 38, key_code_without_location: None, shift_key: Some("8"), shift_key_code: Some(104), text: None, location: Some(3) },
    KeyDefinition { code: "Numpad9", key: "PageUp", key_code: 33, key_code_without_location: None, shift_key: Some("9"), shift_key_code: Some(105), text: None, location: Some(3) },
    KeyDefinition { code: "Numpad4", key: "ArrowLeft", key_code: 37, key_code_without_location: None, shift_key: Some("4"), shift_key_code: Some(100), text: None, location: Some(3) },
    KeyDefinition { code: "Numpad5", key: "Clear", key_code: 12, key_code_without_location: None, shift_key: Some("5"), shift_key_code: Some(101), text: None, location: Some(3) },
    KeyDefinition { code: "Numpad6", key: "ArrowRight", key_code: 39, key_code_without_location: None, shift_key: Some("6"), shift_key_code: Some(102), text: None, location: Some(3) },
    KeyDefinition { code: "NumpadAdd", key: "+", key_code: 107, key_code_without_location: None, shift_key: None, shift_key_code: None, text: None, location: Some(3) },
    KeyDefinition { code: "Numpad1", key: "End", key_code: 35, key_code_without_location: None, shift_key: Some("1"), shift_key_code: Some(97), text: None, location: Some(3) },
    KeyDefinition { code: "Numpad2", key: "ArrowDown", key_code: 40, key_code_without_location: None, shift_key: Some("2"), shift_key_code: Some(98), text: None, location: Some(3) },
    KeyDefinition { code: "Numpad3", key: "PageDown", key_code: 34, key_code_without_location: None, shift_key: Some("3"), shift_key_code: Some(99), text: None, location: Some(3) },
    KeyDefinition { code: "Numpad0", key: "Insert", key_code: 45, key_code_without_location: None, shift_key: Some("0"), shift_key_code: Some(96), text: None, location: Some(3) },
    KeyDefinition { code: "NumpadDecimal", key: "Delete", key_code: 46, key_code_without_location: None, shift_key: Some("."), shift_key_code: Some(110), text: None, location: Some(3) },
    KeyDefinition { code: "NumpadEnter", key: "Enter", key_code: 13, key_code_without_location: None, shift_key: None, shift_key_code: None, text: Some("\r"), location: Some(3) },
];
