import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import {
	GENERATED_TS_PATH,
	REPO_ROOT,
	RULES_PATH,
	providersSha256,
	readCatalog,
	rulesFileVersion,
	sha256Hex,
	writeCatalog,
} from "./lib";

function renderModule(rules: string, catalogJson: string): string {
	return `// Generated by tools/widget-sources/generate.ts (mise run widget-sources:generate). Do not edit.
// PUBLIC_SUFFIX_RULES is derived from the Public Suffix List (MPL-2.0, https://mozilla.org/MPL/2.0/).

export type WidgetSourceMatchType =
	| "service-host"
	| "service-subtree"
	| "shared-suffix"
	| "shared-host"
	| "shared-subtree"
	| "attribution";

export interface WidgetSourceMatch {
	readonly type: WidgetSourceMatchType;
	readonly domain: string;
}

export interface WidgetSourceProvider {
	readonly id: string;
	readonly name: string;
	readonly aboutKey?: string;
	readonly docs: readonly string[];
	readonly match: readonly WidgetSourceMatch[];
	readonly receives?: boolean;
	readonly userContent?: boolean;
}

export interface WidgetSourceCatalog {
	readonly catalogVersion: number;
	readonly providersSha256: string;
	readonly publicSuffixRules: { readonly pslVersion: string; readonly sha256: string };
	readonly providers: readonly WidgetSourceProvider[];
}

export const WIDGET_SOURCE_CATALOG: WidgetSourceCatalog = ${catalogJson};

export const WIDGET_SOURCE_DATA_PIN = {
	catalogVersion: WIDGET_SOURCE_CATALOG.catalogVersion,
	providersSha256: WIDGET_SOURCE_CATALOG.providersSha256,
	pslVersion: WIDGET_SOURCE_CATALOG.publicSuffixRules.pslVersion,
	rulesSha256: WIDGET_SOURCE_CATALOG.publicSuffixRules.sha256,
} as const;

export const PUBLIC_SUFFIX_RULES: string = ${JSON.stringify(rules)};
`;
}

export function generate(): void {
	const rules = readFileSync(RULES_PATH, "utf8");
	const pslVersion = rulesFileVersion(rules);
	if (!pslVersion) {
		throw new Error(`${RULES_PATH} has no psl-version header`);
	}
	const catalog = readCatalog();
	const hash = providersSha256(catalog.providers);
	if (hash !== catalog.providersSha256) {
		catalog.catalogVersion += 1;
		catalog.providersSha256 = hash;
	}
	catalog.publicSuffixRules = { pslVersion, sha256: sha256Hex(rules) };
	writeCatalog(catalog);

	mkdirSync(dirname(GENERATED_TS_PATH), { recursive: true });
	writeFileSync(
		GENERATED_TS_PATH,
		renderModule(rules, JSON.stringify(catalog, null, "\t")),
	);
	const format = spawnSync(
		"bunx",
		["biome", "format", "--write", GENERATED_TS_PATH],
		{ cwd: REPO_ROOT, stdio: "inherit" },
	);
	if (format.status !== 0) {
		throw new Error("biome format failed on the generated module");
	}
	console.log(
		`widget-sources:generate: catalog ${catalog.catalogVersion}, PSL ${pslVersion}`,
	);
}

if (import.meta.main) {
	generate();
}
