//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ; use super :: sea_orm_active_enums :: AiGpaiPosture ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "AiActModelRegistry")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_type = "Text")] pub provider : String , # [sea_orm (column_name = "modelId" , column_type = "Text")] pub model_id : String , pub posture : AiGpaiPosture , pub hosted : bool , # [sea_orm (column_name = "openLicence")] pub open_licence : bool , # [sea_orm (column_name = "systemicRisk")] pub systemic_risk : bool , pub vetted : bool , # [sea_orm (column_type = "Text" , nullable)] pub note : Option < String > , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "updatedAt")] pub updated_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }