//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::AppType;
use super::sea_orm_active_enums::Category;
use super::sea_orm_active_enums::ExecutionMode;
use super::sea_orm_active_enums::Status;
use super::sea_orm_active_enums::Visibility;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "App")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub status: Status,
    pub visibility: Visibility,
    #[sea_orm(column_type = "Text", nullable)]
    pub changelog: Option<String>,
    #[sea_orm(column_name = "defaultRoleId", column_type = "Text", nullable, unique)]
    pub default_role_id: Option<String>,
    #[sea_orm(column_name = "ownerRoleId", column_type = "Text", nullable, unique)]
    pub owner_role_id: Option<String>,
    #[sea_orm(column_name = "primaryCategory")]
    pub primary_category: Option<Category>,
    #[sea_orm(column_name = "secondaryCategory")]
    pub secondary_category: Option<Category>,
    #[sea_orm(column_name = "ratingSum")]
    pub rating_sum: i64,
    #[sea_orm(column_name = "ratingCount")]
    pub rating_count: i64,
    #[sea_orm(column_name = "downloadCount")]
    pub download_count: i64,
    #[sea_orm(column_name = "interactionsCount")]
    pub interactions_count: i64,
    #[sea_orm(column_name = "avgRating", column_type = "Double", nullable)]
    pub avg_rating: Option<f64>,
    #[sea_orm(column_name = "relevanceScore", column_type = "Double", nullable)]
    pub relevance_score: Option<f64>,
    #[sea_orm(column_name = "totalSize")]
    pub total_size: i64,
    pub price: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub version: Option<String>,
    #[sea_orm(column_name = "executionMode")]
    pub execution_mode: ExecutionMode,
    pub bits: Option<Vec<String>>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "allowForking")]
    pub allow_forking: bool,
    #[sea_orm(column_name = "forkedAt")]
    pub forked_at: Option<DateTime>,
    #[sea_orm(column_name = "forkedFrom", column_type = "Text", nullable)]
    pub forked_from: Option<String>,
    #[sea_orm(column_name = "appType")]
    pub app_type: Option<AppType>,
    #[sea_orm(column_name = "forkPolicy", column_type = "JsonBinary", nullable)]
    pub fork_policy: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ai_act_assessment::Entity")]
    AiActAssessment,
    #[sea_orm(has_many = "super::ai_act_model_observation::Entity")]
    AiActModelObservation,
    #[sea_orm(has_many = "super::app_analytics_daily::Entity")]
    AppAnalyticsDaily,
    #[sea_orm(has_many = "super::app_board_score::Entity")]
    AppBoardScore,
    #[sea_orm(has_many = "super::app_discount::Entity")]
    AppDiscount,
    #[sea_orm(has_many = "super::app_group::Entity")]
    AppGroup,
    #[sea_orm(has_many = "super::app_group_member::Entity")]
    AppGroupMember,
    #[sea_orm(has_many = "super::app_package::Entity")]
    AppPackage,
    #[sea_orm(has_many = "super::app_process_note::Entity")]
    AppProcessNote,
    #[sea_orm(has_many = "super::app_purchase::Entity")]
    AppPurchase,
    #[sea_orm(has_many = "super::app_sales_daily::Entity")]
    AppSalesDaily,
    #[sea_orm(has_many = "super::app_usage_limit::Entity")]
    AppUsageLimit,
    #[sea_orm(has_many = "super::board_sync::Entity")]
    BoardSync,
    #[sea_orm(has_many = "super::comment::Entity")]
    Comment,
    #[sea_orm(has_many = "super::course_app_link::Entity")]
    CourseAppLink,
    #[sea_orm(has_many = "super::embedding_usage_tracking::Entity")]
    EmbeddingUsageTracking,
    #[sea_orm(has_many = "super::event::Entity")]
    Event,
    #[sea_orm(has_many = "super::event_alias::Entity")]
    EventAlias,
    #[sea_orm(has_many = "super::event_remote_auth::Entity")]
    EventRemoteAuth,
    #[sea_orm(has_many = "super::event_remote_registration::Entity")]
    EventRemoteRegistration,
    #[sea_orm(has_many = "super::event_setup::Entity")]
    EventSetup,
    #[sea_orm(has_many = "super::event_sink::Entity")]
    EventSink,
    #[sea_orm(has_many = "super::execution_run::Entity")]
    ExecutionRun,
    #[sea_orm(has_many = "super::execution_usage_tracking::Entity")]
    ExecutionUsageTracking,
    #[sea_orm(has_many = "super::feedback::Entity")]
    Feedback,
    #[sea_orm(has_many = "super::invitation::Entity")]
    Invitation,
    #[sea_orm(has_many = "super::invite_link::Entity")]
    InviteLink,
    #[sea_orm(has_many = "super::join_queue::Entity")]
    JoinQueue,
    #[sea_orm(has_many = "super::llm_usage_tracking::Entity")]
    LlmUsageTracking,
    #[sea_orm(has_many = "super::membership::Entity")]
    Membership,
    #[sea_orm(has_many = "super::meta::Entity")]
    Meta,
    #[sea_orm(has_many = "super::notification::Entity")]
    Notification,
    #[sea_orm(has_many = "super::page::Entity")]
    Page,
    #[sea_orm(has_many = "super::publication_request::Entity")]
    PublicationRequest,
    #[sea_orm(has_many = "super::regression_suite::Entity")]
    RegressionSuite,
    #[sea_orm(has_many = "super::regression_suite_run::Entity")]
    RegressionSuiteRun,
    #[sea_orm(
        belongs_to = "super::role::Entity",
        from = "Column::DefaultRoleId",
        to = "super::role::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Role2,
    #[sea_orm(
        belongs_to = "super::role::Entity",
        from = "Column::OwnerRoleId",
        to = "super::role::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Role1,
    #[sea_orm(has_many = "super::technical_user::Entity")]
    TechnicalUser,
    #[sea_orm(has_many = "super::template::Entity")]
    Template,
    #[sea_orm(has_many = "super::widget::Entity")]
    Widget,
}

impl Related<super::ai_act_assessment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiActAssessment.def()
    }
}

impl Related<super::ai_act_model_observation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiActModelObservation.def()
    }
}

impl Related<super::app_analytics_daily::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppAnalyticsDaily.def()
    }
}

impl Related<super::app_board_score::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppBoardScore.def()
    }
}

impl Related<super::app_discount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppDiscount.def()
    }
}

impl Related<super::app_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppGroup.def()
    }
}

impl Related<super::app_group_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppGroupMember.def()
    }
}

impl Related<super::app_package::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppPackage.def()
    }
}

impl Related<super::app_process_note::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppProcessNote.def()
    }
}

impl Related<super::app_purchase::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppPurchase.def()
    }
}

impl Related<super::app_sales_daily::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppSalesDaily.def()
    }
}

impl Related<super::app_usage_limit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppUsageLimit.def()
    }
}

impl Related<super::board_sync::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BoardSync.def()
    }
}

impl Related<super::comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comment.def()
    }
}

impl Related<super::course_app_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseAppLink.def()
    }
}

impl Related<super::embedding_usage_tracking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmbeddingUsageTracking.def()
    }
}

impl Related<super::event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Event.def()
    }
}

impl Related<super::event_alias::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventAlias.def()
    }
}

impl Related<super::event_remote_auth::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventRemoteAuth.def()
    }
}

impl Related<super::event_remote_registration::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventRemoteRegistration.def()
    }
}

impl Related<super::event_setup::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventSetup.def()
    }
}

impl Related<super::event_sink::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventSink.def()
    }
}

impl Related<super::execution_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExecutionRun.def()
    }
}

impl Related<super::execution_usage_tracking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExecutionUsageTracking.def()
    }
}

impl Related<super::feedback::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Feedback.def()
    }
}

impl Related<super::invitation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invitation.def()
    }
}

impl Related<super::invite_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InviteLink.def()
    }
}

impl Related<super::join_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JoinQueue.def()
    }
}

impl Related<super::llm_usage_tracking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LlmUsageTracking.def()
    }
}

impl Related<super::membership::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Membership.def()
    }
}

impl Related<super::meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meta.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::page::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Page.def()
    }
}

impl Related<super::publication_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PublicationRequest.def()
    }
}

impl Related<super::regression_suite::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RegressionSuite.def()
    }
}

impl Related<super::regression_suite_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RegressionSuiteRun.def()
    }
}

impl Related<super::technical_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TechnicalUser.def()
    }
}

impl Related<super::template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Template.def()
    }
}

impl Related<super::widget::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Widget.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
