//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ; use super :: sea_orm_active_enums :: AppConnectionStatus ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "AppConnection")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "sourceAppId" , column_type = "Text")] pub source_app_id : String , # [sea_orm (column_name = "targetAppId" , column_type = "Text")] pub target_app_id : String , # [sea_orm (column_name = "roleId" , column_type = "Text" , nullable)] pub role_id : Option < String > , pub status : AppConnectionStatus , # [sea_orm (column_type = "Text" , nullable)] pub comment : Option < String > , # [sea_orm (column_name = "requestedByUserId" , column_type = "Text" , nullable)] pub requested_by_user_id : Option < String > , # [sea_orm (column_name = "approvedByUserId" , column_type = "Text" , nullable)] pub approved_by_user_id : Option < String > , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "updatedAt")] pub updated_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::app::Entity" , from = "Column::SourceAppId" , to = "super::app::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] App2 , # [sea_orm (belongs_to = "super::app::Entity" , from = "Column::TargetAppId" , to = "super::app::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] App1 , # [sea_orm (belongs_to = "super::role::Entity" , from = "Column::RoleId" , to = "super::role::Column::Id" , on_update = "Cascade" , on_delete = "SetNull" ,)] Role , }

impl Related < super :: role :: Entity > for Entity { fn to () -> RelationDef { Relation :: Role . def () } }

impl ActiveModelBehavior for ActiveModel { }