//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ; use super :: sea_orm_active_enums :: AppGroupMemberKind ; use super :: sea_orm_active_enums :: AppGroupMemberStatus ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "AppGroupMember")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "groupId" , column_type = "Text")] pub group_id : String , # [sea_orm (column_name = "appId" , column_type = "Text")] pub app_id : String , pub kind : AppGroupMemberKind , pub status : AppGroupMemberStatus , pub position : i32 , # [sea_orm (column_name = "addedByUserId" , column_type = "Text" , nullable)] pub added_by_user_id : Option < String > , # [sea_orm (column_name = "approvedByUserId" , column_type = "Text" , nullable)] pub approved_by_user_id : Option < String > , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "updatedAt")] pub updated_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::app::Entity" , from = "Column::AppId" , to = "super::app::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] App , # [sea_orm (belongs_to = "super::app_group::Entity" , from = "Column::GroupId" , to = "super::app_group::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] AppGroup , }

impl Related < super :: app :: Entity > for Entity { fn to () -> RelationDef { Relation :: App . def () } }

impl Related < super :: app_group :: Entity > for Entity { fn to () -> RelationDef { Relation :: AppGroup . def () } }

impl ActiveModelBehavior for ActiveModel { }