//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "AppUsageLimit")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "appId" , column_type = "Text")] pub app_id : String , # [sea_orm (column_name = "userId" , column_type = "Text")] pub user_id : String , # [sea_orm (column_type = "Text")] pub period : String , # [sea_orm (column_name = "costMicroDollars")] pub cost_micro_dollars : Option < i64 > , # [sea_orm (column_name = "tokenLimit")] pub token_limit : Option < i64 > , pub enabled : bool , pub hard : bool , # [sea_orm (column_name = "warningThresholdPercent")] pub warning_threshold_percent : Option < i32 > , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "updatedAt")] pub updated_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::app::Entity" , from = "Column::AppId" , to = "super::app::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] App , }

impl Related < super :: app :: Entity > for Entity { fn to () -> RelationDef { Relation :: App . def () } }

impl ActiveModelBehavior for ActiveModel { }