//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppBoardScore")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "appId", column_type = "Text")]
    pub app_id: String,
    #[sea_orm(column_name = "boardId", column_type = "Text")]
    pub board_id: String,
    pub security: i32,
    pub privacy: i32,
    pub performance: i32,
    pub governance: i32,
    pub reliability: i32,
    pub cost: i32,
    #[sea_orm(column_name = "worstScore")]
    pub worst_score: i32,
    #[sea_orm(column_name = "nodeCount")]
    pub node_count: i32,
    #[sea_orm(column_name = "scoredNodeCount")]
    pub scored_node_count: i32,
    #[sea_orm(column_name = "connectionCount")]
    pub connection_count: i32,
    #[sea_orm(column_name = "flaggedPatterns", column_type = "Json", nullable)]
    pub flagged_patterns: Option<Json>,
    #[sea_orm(column_name = "summary", column_type = "Json", nullable)]
    pub summary: Option<crate::routes::app::board::scoring::BoardSummaryMeta>,
    #[sea_orm(column_name = "computedAt")]
    pub computed_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app::Entity",
        from = "Column::AppId",
        to = "super::app::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    App,
}

impl Related<super::app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::App.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
