//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::BitType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Bit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub authors: Option<Vec<String>>,
    pub r#type: BitType,
    #[sea_orm(column_type = "Text", nullable)]
    pub repository: Option<String>,
    #[sea_orm(column_name = "downloadLink", column_type = "Text", nullable)]
    pub download_link: Option<String>,
    #[sea_orm(column_name = "fileName", column_type = "Text", nullable)]
    pub file_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub hash: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub parameters: Option<Json>,
    pub size: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub hub: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub license: Option<String>,
    pub dependencies: Option<Vec<String>>,
    #[sea_orm(
        column_name = "dependencyTreeHash",
        column_type = "Text",
        nullable,
        unique
    )]
    pub dependency_tree_hash: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "modelSlug", column_type = "Text", nullable)]
    pub model_slug: Option<String>,
    #[sea_orm(has_many)]
    pub bit_caches: HasMany<super::bit_cache::Entity>,
    #[sea_orm(has_one)]
    pub bit_tree_cache: HasOne<super::bit_tree_cache::Entity>,
    #[sea_orm(
        belongs_to,
        from = "model_slug",
        to = "slug",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub llm_model: BelongsTo<Option<super::llm_model::Entity>>,
    #[sea_orm(has_many)]
    pub metas: HasMany<super::meta::Entity>,
    #[sea_orm(has_many)]
    pub swimlane_items: HasMany<super::swimlane_item::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
