//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "Certificate")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "userId" , column_type = "Text")] pub user_id : String , # [sea_orm (column_name = "courseId" , column_type = "Text")] pub course_id : String , # [sea_orm (column_name = "issuedAt")] pub issued_at : DateTime , # [sea_orm (column_type = "Text")] pub hash : String , # [sea_orm (column_name = "pdfUrl" , column_type = "Text" , nullable)] pub pdf_url : Option < String > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::course::Entity" , from = "Column::CourseId" , to = "super::course::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] Course , }

impl Related < super :: course :: Entity > for Entity { fn to () -> RelationDef { Relation :: Course . def () } }

impl ActiveModelBehavior for ActiveModel { }