//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ; use super :: sea_orm_active_enums :: ChallengeKind ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "Challenge")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "lessonId" , column_type = "Text")] pub lesson_id : String , pub position : i32 , pub kind : ChallengeKind , # [sea_orm (column_type = "Text")] pub prompt : String , # [sea_orm (column_type = "Text" , nullable)] pub explanation : Option < String > , # [sea_orm (column_type = "JsonBinary")] pub payload : Json , pub points : i32 , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "updatedAt")] pub updated_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::lesson::Entity" , from = "Column::LessonId" , to = "super::lesson::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] Lesson , # [sea_orm (has_many = "super::user_challenge_attempt::Entity")] UserChallengeAttempt , # [sea_orm (has_many = "super::weekly_challenge::Entity")] WeeklyChallenge , }

impl Related < super :: lesson :: Entity > for Entity { fn to () -> RelationDef { Relation :: Lesson . def () } }

impl Related < super :: user_challenge_attempt :: Entity > for Entity { fn to () -> RelationDef { Relation :: UserChallengeAttempt . def () } }

impl Related < super :: weekly_challenge :: Entity > for Entity { fn to () -> RelationDef { Relation :: WeeklyChallenge . def () } }

impl ActiveModelBehavior for ActiveModel { }