//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::{CourseCategory, CourseDifficulty};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Course")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub language: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub slug: Option<String>,
    pub difficulty: CourseDifficulty,
    pub category: CourseCategory,
    #[sea_orm(column_name = "estimatedMinutes")]
    pub estimated_minutes: i32,
    #[sea_orm(column_name = "isPublished")]
    pub is_published: bool,
    #[sea_orm(column_name = "authorId", column_type = "Text", nullable)]
    pub author_id: Option<String>,
    #[sea_orm(column_name = "iconUrl", column_type = "Text", nullable)]
    pub icon_url: Option<String>,
    #[sea_orm(column_name = "bannerUrl", column_type = "Text", nullable)]
    pub banner_url: Option<String>,
    pub tags: Option<Vec<String>>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::course_app_link::Entity")]
    CourseAppLink,
    #[sea_orm(has_many = "super::course_module::Entity")]
    CourseModule,
    #[sea_orm(has_many = "super::user_course_enrollment::Entity")]
    UserCourseEnrollment,
    #[sea_orm(has_many = "super::certificate::Entity")]
    Certificate,
    #[sea_orm(has_many = "super::meta::Entity")]
    Meta,
    #[sea_orm(has_many = "super::learning_path_course::Entity")]
    LearningPathCourse,
}

impl Related<super::course_app_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseAppLink.def()
    }
}

impl Related<super::course_module::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseModule.def()
    }
}

impl Related<super::user_course_enrollment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCourseEnrollment.def()
    }
}

impl Related<super::certificate::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Certificate.def()
    }
}

impl Related<super::meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meta.def()
    }
}

impl Related<super::learning_path_course::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LearningPathCourse.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
