//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "EmbeddingUsageTracking")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "modelId", column_type = "Text")]
    pub model_id: String,
    #[sea_orm(column_name = "tokenCount")]
    pub token_count: i64,
    #[sea_orm(column_type = "Double", nullable)]
    pub latency: Option<f64>,
    #[sea_orm(column_name = "userId", column_type = "Text", nullable)]
    pub user_id: Option<String>,
    #[sea_orm(column_name = "technicalUserId", column_type = "Text", nullable)]
    pub technical_user_id: Option<String>,
    #[sea_orm(column_name = "appId", column_type = "Text", nullable)]
    pub app_id: Option<String>,
    pub price: i64,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub endpoint: Option<String>,
    #[sea_orm(column_name = "invocationId", column_type = "Text", nullable)]
    pub invocation_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider: Option<String>,
    #[sea_orm(column_name = "providerRequestId", column_type = "Text", nullable)]
    pub provider_request_id: Option<String>,
    #[sea_orm(column_name = "rawUsage", column_type = "JsonBinary", nullable)]
    pub raw_usage: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app::Entity",
        from = "Column::AppId",
        to = "super::app::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    App,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User,
    #[sea_orm(
        belongs_to = "super::technical_user::Entity",
        from = "Column::TechnicalUserId",
        to = "super::technical_user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    TechnicalUser,
}

impl Related<super::app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::App.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::technical_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TechnicalUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
