//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "appId", column_type = "Text")]
    pub app_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_name = "eventType", column_type = "Text")]
    pub event_type: String,
    pub active: bool,
    pub priority: i32,
    #[sea_orm(column_name = "boardId", column_type = "Text", nullable)]
    pub board_id: Option<String>,
    #[sea_orm(column_name = "boardVersion", column_type = "Text", nullable)]
    pub board_version: Option<String>,
    #[sea_orm(column_name = "nodeId", column_type = "Text", nullable)]
    pub node_id: Option<String>,
    #[sea_orm(column_name = "pageId", column_type = "Text", nullable)]
    pub page_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub route: Option<String>,
    #[sea_orm(column_name = "isDefault")]
    pub is_default: bool,
    #[sea_orm(column_name = "eventVersion", column_type = "Text")]
    pub event_version: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub variables: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub config: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub inputs: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub notes: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub canary: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub variants: Option<Json>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "executionMode", column_type = "Text")]
    pub execution_mode: String,
    #[sea_orm(column_name = "lastSetupAt")]
    pub last_setup_at: Option<DateTime>,
    #[sea_orm(column_name = "lastSetupError", column_type = "Text", nullable)]
    pub last_setup_error: Option<String>,
    #[sea_orm(column_name = "lastSetupVersion", column_type = "Text", nullable)]
    pub last_setup_version: Option<String>,
    #[sea_orm(column_name = "setupStatus", column_type = "Text", nullable)]
    pub setup_status: Option<String>,
    #[sea_orm(
        column_name = "correlationMappings",
        column_type = "JsonBinary",
        nullable
    )]
    pub correlation_mappings: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub exposure: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app::Entity",
        from = "Column::AppId",
        to = "super::app::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    App,
    #[sea_orm(has_many = "super::event_alias::Entity")]
    EventAlias,
    #[sea_orm(has_many = "super::event_remote_auth::Entity")]
    EventRemoteAuth,
    #[sea_orm(has_many = "super::event_remote_registration::Entity")]
    EventRemoteRegistration,
    #[sea_orm(has_many = "super::event_setup::Entity")]
    EventSetup,
    #[sea_orm(has_one = "super::event_sink::Entity")]
    EventSink,
}

impl Related<super::app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::App.def()
    }
}

impl Related<super::event_alias::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventAlias.def()
    }
}

impl Related<super::event_remote_auth::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventRemoteAuth.def()
    }
}

impl Related<super::event_remote_registration::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventRemoteRegistration.def()
    }
}

impl Related<super::event_setup::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventSetup.def()
    }
}

impl Related<super::event_sink::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventSink.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
