//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "EventSetup")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "appId" , column_type = "Text")] pub app_id : String , # [sea_orm (column_name = "eventId" , column_type = "Text")] pub event_id : String , # [sea_orm (column_type = "Text")] pub variant : String , # [sea_orm (column_name = "eventVersion" , column_type = "Text")] pub event_version : String , # [sea_orm (column_name = "boardId" , column_type = "Text")] pub board_id : String , # [sea_orm (column_name = "boardVersion" , column_type = "Text" , nullable)] pub board_version : Option < String > , # [sea_orm (column_name = "setupStatus" , column_type = "Text" , nullable)] pub setup_status : Option < String > , # [sea_orm (column_name = "lastSetupAt")] pub last_setup_at : Option < DateTime > , # [sea_orm (column_name = "lastSetupError" , column_type = "Text" , nullable)] pub last_setup_error : Option < String > , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "updatedAt")] pub updated_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::app::Entity" , from = "Column::AppId" , to = "super::app::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] App , # [sea_orm (belongs_to = "super::event::Entity" , from = "Column::EventId" , to = "super::event::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] Event , }

impl Related < super :: app :: Entity > for Entity { fn to () -> RelationDef { Relation :: App . def () } }

impl Related < super :: event :: Entity > for Entity { fn to () -> RelationDef { Relation :: Event . def () } }

impl ActiveModelBehavior for ActiveModel { }