//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "EventRemoteRegistration")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "appId" , column_type = "Text")] pub app_id : String , # [sea_orm (column_name = "eventId" , column_type = "Text")] pub event_id : String , # [sea_orm (column_name = "eventVersion" , column_type = "Text")] pub event_version : String , # [sea_orm (column_type = "Text")] pub kind : String , # [sea_orm (column_type = "Text" , nullable)] pub method : Option < String > , # [sea_orm (column_type = "Text")] pub path : String , # [sea_orm (column_name = "nodeId" , column_type = "Text" , nullable)] pub node_id : Option < String > , # [sea_orm (column_name = "schemaJson" , column_type = "JsonBinary" , nullable)] pub schema_json : Option < Json > , # [sea_orm (column_name = "extrasJson" , column_type = "JsonBinary" , nullable)] pub extras_json : Option < Json > , # [sea_orm (column_name = "authId" , column_type = "Text" , nullable)] pub auth_id : Option < String > , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::app::Entity" , from = "Column::AppId" , to = "super::app::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] App , # [sea_orm (belongs_to = "super::event::Entity" , from = "Column::EventId" , to = "super::event::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] Event , # [sea_orm (belongs_to = "super::event_remote_auth::Entity" , from = "Column::AuthId" , to = "super::event_remote_auth::Column::Id" , on_update = "Cascade" , on_delete = "SetNull" ,)] EventRemoteAuth , }

impl Related < super :: app :: Entity > for Entity { fn to () -> RelationDef { Relation :: App . def () } }

impl Related < super :: event :: Entity > for Entity { fn to () -> RelationDef { Relation :: Event . def () } }

impl Related < super :: event_remote_auth :: Entity > for Entity { fn to () -> RelationDef { Relation :: EventRemoteAuth . def () } }

impl ActiveModelBehavior for ActiveModel { }