//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "LearningPath")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub slug: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub position: i32,
    #[sea_orm(column_name = "isPublished")]
    pub is_published: bool,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::learning_path_course::Entity")]
    LearningPathCourse,
}

impl Related<super::learning_path_course::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LearningPathCourse.def()
    }
}

impl Related<super::course::Entity> for Entity {
    fn to() -> RelationDef {
        super::learning_path_course::Relation::Course.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::learning_path_course::Relation::LearningPath
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
