//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "LearningPathCourse")]
pub struct Model {
    #[sea_orm(
        column_name = "pathId",
        primary_key,
        auto_increment = false,
        column_type = "Text"
    )]
    pub path_id: String,
    #[sea_orm(
        column_name = "courseId",
        primary_key,
        auto_increment = false,
        column_type = "Text"
    )]
    pub course_id: String,
    pub position: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::course::Entity",
        from = "Column::CourseId",
        to = "super::course::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Course,
    #[sea_orm(
        belongs_to = "super::learning_path::Entity",
        from = "Column::PathId",
        to = "super::learning_path::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    LearningPath,
}

impl Related<super::course::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Course.def()
    }
}

impl Related<super::learning_path::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LearningPath.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
