//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "Lesson")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "moduleId" , column_type = "Text")] pub module_id : String , # [sea_orm (column_type = "Text")] pub title : String , pub position : i32 , # [sea_orm (column_type = "Text")] pub language : String , # [sea_orm (column_type = "Text")] pub content : String , # [sea_orm (column_name = "videoUrl" , column_type = "Text" , nullable)] pub video_url : Option < String > , # [sea_orm (column_name = "estimatedMinutes")] pub estimated_minutes : i32 , # [sea_orm (column_name = "isOptional")] pub is_optional : bool , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "updatedAt")] pub updated_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (has_many = "super::challenge::Entity")] Challenge , # [sea_orm (belongs_to = "super::course_module::Entity" , from = "Column::ModuleId" , to = "super::course_module::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] CourseModule , # [sea_orm (has_many = "super::lesson_app_ref::Entity")] LessonAppRef , # [sea_orm (has_many = "super::user_lesson_progress::Entity")] UserLessonProgress , }

impl Related < super :: challenge :: Entity > for Entity { fn to () -> RelationDef { Relation :: Challenge . def () } }

impl Related < super :: course_module :: Entity > for Entity { fn to () -> RelationDef { Relation :: CourseModule . def () } }

impl Related < super :: lesson_app_ref :: Entity > for Entity { fn to () -> RelationDef { Relation :: LessonAppRef . def () } }

impl Related < super :: user_lesson_progress :: Entity > for Entity { fn to () -> RelationDef { Relation :: UserLessonProgress . def () } }

impl ActiveModelBehavior for ActiveModel { }