//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "LlmModel")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_name = "releaseDate")]
    pub release_date: Option<DateTime>,
    #[sea_orm(column_name = "creatorName", column_type = "Text")]
    pub creator_name: String,
    #[sea_orm(column_name = "creatorSlug", column_type = "Text")]
    pub creator_slug: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub evaluations: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub pricing: Option<Json>,
    #[sea_orm(
        column_name = "medianOutputTokensPerSecond",
        column_type = "Double",
        nullable
    )]
    pub median_output_tokens_per_second: Option<f64>,
    #[sea_orm(
        column_name = "medianTimeToFirstTokenSeconds",
        column_type = "Double",
        nullable
    )]
    pub median_time_to_first_token_seconds: Option<f64>,
    #[sea_orm(
        column_name = "medianTimeToFirstAnswerToken",
        column_type = "Double",
        nullable
    )]
    pub median_time_to_first_answer_token: Option<f64>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bit::Entity")]
    Bit,
}

impl Related<super::bit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bit.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
