//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "RegressionSuite")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "appId" , column_type = "Text")] pub app_id : String , # [sea_orm (column_name = "boardId" , column_type = "Text")] pub board_id : String , # [sea_orm (column_name = "eventId" , column_type = "Text" , nullable)] pub event_id : Option < String > , # [sea_orm (column_name = "nodeId" , column_type = "Text")] pub node_id : String , # [sea_orm (column_name = "triggerOnPublish")] pub trigger_on_publish : bool , # [sea_orm (column_type = "Text" , nullable)] pub schedule : Option < String > , # [sea_orm (column_name = "gateMode" , column_type = "Text")] pub gate_mode : String , # [sea_orm (column_name = "allowLiveSideEffects")] pub allow_live_side_effects : bool , # [sea_orm (column_name = "nextRunAt")] pub next_run_at : Option < DateTime > , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "updatedAt")] pub updated_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::app::Entity" , from = "Column::AppId" , to = "super::app::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] App , }

impl Related < super :: app :: Entity > for Entity { fn to () -> RelationDef { Relation :: App . def () } }

impl ActiveModelBehavior for ActiveModel { }