//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "SwimlaneItem")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "swimlaneId", column_type = "Text")]
    pub swimlane_id: String,
    pub order: i64,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub content: Option<Json>,
    #[sea_orm(column_name = "bitId", column_type = "Text", nullable)]
    pub bit_id: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "bit_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub bit: BelongsTo<Option<super::bit::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "swimlane_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub swimlane: BelongsTo<super::swimlane::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
