//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetryFlowpilotDaily")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(unique)]
    pub day: DateTime,
    #[sea_orm(column_name = "runsStarted")]
    pub runs_started: i64,
    #[sea_orm(column_name = "runsSucceeded")]
    pub runs_succeeded: i64,
    #[sea_orm(column_name = "runsFailed")]
    pub runs_failed: i64,
    #[sea_orm(column_name = "runsCancelled")]
    pub runs_cancelled: i64,
    #[sea_orm(column_name = "plansAssessed")]
    pub plans_assessed: i64,
    #[sea_orm(column_name = "plansFeasible")]
    pub plans_feasible: i64,
    #[sea_orm(column_name = "plansInfeasible")]
    pub plans_infeasible: i64,
    #[sea_orm(column_name = "attemptsTotal")]
    pub attempts_total: i64,
    #[sea_orm(column_name = "attemptsParseValid")]
    pub attempts_parse_valid: i64,
    #[sea_orm(column_name = "attemptsTypedValid")]
    pub attempts_typed_valid: i64,
    #[sea_orm(column_name = "attemptsReconcileValid")]
    pub attempts_reconcile_valid: i64,
    #[sea_orm(column_name = "attemptsApplied")]
    pub attempts_applied: i64,
    #[sea_orm(column_name = "queuedReviews")]
    pub queued_reviews: i64,
    #[sea_orm(column_name = "applyDispositions")]
    pub apply_dispositions: i64,
    #[sea_orm(column_name = "dismissedDispositions")]
    pub dismissed_dispositions: i64,
    #[sea_orm(column_name = "staleDispositions")]
    pub stale_dispositions: i64,
    #[sea_orm(column_name = "errorDispositions")]
    pub error_dispositions: i64,
    #[sea_orm(column_name = "diagnosticOccurrences")]
    pub diagnostic_occurrences: i64,
    #[sea_orm(column_name = "repeatedDiagnosticOccurrences")]
    pub repeated_diagnostic_occurrences: i64,
    #[sea_orm(column_name = "validationRegressions")]
    pub validation_regressions: i64,
    #[sea_orm(column_name = "boardsInspected")]
    pub boards_inspected: i64,
    #[sea_orm(column_name = "emptyBoardsAfterRun")]
    pub empty_boards_after_run: i64,
    pub installs: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
