//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetryPerfDaily")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub day: DateTime,
    #[sea_orm(column_type = "Text")]
    pub metric: String,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    pub count: i32,
    #[sea_orm(column_type = "Double")]
    pub p50: f64,
    #[sea_orm(column_type = "Double")]
    pub p75: f64,
    #[sea_orm(column_type = "Double")]
    pub p95: f64,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
