//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetrySessionDaily")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub day: DateTime,
    #[sea_orm(column_type = "Text")]
    pub release: String,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    pub sessions: i32,
    #[sea_orm(column_name = "crashedSessions")]
    pub crashed_sessions: i32,
    #[sea_orm(column_name = "erroredSessions")]
    pub errored_sessions: i32,
    pub installs: i32,
    #[sea_orm(column_name = "crashedInstalls")]
    pub crashed_installs: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
