//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "TelemetryEvent")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_type = "Text")] pub name : String , # [sea_orm (column_type = "Text")] pub source : String , # [sea_orm (column_name = "anonId" , column_type = "Text")] pub anon_id : String , # [sea_orm (column_type = "JsonBinary" , nullable)] pub props : Option < Json > , # [sea_orm (column_name = "appVersion" , column_type = "Text" , nullable)] pub app_version : Option < String > , # [sea_orm (column_type = "Text" , nullable)] pub platform : Option < String > , # [sea_orm (column_type = "Text" , nullable)] pub country : Option < String > , # [sea_orm (column_name = "clientTs")] pub client_ts : Option < DateTime > , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }