//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "TelemetryEventDaily")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , pub day : DateTime , # [sea_orm (column_type = "Text")] pub name : String , # [sea_orm (column_type = "Text")] pub source : String , pub count : i32 , pub installs : i32 , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "updatedAt")] pub updated_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }