//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "TelemetryRelease")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_type = "Text")] pub version : String , # [sea_orm (column_type = "Text")] pub source : String , # [sea_orm (column_name = "commitSha" , column_type = "Text" , nullable)] pub commit_sha : Option < String > , # [sea_orm (column_name = "firstSeenAt")] pub first_seen_at : DateTime , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }