//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "TelemetrySession")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "anonId" , column_type = "Text")] pub anon_id : String , # [sea_orm (column_type = "Text")] pub source : String , # [sea_orm (column_type = "Text" , nullable)] pub release : Option < String > , # [sea_orm (column_type = "Text" , nullable)] pub platform : Option < String > , # [sea_orm (column_type = "Text")] pub status : String , # [sea_orm (column_name = "startedAt")] pub started_at : DateTime , # [sea_orm (column_name = "durationMs")] pub duration_ms : Option < i32 > , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "updatedAt")] pub updated_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }