//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ; use super :: sea_orm_active_enums :: BitType ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "UserBit")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "userId" , column_type = "Text")] pub user_id : String , pub r#type : BitType , # [sea_orm (column_type = "Text" , nullable)] pub repository : Option < String > , # [sea_orm (column_name = "downloadLink" , column_type = "Text" , nullable)] pub download_link : Option < String > , # [sea_orm (column_name = "fileName" , column_type = "Text" , nullable)] pub file_name : Option < String > , # [sea_orm (column_type = "Text" , nullable)] pub hash : Option < String > , pub size : Option < i64 > , # [sea_orm (column_type = "JsonBinary" , nullable)] pub parameters : Option < Json > , # [sea_orm (column_name = "secretsEncrypted" , column_type = "Text" , nullable)] pub secrets_encrypted : Option < String > , # [sea_orm (column_type = "JsonBinary" , nullable)] pub meta : Option < Json > , # [sea_orm (column_type = "Text" , nullable)] pub version : Option < String > , # [sea_orm (column_type = "Text" , nullable)] pub license : Option < String > , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "updatedAt")] pub updated_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::user::Entity" , from = "Column::UserId" , to = "super::user::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] User , }

impl Related < super :: user :: Entity > for Entity { fn to () -> RelationDef { Relation :: User . def () } }

impl ActiveModelBehavior for ActiveModel { }