//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ; use super :: sea_orm_active_enums :: LessonStatus ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "UserLessonProgress")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "userId" , column_type = "Text")] pub user_id : String , # [sea_orm (column_name = "lessonId" , column_type = "Text")] pub lesson_id : String , pub status : LessonStatus , # [sea_orm (column_name = "completedAt")] pub completed_at : Option < DateTime > , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "updatedAt")] pub updated_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::lesson::Entity" , from = "Column::LessonId" , to = "super::lesson::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] Lesson , }

impl Related < super :: lesson :: Entity > for Entity { fn to () -> RelationDef { Relation :: Lesson . def () } }

impl ActiveModelBehavior for ActiveModel { }