//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ; use super :: sea_orm_active_enums :: PurchaseStatus ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "WasmPackagePurchase")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "userId" , column_type = "Text")] pub user_id : String , # [sea_orm (column_name = "packageId" , column_type = "Text")] pub package_id : String , # [sea_orm (column_name = "pricePaid")] pub price_paid : i64 , # [sea_orm (column_name = "originalPrice")] pub original_price : i64 , # [sea_orm (column_name = "discountAmount")] pub discount_amount : i64 , # [sea_orm (column_type = "Text")] pub currency : String , # [sea_orm (column_name = "stripeSessionId" , column_type = "Text")] pub stripe_session_id : String , # [sea_orm (column_name = "stripePaymentIntentId" , column_type = "Text" , nullable)] pub stripe_payment_intent_id : Option < String > , pub status : PurchaseStatus , # [sea_orm (column_name = "completedAt")] pub completed_at : Option < DateTime > , # [sea_orm (column_name = "refundedAt")] pub refunded_at : Option < DateTime > , # [sea_orm (column_name = "refundReason" , column_type = "Text" , nullable)] pub refund_reason : Option < String > , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "updatedAt")] pub updated_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::user::Entity" , from = "Column::UserId" , to = "super::user::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] User , # [sea_orm (belongs_to = "super::wasm_package::Entity" , from = "Column::PackageId" , to = "super::wasm_package::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] WasmPackage , }

impl Related < super :: user :: Entity > for Entity { fn to () -> RelationDef { Relation :: User . def () } }

impl Related < super :: wasm_package :: Entity > for Entity { fn to () -> RelationDef { Relation :: WasmPackage . def () } }

impl ActiveModelBehavior for ActiveModel { }