//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ; use super :: sea_orm_active_enums :: InvitationStatus ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "WasmPackageInvitation")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "packageId" , column_type = "Text")] pub package_id : String , # [sea_orm (column_name = "invitedById" , column_type = "Text")] pub invited_by_id : String , # [sea_orm (column_name = "inviteeId" , column_type = "Text")] pub invitee_id : String , pub permission : i64 , pub status : InvitationStatus , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , # [sea_orm (column_name = "expiresAt")] pub expires_at : Option < DateTime > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::user::Entity" , from = "Column::InvitedById" , to = "super::user::Column::Id" , on_update = "Cascade" , on_delete = "Restrict" ,)] User2 , # [sea_orm (belongs_to = "super::user::Entity" , from = "Column::InviteeId" , to = "super::user::Column::Id" , on_update = "Cascade" , on_delete = "Restrict" ,)] User1 , # [sea_orm (belongs_to = "super::wasm_package::Entity" , from = "Column::PackageId" , to = "super::wasm_package::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] WasmPackage , }

impl Related < super :: wasm_package :: Entity > for Entity { fn to () -> RelationDef { Relation :: WasmPackage . def () } }

impl ActiveModelBehavior for ActiveModel { }