//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (schema_name = "public" , table_name = "WeeklyChallenge")] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_name = "weekIso" , column_type = "Text" , unique)] pub week_iso : String , # [sea_orm (column_name = "challengeId" , column_type = "Text")] pub challenge_id : String , # [sea_orm (column_name = "expiresAt")] pub expires_at : DateTime , # [sea_orm (column_name = "createdAt")] pub created_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::challenge::Entity" , from = "Column::ChallengeId" , to = "super::challenge::Column::Id" , on_update = "Cascade" , on_delete = "Cascade" ,)] Challenge , }

impl Related < super :: challenge :: Entity > for Entity { fn to () -> RelationDef { Relation :: Challenge . def () } }

impl ActiveModelBehavior for ActiveModel { }