CREATE INDEX ASYNC "AuditEntry_entryHash_idx" ON "AuditEntry"("entryHash");
CREATE INDEX ASYNC "AuditEntry_timestamp_idx" ON "AuditEntry"("timestamp");
CREATE INDEX ASYNC "ExecutionRun_boardId_createdAt_idx" ON "ExecutionRun"("boardId", "createdAt");
DROP INDEX "ExecutionRun_boardId_idx";
CREATE INDEX ASYNC "ExecutionRun_eventId_createdAt_id_idx" ON "ExecutionRun"("eventId", "createdAt", id);
CREATE INDEX ASYNC "ExecutionRun_status_idx" ON "ExecutionRun"(status);
CREATE INDEX ASYNC "ExecutionEvent_runId_sequence_idx" ON "ExecutionEvent"("runId", sequence);
DROP INDEX "ExecutionEvent_runId_delivered_sequence_idx";
CREATE INDEX ASYNC "LeaderboardOptIn_isOptedIn_totalPoints_userId_idx" ON "LeaderboardOptIn"("isOptedIn", "totalPoints", "userId");
CREATE INDEX ASYNC "Certificate_hash_idx" ON "Certificate"(hash);
CREATE INDEX ASYNC "WasmPackage_updatedAt_idx" ON "WasmPackage"("updatedAt");
CREATE INDEX ASYNC "TelemetryErrorEvent_issueId_anonId_idx" ON "TelemetryErrorEvent"("issueId", "anonId");
CREATE INDEX ASYNC "TelemetrySession_createdAt_idx" ON "TelemetrySession"("createdAt");
CREATE INDEX ASYNC "Comment_appId_createdAt_idx" ON "Comment"("appId", "createdAt");
DROP INDEX "Comment_appId_idx";
CREATE INDEX ASYNC "Feedback_appId_createdAt_idx" ON "Feedback"("appId", "createdAt");
DROP INDEX "Feedback_appId_idx";
CREATE INDEX ASYNC "ErrorReport_createdAt_idx" ON "ErrorReport"("createdAt");
CREATE INDEX ASYNC "User_createdAt_idx" ON "User"("createdAt");
