use utoipa::{
    Modify, OpenApi,
    openapi::security::{
        ApiKey, ApiKeyValue, AuthorizationCode, Flow, Http, HttpAuthScheme, OAuth2, Scopes,
        SecurityScheme,
    },
};

/// Security scheme modifier to add authentication methods
struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);

        // Bearer token (OAuth2 JWT)
        components.add_security_scheme(
            "bearer_auth",
            SecurityScheme::Http(Http::new(HttpAuthScheme::Bearer)),
        );

        // API Key for technical users (X-API-Key header)
        components.add_security_scheme(
            "api_key",
            SecurityScheme::ApiKey(ApiKey::Header(ApiKeyValue::new("X-API-Key"))),
        );

        // Personal Access Token (Authorization: PAT <token>)
        components.add_security_scheme(
            "pat",
            SecurityScheme::ApiKey(ApiKey::Header(ApiKeyValue::with_description(
                "Authorization",
                "Personal Access Token. Format: 'PAT <token>'",
            ))),
        );

        // OAuth2 Authorization Code flow
        components.add_security_scheme(
            "oauth2",
            SecurityScheme::OAuth2(OAuth2::new([Flow::AuthorizationCode(
                AuthorizationCode::new(
                    "/api/v1/auth/authorize",
                    "/api/v1/auth/token",
                    Scopes::from_iter([
                        ("openid", "OpenID Connect scope"),
                        ("profile", "User profile information"),
                        ("email", "User email address"),
                    ]),
                ),
            )])),
        );

        // Executor JWT (for backend execution services)
        components.add_security_scheme(
            "executor_jwt",
            SecurityScheme::Http(
                Http::builder()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .description(Some("JWT token for execution services"))
                    .build(),
            ),
        );
    }
}

#[derive(OpenApi)]
#[openapi(
    modifiers(&SecurityAddon),
    info(
        title = "Flow-Like API",
        version = "1.0.0",
        description = "Flow-Like platform API for building and executing workflows.\n\n## Authentication\n\nThis API supports multiple authentication methods:\n\n- **Bearer Token (OAuth2)**: Standard JWT token from OAuth2 flow. Use `Authorization: Bearer <token>`\n- **API Key**: For technical/service users. Use `X-API-Key: <key>` header\n- **Personal Access Token (PAT)**: For programmatic access. Use `Authorization: PAT <token>`\n- **Executor JWT**: Internal JWT for execution services",
        license(name = "MIT")
    ),
    servers(
        (url = "/api/v1", description = "API v1")
    ),
    tags(
        (name = "health", description = "Health check endpoints"),
        (name = "auth", description = "Authentication and authorization"),
        (name = "oauth", description = "OAuth provider integration"),
        (name = "user", description = "User management and preferences"),
        (name = "profile", description = "User profiles"),
        (name = "apps", description = "Application management"),
        (name = "boards", description = "Board/workflow management"),
        (name = "pages", description = "Page management"),
        (name = "routes", description = "Route mapping management"),
        (name = "execution", description = "Workflow execution"),
        (name = "events", description = "Event management"),
        (name = "widgets", description = "Widget management"),
        (name = "templates", description = "Template management"),
        (name = "meta", description = "Metadata management"),
        (name = "roles", description = "Role management"),
        (name = "packages", description = "App package management"),
        (name = "team", description = "Team management"),
        (name = "analytics", description = "Analytics and usage metrics"),
        (name = "sales", description = "Sales and pricing"),
        (name = "api-keys", description = "API key management"),
        (name = "comments", description = "App review comments"),
        (name = "notifications", description = "App notifications"),
        (name = "registry", description = "Package registry"),
        (name = "bit", description = "Bit (component) management"),
        (name = "sink", description = "Event sink management"),
        (name = "chat", description = "LLM chat completions"),
        (name = "database", description = "Database operations"),
        (name = "graph", description = "Graph overlay and visualization operations"),
        (name = "data", description = "Data file access"),
        (name = "store", description = "Data store"),
        (name = "solution", description = "Solution requests"),
        (name = "admin", description = "Admin operations"),
        (name = "tmp", description = "Temporary file operations"),
        (name = "courses", description = "Flow-Like University: courses, lessons, challenges, leaderboard"),
        (name = "ai-act", description = "EU AI Act conformity assessment and model governance")
    ),
    paths(
        // Health routes
        crate::routes::health::health,
        crate::routes::health::db_health,
        // OG metadata
        crate::routes::og::fetch_og_metadata,
        // Auth routes
        crate::routes::auth::openid_config,
        crate::routes::auth::discovery,
        crate::routes::auth::jwks,
        // OAuth routes
        crate::routes::oauth::token_exchange,
        crate::routes::oauth::token_refresh,
        // User routes
        crate::routes::user::info::user_info,
        crate::routes::user::upsert_info::upsert_info,
        crate::routes::user::pricing::get_pricing,
        crate::routes::user::subscribe::create_subscription_checkout,
        crate::routes::user::lookup::user_lookup,
        crate::routes::user::lookup::user_batch_lookup,
        crate::routes::user::lookup::user_search,
        crate::routes::user::billing::get_billing_session,
        crate::routes::user::notifications::get_notifications,
        crate::routes::user::notifications::list_notifications,
        crate::routes::user::notifications::mark_notification_read,
        crate::routes::user::notifications::mark_all_read,
        crate::routes::user::notifications::delete_notification,
        crate::routes::user::push_targets::register_push_target,
        crate::routes::user::push_targets::get_push_target_status,
        crate::routes::user::push_targets::update_push_target_status,
        crate::routes::user::push_targets::unregister_push_target,
        crate::routes::user::get_invites::get_invites,
        crate::routes::user::manage_invite::accept_invite,
        crate::routes::user::manage_invite::reject_invite,
        crate::routes::user::templates::get_templates,
        crate::routes::user::widgets::get_widgets,
        crate::routes::user::pat::get_pats::get_pats,
        crate::routes::user::pat::create_pat::create_pat,
        crate::routes::user::pat::delete_pat::delete_pat,
        // Profile routes
        crate::routes::profile::get_profiles::get_profiles,
        crate::routes::profile::upsert_profile::upsert_profile,
        crate::routes::profile::delete_profile::delete_profile,
        crate::routes::profile::sync_profiles::sync_profiles,
        crate::routes::profile::get_profile_bits::get_profile_bits,
        // App routes
        crate::routes::app::internal::get_app::get_app,
        crate::routes::app::internal::get_apps::get_apps,
        crate::routes::app::internal::search_apps::search_apps,
        crate::routes::app::internal::upsert_app::upsert_app,
        crate::routes::app::internal::delete_app::delete_app,
        crate::routes::app::internal::change_visibility::change_visibility,
        crate::routes::app::internal::change_forking::change_forking,
        crate::routes::app::fork::preview::get_fork_preview,
        crate::routes::app::fork::begin_offline::begin_offline_fork,
        crate::routes::app::fork::begin_online::begin_online_fork,
        crate::routes::app::fork::finalize_online::finalize_online_fork,
        crate::routes::app::fork::online_fork::online_fork,
        crate::routes::admin::forks::list_orphan_forks,
        crate::routes::admin::forks::delete_orphan_fork,
        crate::routes::admin::governance::list_scores::list_scores,
        crate::routes::admin::governance::get_scores_summary::get_scores_summary,
        crate::routes::admin::governance::get_app_scores::get_app_scores,
        crate::routes::admin::governance::list_patterns::list_patterns,
        crate::routes::admin::governance::recompute::recompute_scores,
        crate::routes::app::publication::get_publication::get_publication_requests,
        crate::routes::app::publication::upsert_publication::request_publication,
        crate::routes::admin::publication::get_requests::get_requests,
        crate::routes::admin::publication::upsert_requests::upsert_request,
        crate::routes::admin::publication::get_app_content::get_app_content,
        crate::routes::admin::publication::get_board::get_board,
        crate::routes::admin::publication::get_page::get_page,
        // EU AI Act routes
        crate::routes::app::ai_act::get_questionnaire,
        crate::routes::app::ai_act::classify_preview,
        crate::routes::app::ai_act::get_assessment,
        crate::routes::app::ai_act::put_assessment,
        crate::routes::app::ai_act::suggest_assessment,
        crate::routes::admin::ai_act::list_inventory,
        crate::routes::admin::ai_act::get_inventory_detail,
        crate::routes::admin::ai_act::put_inventory_assessment,
        crate::routes::admin::ai_act::reconcile_models,
        crate::routes::admin::ai_act::acknowledge_model,
        crate::routes::admin::ai_act::list_models,
        crate::routes::admin::ai_act::upsert_model,
        crate::routes::admin::ai_act::assist,
        crate::routes::admin::ai_act::export_inventory,
        crate::routes::app::internal::get_nodes::get_nodes,
        // Board routes
        crate::routes::app::board::get_board::get_board,
        crate::routes::app::board::get_boards::get_boards,
        crate::routes::app::board::get_board_versions::get_board_versions,
        crate::routes::app::board::upsert_board::upsert_board,
        crate::routes::app::board::delete_board::delete_board,
        crate::routes::app::board::version_board::version_board,
        crate::routes::app::board::execute_commands::execute_commands,
        crate::routes::app::board::undo_redo_board::undo_board,
        crate::routes::app::board::undo_redo_board::redo_board,
        crate::routes::app::board::invoke_board::invoke_board,
        crate::routes::app::board::invoke_board_async::invoke_board_async,
        crate::routes::app::board::prerun_board::prerun_board,
        crate::routes::app::board::query_logs::query_logs,
        crate::routes::app::board::get_runs::get_runs,
        crate::routes::app::board::get_execution_elements::get_execution_elements,
        // Page routes
        crate::routes::app::page::get_page::get_page,
        crate::routes::app::page::get_pages::get_pages,
        crate::routes::app::page::get_page_by_route::get_page_by_route,
        crate::routes::app::page::upsert_page::upsert_page,
        crate::routes::app::page::delete_page::delete_page,
        // Route mapping routes
        crate::routes::app::route::get_routes::get_routes,
        crate::routes::app::route::get_route_by_path::get_route_by_path,
        crate::routes::app::route::get_default_route::get_default_route,
        crate::routes::app::route::upsert_route::create_route,
        crate::routes::app::route::upsert_route::update_route,
        crate::routes::app::route::delete_route::delete_route,
        // Widget routes
        crate::routes::app::widget::get_widgets::get_widgets,
        crate::routes::app::widget::get_widget::get_widget,
        crate::routes::app::widget::upsert_widget::upsert_widget,
        crate::routes::app::widget::delete_widget::delete_widget,
        // Template routes
        crate::routes::app::template::get_templates::get_templates,
        crate::routes::app::template::get_template::get_template,
        crate::routes::app::template::upsert_template::upsert_template,
        crate::routes::app::template::delete_template::delete_template,
        // Meta routes
        crate::routes::app::meta::get_meta::get_meta,
        crate::routes::app::meta::upsert_meta::upsert_meta,
        crate::routes::app::meta::push_media::push_media,
        crate::routes::app::meta::remove_media::remove_media,
        // Role routes
        crate::routes::app::roles::get_roles::get_roles,
        crate::routes::app::roles::upsert_role::upsert_role,
        crate::routes::app::roles::delete_role::delete_role,
        crate::routes::app::roles::make_role_default::make_role_default,
        crate::routes::app::roles::assign_role::assign_role,
        // Team routes
        crate::routes::app::team::get_team::get_team,
        crate::routes::app::team::create_invite_link::create_invite_link,
        crate::routes::app::team::get_invite_links::get_invite_links,
        crate::routes::app::team::remove_invite_link::remove_invite_link,
        crate::routes::app::team::join_invite_link::join_invite_link,
        crate::routes::app::team::get_join_requests::get_join_requests,
        crate::routes::app::team::request_join::request_join,
        crate::routes::app::team::manage_join_request::accept_join_request,
        crate::routes::app::team::manage_join_request::reject_join_request,
        crate::routes::app::team::invite_user::invite_user,
        crate::routes::app::team::purchase::purchase,
        crate::routes::app::team::remove_user::remove_user,
        // App connection routes (app-to-app access)
        crate::routes::app::connection::get_connections::get_connections,
        crate::routes::app::connection::add_connection::add_connection,
        crate::routes::app::connection::request_connection::request_connection,
        crate::routes::app::connection::manage_connection::accept_connection_request,
        crate::routes::app::connection::manage_connection::reject_connection_request,
        crate::routes::app::connection::update_connection::update_connection,
        crate::routes::app::connection::remove_connection::remove_connection,
        crate::routes::app::connection::get_accessible::get_accessible_apps,
        crate::routes::app::connection::remote_tables::get_remote_tables,
        crate::routes::app::connection::remote_events::get_remote_events,
        crate::routes::app::connection::remote_events::get_remote_event_detail,
        crate::routes::app::connection::token::create_app_connection_token,
        crate::routes::app::connection::graph::get_connection_graph,
        crate::routes::app::connection::notes::list_notes,
        crate::routes::app::connection::notes::create_note,
        crate::routes::app::connection::notes::update_note,
        crate::routes::app::connection::notes::delete_note,
        crate::routes::admin::connections::get_global_connection_graph,
        // API key routes
        crate::routes::app::api::get_api_keys::get_api_keys,
        crate::routes::app::api::create_api_key::create_api_key,
        crate::routes::app::api::delete_api_key::delete_api_key,
        // Analytics routes
        crate::routes::app::analytics::overview::get_analytics_overview,
        crate::routes::app::analytics::overview::get_analytics_stats,
        crate::routes::app::analytics::feedback::list_feedback,
        // Sales routes
        crate::routes::app::sales::overview::get_sales_overview,
        crate::routes::app::sales::overview::get_sales_stats,
        crate::routes::app::sales::purchases::list_purchases,
        crate::routes::app::sales::price::update_price,
        crate::routes::app::sales::discounts::list_discounts,
        crate::routes::app::sales::discounts::create_discount,
        crate::routes::app::sales::discounts::get_discount,
        crate::routes::app::sales::discounts::update_discount,
        crate::routes::app::sales::discounts::delete_discount,
        crate::routes::app::sales::discounts::toggle_discount,
        // Event routes
        crate::routes::app::events::get_events::get_events,
        crate::routes::app::events::get_event::get_event,
        crate::routes::app::events::upsert_event::upsert_event,
        crate::routes::app::events::delete_event::delete_event,
        crate::routes::app::events::get_event_versions::get_event_versions,
        crate::routes::app::events::validate_event::validate_event,
        crate::routes::app::events::setup_event::setup_event,
        crate::routes::app::events::prerun_event::prerun_event,
        crate::routes::app::events::invoke_event::invoke_event,
        crate::routes::app::events::invoke_event_async::invoke_event_async,
        crate::routes::app::events::registrations::list_registrations,
        crate::routes::app::events::alias::list_aliases,
        crate::routes::app::events::alias::get_alias,
        crate::routes::app::events::alias::upsert_alias,
        crate::routes::app::events::alias::delete_alias,
        crate::routes::app::events::upsert_event_feedback::upsert_event_feedback,
        crate::routes::alias::lookup_alias,
        // Comment routes
        crate::routes::app::comments::get_comments::get_comments,
        crate::routes::app::comments::upsert_comment::upsert_comment,
        crate::routes::app::comments::remove_comment::remove_comment,
        // Notifications routes
        crate::routes::app::notifications::create_notification,
        // Data routes
        crate::routes::app::data::upload_files::upload_files,
        crate::routes::app::data::upload_files::upload_user_files,
        crate::routes::app::data::download_files::download_files,
        crate::routes::app::data::download_files::download_user_files,
        crate::routes::app::data::list_files::list_files,
        crate::routes::app::data::list_files::list_user_files,
        crate::routes::app::data::delete_files::delete_files,
        crate::routes::app::data::delete_files::delete_user_files,
        crate::routes::app::data::presign_data_access::presign_data_access,
        crate::routes::app::data::presign_data_access::presign_user_data_access,
        // Realtime board routes
        crate::routes::app::board::realtime::jwks,
        crate::routes::app::board::realtime::access,
        // Invoke presign
        crate::routes::app::invoke::presign::presign,
        // Database routes
        crate::routes::app::db::list_tables::list_tables,
        crate::routes::app::db::db_list::list_items,
        crate::routes::app::db::db_add::add_to_table,
        crate::routes::app::db::db_delete::delete_from_table,
        crate::routes::app::db::db_update::update_table,
        crate::routes::app::db::db_query::query_table,
        crate::routes::app::db::db_count::db_count,
        crate::routes::app::db::get_db_schema::get_db_schema,
        crate::routes::app::db::get_indices::get_db_indices,
        crate::routes::app::db::add_column::add_column,
        crate::routes::app::db::alter_column::alter_column,
        crate::routes::app::db::drop_columns::drop_columns,
        crate::routes::app::db::build_index::build_index,
        crate::routes::app::db::drop_index::drop_index,
        crate::routes::app::db::optimize::optimize_table,
        crate::routes::app::db::presign_db_access::presign_db_access,
        crate::routes::app::db::presign_db_access::presign_project_db_access,
        crate::routes::app::graph::search::search_nodes,
        // App package routes
        crate::routes::app::packages::list_packages,
        crate::routes::app::packages::add_package,
        crate::routes::app::packages::remove_package,
        crate::routes::app::packages::update_package,
        crate::routes::app::packages::get_patch_info,
        crate::routes::app::packages::check_updates,
        // Execution routes
        crate::routes::execution::progress::report_progress,
        crate::routes::execution::progress::push_events,
        crate::routes::execution::progress::poll_status,
        crate::routes::execution::progress::get_run_status,
        crate::routes::execution::public_key::get_execution_jwks,
        // Registry routes
        crate::routes::registry::publish::publish,
        crate::routes::registry::search::search,
        crate::routes::registry::download::download,
        // Bit routes
        crate::routes::bit::get_bit::get_bit,
        crate::routes::bit::get_with_dependencies::get_with_dependencies,
        crate::routes::bit::search_bits::search_bits,
        // Sink routes
        crate::routes::sink::trigger::trigger_http,
        crate::routes::sink::trigger::trigger_telegram,
        crate::routes::sink::trigger::trigger_discord,
        crate::routes::sink::trigger::trigger_service,
        crate::routes::sink::trigger::get_cron_sinks,
        crate::routes::sink::trigger::get_sink_configs,
        crate::routes::sink::management::list_sinks,
        crate::routes::sink::management::list_app_sinks,
        crate::routes::sink::management::get_sink,
        crate::routes::sink::management::update_sink,
        crate::routes::sink::management::toggle_sink,
        // Chat routes
        crate::routes::chat::completions::invoke_llm,
        crate::routes::chat::usage::get_llm_usage,
        // Store routes
        crate::routes::store::get_store_db,
        // Solution routes
        crate::routes::solution::get_upload_url,
        crate::routes::solution::submit_solution,
        crate::routes::solution::track_solution,
        // Tmp routes
        crate::routes::tmp::get_temporary_upload,
        // Admin routes
        crate::routes::admin::solutions::list_solutions::list_solutions,
        crate::routes::admin::packages::get_stats::get_stats,
        crate::routes::admin::packages::ensure_wasm_artifacts::ensure_wasm_artifacts,
        crate::routes::admin::packages::get_packages::get_packages,
        crate::routes::admin::packages::get_package::get_package,
        crate::routes::admin::packages::delete_package::delete_package,
        crate::routes::admin::packages::review_package::review_package,
        crate::routes::admin::packages::update_package::update_package,
        crate::routes::registry::metadata::get_publication_reviews,
        crate::routes::admin::bit::delete_bit::delete_bit,
        crate::routes::admin::sinks::list_tokens::list_tokens,
        crate::routes::admin::profiles::delete_profile_template::delete_profile_template,
        crate::routes::admin::runs::sweep_runs,
        // Course routes (University)
        crate::routes::course::courses::list_courses,
        crate::routes::course::courses::get_course,
        crate::routes::course::courses::get_course_structure,
        crate::routes::course::courses::upsert_course,
        crate::routes::course::courses::push_course_media,
        crate::routes::course::courses::delete_course,
        crate::routes::course::assets::list_course_assets,
        crate::routes::course::assets::create_course_asset,
        crate::routes::course::assets::update_course_asset,
        crate::routes::course::assets::delete_course_asset,
        crate::routes::course::assets::optimize_course_asset,
        crate::routes::course::modules::upsert_module,
        crate::routes::course::modules::delete_module,
        crate::routes::course::lessons::get_lesson,
        crate::routes::course::lessons::upsert_lesson,
        crate::routes::course::lessons::delete_lesson,
        crate::routes::course::challenges::upsert_challenge,
        crate::routes::course::challenges::delete_challenge,
        crate::routes::course::app_links::list_app_links,
        crate::routes::course::app_links::upsert_app_link,
        crate::routes::course::app_links::delete_app_link,
        crate::routes::course::app_refs::upsert_app_ref,
        crate::routes::course::app_refs::delete_app_ref,
        crate::routes::course::shared_app::open_shared_app,
        crate::routes::course::translate::translate,
        crate::routes::course::enrollment::enroll,
        crate::routes::course::enrollment::get_my_enrollments,
        crate::routes::course::progress::mark_lesson_complete,
        crate::routes::course::progress::get_my_course_progress,
        crate::routes::course::attempts::submit_attempt,
        crate::routes::course::certificates::issue_certificate,
        crate::routes::course::certificates::list_my_certificates,
        crate::routes::course::certificates::verify_certificate,
        crate::routes::course::paths::list_learning_paths,
        crate::routes::course::paths::get_learning_path,
        crate::routes::course::paths::upsert_learning_path,
        crate::routes::course::paths::delete_learning_path,
        crate::routes::course::paths::upsert_learning_path_step,
        crate::routes::course::paths::delete_learning_path_step,
        crate::routes::course::leaderboard::get_leaderboard,
        crate::routes::course::leaderboard::get_my_opt_in,
        crate::routes::course::leaderboard::update_my_opt_in,
        crate::routes::course::weekly::get_current_weekly,
        crate::routes::course::weekly::rotate_weekly,
    ),
    components(schemas(
        // Health schemas
        crate::routes::health::HealthResponse,
        crate::routes::health::DbHealthResponse,
        // OAuth schemas
        crate::routes::oauth::TokenExchangeRequest,
        crate::routes::oauth::TokenRefreshRequest,
        crate::routes::oauth::TokenResponse,
        crate::routes::oauth::ErrorResponse,
        // Database schemas
        crate::routes::app::db::add_column::AddColumnPayload,
        crate::routes::app::db::alter_column::AlterColumnPayload,
        crate::routes::app::db::build_index::BuildIndexPayload,
        crate::routes::app::db::build_index::IndexType,
        crate::routes::app::db::db_delete::DeleteFromDBPayload,
        crate::routes::app::db::db_query::QueryTablePayload,
        crate::routes::app::db::db_query::VectorQueryPayload,
        crate::routes::app::db::drop_columns::DropColumnsPayload,
        crate::routes::app::db::get_indices::IndexConfigResponse,
        crate::routes::app::db::optimize::OptimizePayload,
        crate::routes::app::db::presign_db_access::PresignDbAccessRequest,
        crate::routes::app::db::presign_db_access::PresignDbAccessResponse,
        // App connection schemas
        crate::routes::app::connection::AppConnectionInfo,
        crate::routes::app::connection::get_connections::AppConnectionsResponse,
        crate::routes::app::connection::add_connection::AddConnectionRequest,
        crate::routes::app::connection::request_connection::RequestConnectionRequest,
        crate::routes::app::connection::manage_connection::AcceptConnectionRequest,
        crate::routes::app::connection::update_connection::UpdateConnectionRequest,
        crate::routes::app::connection::get_accessible::AccessibleApp,
        crate::routes::app::connection::token::CreateAppConnectionTokenRequest,
        crate::routes::app::connection::token::CreateAppConnectionTokenResponse,
        crate::routes::app::connection::graph::ProcessGraphResponse,
        crate::routes::app::connection::graph::ProcessGraphNode,
        crate::routes::app::connection::graph::ProcessGraphEdge,
        crate::routes::app::connection::graph::ProcessFlow,
        crate::routes::app::connection::graph::AppContentStats,
        crate::routes::app::connection::graph::ProcessNoteInfo,
        crate::routes::app::connection::notes::UpsertProcessNoteRequest,
        crate::routes::app::connection::remote_events::RemoteEvent,
        crate::routes::app::connection::remote_events::RemoteEventDetail,
        crate::routes::app::connection::remote_events::RemoteRestRoute,
        crate::routes::app::connection::remote_events::RemoteRestFile,
        crate::routes::app::connection::remote_events::RemoteMcpTool,
        crate::routes::app::connection::remote_events::RemoteMcpResource,
        crate::routes::app::data::presign_data_access::PresignDataAccessRequest,
        crate::routes::app::data::presign_data_access::PresignDataAccessResponse,
        // App notifications
        crate::routes::app::notifications::CreateNotificationParams,
        crate::routes::app::notifications::CreateNotificationResponse,
        // Admin governance scores
        crate::routes::admin::governance::list_scores::AppScoreItem,
        crate::routes::admin::governance::list_scores::ListAppScoresResponse,
        crate::routes::admin::governance::get_app_scores::BoardScoreItem,
        crate::routes::admin::governance::get_app_scores::AppScoreDetailResponse,
        crate::routes::admin::governance::get_scores_summary::GovernanceScoresSummary,
        crate::routes::admin::governance::get_scores_summary::WorstAppItem,
        crate::routes::admin::governance::list_patterns::PatternItem,
        crate::routes::admin::governance::list_patterns::ListPatternsResponse,
        crate::routes::admin::governance::recompute::RecomputeScoresRequest,
        crate::routes::admin::governance::recompute::RecomputeScoresResponse,
        crate::routes::app::board::scoring::BoardScores,
        crate::routes::app::board::scoring::FlaggedPattern,
        crate::routes::app::publication::get_publication::AppPublicationActor,
        crate::routes::app::publication::get_publication::AppPublicationLogItem,
        crate::routes::app::publication::get_publication::AppPublicationRequestItem,
        crate::routes::app::publication::upsert_publication::RequestPublicationBody,
        crate::routes::app::publication::upsert_publication::RequestPublicationResponse,
        crate::routes::admin::publication::get_requests::ListPublicationRequestsQuery,
        crate::routes::admin::publication::get_requests::ListPublicationRequestsResponse,
        crate::routes::admin::publication::get_requests::PublicationActor,
        crate::routes::admin::publication::get_requests::PublicationLogItem,
        crate::routes::admin::publication::get_requests::PublicationRequestItem,
        crate::routes::admin::publication::upsert_requests::ReviewPublicationBody,
        crate::routes::admin::publication::upsert_requests::ReviewPublicationResponse,
        // EU AI Act
        crate::routes::app::ai_act::QuestionnaireResponse,
        crate::routes::app::ai_act::ClassifyBody,
        crate::routes::app::ai_act::ClassifyResponse,
        crate::routes::app::ai_act::AssessmentResponse,
        crate::routes::app::ai_act::UpsertAssessmentBody,
        crate::routes::app::ai_act::SuggestBody,
        crate::routes::app::ai_act::SuggestResponse,
        crate::routes::admin::ai_act::InventoryItem,
        crate::routes::admin::ai_act::InventoryResponse,
        crate::routes::admin::ai_act::ModelObservationItem,
        crate::routes::admin::ai_act::InventoryDetailResponse,
        crate::routes::admin::ai_act::ReconcileResponse,
        crate::routes::admin::ai_act::RegistryItem,
        crate::routes::admin::ai_act::UpsertModelBody,
        crate::routes::admin::ai_act::AssistBody,
        // Widgets
        crate::routes::app::widget::get_widget::VersionQuery,
        crate::routes::app::widget::upsert_widget::WidgetUpsert,
        // Templates
        crate::routes::app::template::get_template::VersionQuery,
        crate::routes::app::template::upsert_template::TemplateUpsert,
        // Meta
        crate::routes::app::meta::MetaQuery,
        crate::routes::app::meta::MediaQuery,
        crate::routes::app::meta::MediaItem,
        crate::routes::app::meta::push_media::PushMediaResponse,
        // Team
        crate::routes::app::team::create_invite_link::CreateInviteLinkPayload,
        crate::routes::app::team::request_join::RequestJoinParams,
        crate::routes::app::team::invite_user::InviteUserParams,
        crate::routes::app::team::purchase::PurchaseParams,
        crate::routes::app::team::purchase::PurchaseResponse,
        // API keys
        crate::routes::app::api::ApiKeyInfo,
        crate::routes::app::api::ApiKeyInput,
        crate::routes::app::api::ApiKeyOut,
        // Analytics
        crate::routes::app::analytics::overview::AnalyticsStatsQuery,
        crate::routes::app::analytics::overview::AnalyticsOverview,
        crate::routes::app::analytics::overview::DailyAnalyticsStat,
        crate::routes::app::analytics::overview::AnalyticsStats,
        crate::routes::app::analytics::feedback::FeedbackQuery,
        crate::routes::app::analytics::feedback::FeedbackItem,
        crate::routes::app::analytics::feedback::PaginatedFeedback,
        // Sales
        crate::routes::app::sales::overview::StatsQuery,
        crate::routes::app::sales::overview::SalesOverview,
        crate::routes::app::sales::overview::DailyStat,
        crate::routes::app::sales::overview::SalesStats,
        crate::routes::app::sales::price::UpdatePriceRequest,
        crate::routes::app::sales::price::PriceResponse,
        crate::routes::app::sales::discounts::ListDiscountsQuery,
        crate::routes::app::sales::discounts::DiscountResponse,
        crate::routes::app::sales::discounts::CreateDiscountRequest,
        crate::routes::app::sales::discounts::UpdateDiscountRequest,
        crate::routes::app::sales::purchases::PurchasesQuery,
        crate::routes::app::sales::purchases::PurchaseItem,
        crate::routes::app::sales::purchases::PurchasesResponse,
        // Events
        crate::routes::app::events::get_event::VersionQuery,
        crate::routes::app::events::validate_event::VersionQuery,
        crate::routes::app::events::upsert_event::EventUpsertBody,
        crate::routes::app::events::setup_event::SetupEventRequest,
        crate::routes::app::events::setup_event::SetupEventResponse,
        crate::routes::app::events::prerun_event::PrerunEventQuery,
        crate::routes::app::prerun_shared::RuntimeVariable,
        crate::routes::app::prerun_shared::OAuthRequirement,
        crate::routes::app::prerun_shared::PrerunPayload,
        crate::routes::app::events::prerun_event::PrerunEventResponse,
        crate::routes::app::board::prerun_board::PrerunBoardResponse,
        crate::routes::app::board::prerun_board::PrerunBoardQuery,
        crate::routes::app::events::invoke_event::InvokeEventQuery,
        crate::routes::app::events::invoke_event::InvokeEventRequest,
        crate::routes::app::events::invoke_event::InvokeEventResponse,
        crate::routes::app::events::invoke_event_async::InvokeEventAsyncRequest,
        crate::routes::app::events::invoke_event_async::InvokeEventAsyncResponse,
        crate::routes::app::events::registrations::ListRegistrationsQuery,
        crate::routes::app::events::registrations::AuthView,
        crate::routes::app::events::registrations::RegistrationView,
        crate::routes::app::events::registrations::ListRegistrationsResponse,
        crate::routes::app::events::alias::AliasView,
        crate::routes::app::events::alias::UpsertAliasRequest,
        crate::routes::alias::AliasLookupResponse,
        crate::routes::app::events::upsert_event_feedback::FeedbackBody,
        crate::routes::app::events::upsert_event_feedback::FeedbackResponse,
        // Comments
        crate::routes::app::comments::upsert_comment::CommentBody,
        crate::routes::app::comments::upsert_comment::CommentResponse,
        crate::routes::app::comments::get_comments::CommentsQuery,
        crate::routes::app::comments::get_comments::CommentItem,
        crate::routes::app::comments::get_comments::CommentsResponse,
        // App packages
        crate::routes::app::packages::AddPackageRequest,
        crate::routes::app::packages::UpdatePackageRequest,
        crate::routes::app::packages::AppPackageResponse,
        crate::routes::app::packages::PatchInfo,
        crate::routes::app::packages::PackageUpdateInfo,
        // Realtime
        crate::routes::app::board::realtime::RealtimeParams,
        // Data
        crate::routes::app::data::upload_files::UploadFilesPayload,
        crate::routes::app::data::download_files::DownloadFilesPayload,
        crate::routes::app::data::list_files::ListFilesPayload,
        crate::routes::app::data::delete_files::DeleteFilesPayload,
        // University
        crate::routes::user::lookup::UserLookupResponse,
        crate::routes::user::lookup::UserBatchLookupBody,
        crate::routes::course::courses::CourseListItem,
        crate::routes::course::courses::CourseUpsertBody,
        crate::routes::course::courses::CourseDetail,
        crate::routes::course::courses::CourseStructure,
        crate::routes::course::courses::ModuleWithLessons,
        crate::routes::course::courses::LessonSummary,
        crate::routes::course::courses::ListCoursesQuery,
        crate::routes::course::courses::CourseMediaItem,
        crate::routes::course::courses::CourseMediaQuery,
        crate::routes::course::courses::PushCourseMediaResponse,
        crate::routes::course::assets::CourseAssetView,
        crate::routes::course::assets::CourseAssetKind,
        crate::routes::course::assets::CreateCourseAssetBody,
        crate::routes::course::assets::CreateCourseAssetResponse,
        crate::routes::course::assets::UpdateCourseAssetBody,
        crate::routes::course::assets::ListCourseAssetsQuery,
        crate::routes::course::assets::OptimizeCourseAssetResponse,
        crate::routes::course::modules::ModuleUpsertBody,
        crate::routes::course::lessons::LessonUpsertBody,
        crate::routes::course::lessons::LessonWithChildren,
        crate::routes::course::challenges::ChallengeUpsertBody,
        crate::routes::course::challenges::ChallengeView,
        crate::routes::course::app_links::AppLinkUpsertBody,
        crate::routes::course::app_refs::AppRefUpsertBody,
        crate::routes::course::app_refs::AppRefView,
        crate::routes::course::attempts::AttemptSubmission,
        crate::routes::course::attempts::AttemptResult,
        crate::routes::course::attempts::ChallengeAttemptView,
        crate::routes::course::progress::UserLessonProgressView,
        crate::routes::course::certificates::CertificateView,
        crate::routes::course::paths::LearningPathView,
        crate::routes::course::paths::LearningPathStepView,
        crate::routes::course::paths::LearningPathUpsertBody,
        crate::routes::course::paths::LearningPathStepUpsertBody,
        crate::routes::course::leaderboard::LeaderboardEntry,
        crate::routes::course::leaderboard::OptInBody,
        crate::routes::course::weekly::CurrentWeekly,
        crate::routes::course::shared_app::OpenSharedAppResponse,
        crate::routes::course::shared_app::OpenSharedAppQuery,
        crate::routes::course::translate::TranslateQuery,
        crate::routes::course::translate::TranslateResponse,
        crate::utils::fork::ForkIdMap,
    ))
)]
pub struct ApiDoc;
