//! Server-side WASM Package Registry
//!
//! Stores WASM binaries in CDN/content bucket and metadata in PostgreSQL.
//! Custom nodes are public after admin approval.

use crate::entity::{
    meta, user, wasm_package, wasm_package_author, wasm_package_review, wasm_package_user,
    wasm_package_version,
};
use crate::entity::sea_orm_active_enums::{WasmCompilationStatus, WasmPackageVisibility};
use flow_like_storage::files::store::FlowLikeStore;
use flow_like_storage::object_store::PutPayload;
use flow_like_storage::object_store::path::Path;
use flow_like_types::create_id;
use flow_like_wasm::manifest::PackageManifest;
use super::types::{
    MetaSummary, PackageSource, PackageStatus, PackageSummary, PackageVersion, PublishResponse,
    RegistryEntry, RegistryIndex, SearchFilters, SearchResults, SortField,
};
use sea_orm::{
    ActiveModelTrait, ActiveValue::Set, ColumnTrait, DatabaseConnection, EntityTrait,
    PaginatorTrait, QueryFilter, QueryOrder, QuerySelect,
};
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use std::time::Duration;
use utoipa::ToSchema;

/// CDN path prefix for WASM packages
const WASM_PACKAGES_PATH: &str = "wasm";
const WASM_COMPILED_PATH: &str = "wasm-compiled";
const WASMTIME_VERSION: &str = "40";

/// Build a platform key from OS and architecture strings.
fn platform_key_for(os: &str, arch: &str) -> String {
    format!("{}-{}-wt{}", os, arch, WASMTIME_VERSION)
}

/// Platform key for the current host process.
fn host_platform_key() -> String {
    platform_key_for(std::env::consts::OS, std::env::consts::ARCH)
}

/// Map `(os, arch)` to a wasmtime target triple for cross-compilation.
/// Returns `None` when the requested platform matches the current host
/// (no cross-compilation needed).
fn target_triple_for(os: &str, arch: &str) -> Option<&'static str> {
    let host_os = std::env::consts::OS;
    let host_arch = std::env::consts::ARCH;
    if os == host_os && arch == host_arch {
        return None; // host – no cross-compilation required
    }
    match (os, arch) {
        ("linux", "x86_64") => Some("x86_64-unknown-linux-gnu"),
        ("linux", "aarch64") => Some("aarch64-unknown-linux-gnu"),
        ("macos", "x86_64") => Some("x86_64-apple-darwin"),
        ("macos", "aarch64") => Some("aarch64-apple-darwin"),
        ("windows", "x86_64") => Some("x86_64-pc-windows-msvc"),
        ("windows", "aarch64") => Some("aarch64-pc-windows-msvc"),
        ("ios", "aarch64") => Some("aarch64-apple-ios"),
        ("android", "aarch64") => Some("aarch64-linux-android"),
        ("android", "x86_64") => Some("x86_64-linux-android"),
        _ => None,
    }
}

/// Lightweight target specification used by the API to enumerate compilation
/// targets. Does not include presigned URLs — those are generated by the
/// dispatcher when building a `CompilationJob`.
#[derive(Clone, Debug)]
pub struct TargetSpec {
    pub platform_key: String,
    pub cross_triple: Option<String>,
}

/// Read the list of platforms to compile for from `WASM_COMPILATION_TARGETS`.
///
/// Format: comma-separated `os-arch` pairs, e.g. `linux-x86_64,linux-aarch64`.
/// Falls back to the host platform when the variable is unset.
///
/// Used for **inline** compilation only. For external dispatch, use
/// [`all_known_targets`] so the worker can compile whichever subset it supports.
pub fn compilation_targets() -> Vec<TargetSpec> {
    if let Ok(val) = std::env::var("WASM_COMPILATION_TARGETS") {
        val.split(',')
            .filter_map(|entry| {
                let entry = entry.trim();
                let (os, arch) = entry.split_once('-')?;
                Some(TargetSpec {
                    platform_key: platform_key_for(os, arch),
                    cross_triple: target_triple_for(os, arch).map(String::from),
                })
            })
            .collect()
    } else {
        vec![TargetSpec {
            platform_key: host_platform_key(),
            cross_triple: None,
        }]
    }
}

/// The platform key the executor expects.
///
/// Read from `EXECUTOR_PLATFORM` (e.g. `linux-x86_64-wt40`).
/// Falls back to the host platform key when unset.
pub fn executor_target_platform() -> String {
    std::env::var("EXECUTOR_PLATFORM").unwrap_or_else(|_| host_platform_key())
}

/// Every platform the system knows how to compile for.
///
/// Used by the dispatcher to generate presigned upload URLs for **all**
/// potential targets so the external worker can compile whichever subset
/// it supports without the API needing to know the worker's configuration.
const ALL_KNOWN_PLATFORMS: &[(&str, &str)] = &[
    ("linux", "x86_64"),
    ("linux", "aarch64"),
    ("macos", "x86_64"),
    ("macos", "aarch64"),
    ("windows", "x86_64"),
    ("windows", "aarch64"),
    ("ios", "aarch64"),
    ("android", "aarch64"),
    ("android", "x86_64"),
];

pub fn all_known_targets() -> Vec<TargetSpec> {
    ALL_KNOWN_PLATFORMS
        .iter()
        .map(|(os, arch)| TargetSpec {
            platform_key: platform_key_for(os, arch),
            cross_triple: target_triple_for(os, arch).map(String::from),
        })
        .collect()
}

/// Author information for display
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct AuthorInfo {
    pub user_id: String,
    pub username: Option<String>,
    pub name: Option<String>,
    pub avatar: Option<String>,
    pub role: Option<String>,
}

/// Extended package summary with additional metadata for UI
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct PackageDetails {
    pub id: String,
    pub name: String,
    pub description: String,
    pub version: String,
    pub authors: Vec<AuthorInfo>,
    pub license: Option<String>,
    pub homepage: Option<String>,
    pub repository: Option<String>,
    pub keywords: Vec<String>,
    pub status: String,
    pub verified: bool,
    pub download_count: u64,
    pub wasm_size: u64,
    pub nodes: serde_json::Value,
    pub permissions: serde_json::Value,
    pub price: i64,
    pub visibility: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub published_at: Option<chrono::DateTime<chrono::Utc>>,
}

/// Package review entry
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct PackageReview {
    pub id: String,
    pub package_id: String,
    pub reviewer_id: String,
    pub action: String,
    pub comment: Option<String>,
    pub security_score: Option<i32>,
    pub code_quality_score: Option<i32>,
    pub documentation_score: Option<i32>,
    pub created_at: chrono::DateTime<chrono::Utc>,
}

/// Request to submit a review
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct ReviewRequest {
    pub action: String, // "approve", "reject", "request_changes", "comment", "flag"
    pub comment: Option<String>,
    pub internal_note: Option<String>,
    pub security_score: Option<i32>,
    pub code_quality_score: Option<i32>,
    pub documentation_score: Option<i32>,
}

/// Statistics for the registry
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct RegistryStats {
    pub total_packages: i64,
    pub total_versions: i64,
    pub total_downloads: i64,
    pub pending_review: i64,
    pub active_packages: i64,
    pub rejected_packages: i64,
    pub verified_packages: i64,
}

fn status_to_string(status: &crate::entity::sea_orm_active_enums::WasmPackageStatus) -> String {
    use crate::entity::sea_orm_active_enums::WasmPackageStatus;
    match status {
        WasmPackageStatus::PendingReview => "pending_review".to_string(),
        WasmPackageStatus::Active => "active".to_string(),
        WasmPackageStatus::Rejected => "rejected".to_string(),
        WasmPackageStatus::Deprecated => "deprecated".to_string(),
        WasmPackageStatus::Disabled => "disabled".to_string(),
    }
}

fn visibility_to_string(v: &WasmPackageVisibility) -> String {
    match v {
        WasmPackageVisibility::Public => "public".to_string(),
        WasmPackageVisibility::Private => "private".to_string(),
        WasmPackageVisibility::PublicRequestAccess => "public_request_access".to_string(),
    }
}

fn status_to_enum(status: &str) -> crate::entity::sea_orm_active_enums::WasmPackageStatus {
    use crate::entity::sea_orm_active_enums::WasmPackageStatus;
    match status {
        "pending_review" => WasmPackageStatus::PendingReview,
        "active" => WasmPackageStatus::Active,
        "rejected" => WasmPackageStatus::Rejected,
        "deprecated" => WasmPackageStatus::Deprecated,
        "disabled" => WasmPackageStatus::Disabled,
        _ => WasmPackageStatus::PendingReview,
    }
}

/// Server-side registry for managing WASM packages
/// Uses PostgreSQL for metadata and CDN for WASM binaries
pub struct ServerRegistry {
    db: DatabaseConnection,
    content_bucket: Arc<FlowLikeStore>,
    meta_bucket: Arc<FlowLikeStore>,
    compilation_dispatcher: Option<Arc<crate::compilation::CompilationDispatcher>>,
}

impl ServerRegistry {
    pub fn new(
        db: DatabaseConnection,
        content_bucket: Arc<FlowLikeStore>,
        meta_bucket: Arc<FlowLikeStore>,
    ) -> Self {
        Self {
            db,
            content_bucket,
            meta_bucket,
            compilation_dispatcher: None,
        }
    }

    pub fn with_compilation_dispatcher(
        mut self,
        dispatcher: Arc<crate::compilation::CompilationDispatcher>,
    ) -> Self {
        self.compilation_dispatcher = Some(dispatcher);
        self
    }

    /// Get storage path for a WASM package version
    fn wasm_path(package_id: &str, version: &str) -> Path {
        Path::from(WASM_PACKAGES_PATH)
            .child(package_id)
            .child(version)
            .child("node.wasm")
    }

    /// Fetch meta models for a batch of packages, filtered by language + English fallback.
    async fn fetch_meta_map(
        &self,
        packages: &[wasm_package::Model],
        language: &str,
    ) -> flow_like_types::Result<std::collections::HashMap<String, Vec<meta::Model>>> {
        if packages.is_empty() {
            return Ok(std::collections::HashMap::new());
        }
        let pkg_ids: Vec<String> = packages.iter().map(|p| p.id.clone()).collect();
        let metas = meta::Entity::find()
            .filter(meta::Column::WasmPackageId.is_in(pkg_ids))
            .filter(
                meta::Column::Lang
                    .eq(language)
                    .or(meta::Column::Lang.eq("en")),
            )
            .all(&self.db)
            .await?;
        Ok(metas.into_iter().fold(
            std::collections::HashMap::new(),
            |mut acc, m| {
                if let Some(ref pkg_id) = m.wasm_package_id {
                    acc.entry(pkg_id.clone()).or_default().push(m);
                }
                acc
            },
        ))
    }

    /// Get a presigned PUT URL for uploading a WASM binary to temporary storage
    pub async fn get_upload_url(&self, tmp_path: &str) -> flow_like_types::Result<String> {
        let path = Path::from(tmp_path);
        let url = self
            .content_bucket
            .sign("PUT", &path, Duration::from_secs(3600))
            .await?;
        Ok(url.to_string())
    }

    /// Compile WASM bytes to AOT .cwasm for every configured target platform
    /// and store artifacts + checksums in the bucket.
    ///
    /// Set `WASM_COMPILATION_TARGETS=linux-x86_64,linux-aarch64` to cross-compile.
    /// Defaults to host-only when the variable is unset.
    pub async fn compile_and_store_artifact(
        &self,
        package_id: &str,
        version: &str,
        wasm_bytes: &[u8],
    ) -> flow_like_types::Result<Vec<String>> {
        let targets = compilation_targets();
        let mut compiled_platforms = Vec::new();

        for target in &targets {
            let mut config = flow_like_wasm::engine::WasmConfig::default().without_cache();
            if let Some(triple) = &target.cross_triple {
                config = config.with_target(triple);
            }
            let engine = flow_like_wasm::engine::WasmEngine::new(config)?;
            let serialized = engine.precompile(wasm_bytes)?;

            let base = Path::from(WASM_COMPILED_PATH)
                .child(package_id)
                .child(version);
            let cwasm_path = base.child(format!("{}.cwasm", target.platform_key));
            let hash_path = base.child(format!("{}.cwasm.b3", target.platform_key));
            let hash = blake3::hash(&serialized).to_hex().to_string();

            self.meta_bucket
                .as_generic()
                .put(&cwasm_path, PutPayload::from(serialized))
                .await?;
            self.meta_bucket
                .as_generic()
                .put(&hash_path, PutPayload::from(hash.into_bytes()))
                .await?;

            compiled_platforms.push(target.platform_key.clone());
        }

        Ok(compiled_platforms)
    }

    pub async fn recompile_version(
        &self,
        sub: String,
        package_id: &str,
        version: &str,
    ) -> flow_like_types::Result<()> {
        let use_external = self
            .compilation_dispatcher
            .as_ref()
            .map_or(false, |d| d.backend().is_external());

        if use_external {
            let wasm_path = Self::wasm_path(package_id, version).to_string();

            let version_record = wasm_package_version::Entity::find()
                .filter(wasm_package_version::Column::PackageId.eq(package_id))
                .filter(wasm_package_version::Column::Version.eq(version))
                .one(&self.db)
                .await?
                .ok_or_else(|| flow_like_types::anyhow!("Version not found"))?;

            let dispatcher = self
                .compilation_dispatcher
                .clone()
                .ok_or_else(|| flow_like_types::anyhow!("Compilation dispatcher not configured"))?;
            let params = crate::compilation::DispatchParams {
                package_id: package_id.to_string(),
                version: version.to_string(),
                wasm_path,
                wasm_hash: version_record.wasm_hash,
            };
            let resp = dispatcher.dispatch(sub, params).await
                .map_err(|e| flow_like_types::anyhow!("Dispatch failed: {e}"))?;
            tracing::info!(
                pkg = %package_id,
                ver = %version,
                job_id = %resp.job_id,
                backend = %resp.backend,
                "Recompilation job dispatched to external backend"
            );
        } else {
            let db = self.db.clone();
            let content_bucket = self.content_bucket.clone();
            let meta_bucket = self.meta_bucket.clone();
            let pkg_id = package_id.to_string();
            let ver = version.to_string();

            flow_like_types::tokio::spawn(async move {
                let inline_registry = ServerRegistry::new(db.clone(), content_bucket, meta_bucket);
                let wasm_path = ServerRegistry::wasm_path(&pkg_id, &ver);
                let data = match inline_registry.content_bucket.as_generic().get(&wasm_path).await {
                    Ok(d) => d,
                    Err(e) => {
                        tracing::error!(pkg = %pkg_id, ver = %ver, err = %e, "Failed to fetch WASM for recompilation");
                        return;
                    }
                };
                let wasm_bytes = match data.bytes().await {
                    Ok(b) => b.to_vec(),
                    Err(e) => {
                        tracing::error!(pkg = %pkg_id, ver = %ver, err = %e, "Failed to read WASM bytes");
                        return;
                    }
                };

                match inline_registry.compile_and_store_artifact(&pkg_id, &ver, &wasm_bytes).await {
                    Ok(platforms) => {
                        let version_record = wasm_package_version::Entity::find()
                            .filter(wasm_package_version::Column::PackageId.eq(&pkg_id))
                            .filter(wasm_package_version::Column::Version.eq(&ver))
                            .one(&db)
                            .await;
                        if let Ok(Some(record)) = version_record {
                            let mut active: wasm_package_version::ActiveModel = record.into();
                            active.compilation_status = Set(WasmCompilationStatus::Compiled);
                            active.compiled_platforms = Set(platforms);
                            active.compilation_error = Set(None);
                            let _ = active.update(&db).await;
                        }
                    }
                    Err(e) => {
                        tracing::error!(pkg = %pkg_id, ver = %ver, err = %e, "Inline recompilation failed");
                        let version_record = wasm_package_version::Entity::find()
                            .filter(wasm_package_version::Column::PackageId.eq(&pkg_id))
                            .filter(wasm_package_version::Column::Version.eq(&ver))
                            .one(&db)
                            .await;
                        if let Ok(Some(record)) = version_record {
                            let mut active: wasm_package_version::ActiveModel = record.into();
                            active.compilation_status = Set(WasmCompilationStatus::LocalOnly);
                            active.compilation_error = Set(Some(e.to_string()));
                            let _ = active.update(&db).await;
                        }
                    }
                }
            });
        }

        Ok(())
    }

    /// Get a signed URL or CDN URL for downloading a WASM file
    async fn get_download_url(
        &self,
        package_id: &str,
        version: &str,
    ) -> flow_like_types::Result<String> {
        let path = Self::wasm_path(package_id, version);

        // Otherwise generate a signed URL (valid for 1 hour)
        let url = self
            .content_bucket
            .sign("GET", &path, Duration::from_secs(3600))
            .await?;
        Ok(url.to_string())
    }

    /// Generate presigned GET URLs for a compiled `.cwasm` artifact and its checksum.
    ///
    /// `target_platform` is the platform key the executor expects
    /// (e.g. `linux-x86_64-wt40`).  Pass [`executor_target_platform()`] when the
    /// caller doesn't have a more specific value.
    pub async fn sign_cwasm_urls(
        &self,
        package_id: &str,
        version: &str,
        target_platform: &str,
    ) -> flow_like_types::Result<(String, String)> {
        let base = Path::from(WASM_COMPILED_PATH)
            .child(package_id)
            .child(version);

        let cwasm_path = base.child(format!("{}.cwasm", target_platform));
        let checksum_path = base.child(format!("{}.cwasm.b3", target_platform));

        let cwasm_url = self
            .meta_bucket
            .sign("GET", &cwasm_path, Duration::from_secs(3600))
            .await?;
        let checksum_url = self
            .meta_bucket
            .sign("GET", &checksum_path, Duration::from_secs(3600))
            .await?;

        Ok((cwasm_url.to_string(), checksum_url.to_string()))
    }

    /// Get the registry index (list of all publicly accessible packages)
    pub async fn get_index(&self) -> flow_like_types::Result<RegistryIndex> {
        use crate::entity::sea_orm_active_enums::WasmPackageStatus;
        use sea_orm::Condition;

        let packages = wasm_package::Entity::find()
            .filter(wasm_package::Column::Status.eq(WasmPackageStatus::Active))
            .filter(
                Condition::any()
                    .add(wasm_package::Column::Visibility.eq(WasmPackageVisibility::Public))
                    .add(wasm_package::Column::Visibility.eq(WasmPackageVisibility::PublicRequestAccess)),
            )
            .order_by_desc(wasm_package::Column::DownloadCount)
            .all(&self.db)
            .await?;

        let summaries: Vec<PackageSummary> = packages
            .into_iter()
            .map(|pkg| {
                let vis = visibility_to_string(&pkg.visibility);
                PackageSummary {
                    id: pkg.id,
                    name: pkg.name,
                    description: pkg.description,
                    latest_version: pkg.version,
                    download_count: pkg.download_count as u64,
                    status: PackageStatus::Active,
                    keywords: pkg.keywords.unwrap_or_default(),
                    verified: pkg.verified,
                    price: pkg.price,
                    visibility: vis,
                    metadata: None,
                }
            })
            .collect();

        Ok(RegistryIndex {
            name: "Flow-Like WASM Registry".to_string(),
            url: String::new(),
            updated_at: chrono::Utc::now(),
            packages: summaries,
        })
    }

    /// Get registry statistics (admin)
    pub async fn get_stats(&self) -> flow_like_types::Result<RegistryStats> {
        use crate::entity::sea_orm_active_enums::WasmPackageStatus;

        let total_packages = wasm_package::Entity::find().count(&self.db).await? as i64;

        let total_versions = wasm_package_version::Entity::find().count(&self.db).await? as i64;

        let active_packages = wasm_package::Entity::find()
            .filter(wasm_package::Column::Status.eq(WasmPackageStatus::Active))
            .count(&self.db)
            .await? as i64;

        let pending_review = wasm_package::Entity::find()
            .filter(wasm_package::Column::Status.eq(WasmPackageStatus::PendingReview))
            .count(&self.db)
            .await? as i64;

        let rejected_packages = wasm_package::Entity::find()
            .filter(wasm_package::Column::Status.eq(WasmPackageStatus::Rejected))
            .count(&self.db)
            .await? as i64;

        let verified_packages = wasm_package::Entity::find()
            .filter(wasm_package::Column::Verified.eq(true))
            .count(&self.db)
            .await? as i64;

        // Sum all download counts
        let downloads_result: Option<i64> = wasm_package::Entity::find()
            .select_only()
            .column_as(wasm_package::Column::DownloadCount.sum(), "total")
            .into_tuple()
            .one(&self.db)
            .await?;

        Ok(RegistryStats {
            total_packages,
            total_versions,
            total_downloads: downloads_result.unwrap_or(0),
            pending_review,
            active_packages,
            rejected_packages,
            verified_packages,
        })
    }

    /// Get a package entry by ID (public - only returns active packages)
    pub async fn get_package(&self, id: &str) -> flow_like_types::Result<Option<RegistryEntry>> {
        use crate::entity::sea_orm_active_enums::WasmPackageStatus;

        let Some(pkg) = wasm_package::Entity::find_by_id(id)
            .filter(wasm_package::Column::Status.eq(WasmPackageStatus::Active))
            .one(&self.db)
            .await?
        else {
            return Ok(None);
        };

        self.build_registry_entry(pkg).await.map(Some)
    }

    /// Get a package entry by ID (admin - returns any status)
    pub async fn get_package_admin(
        &self,
        id: &str,
    ) -> flow_like_types::Result<Option<PackageDetails>> {
        let Some(pkg) = wasm_package::Entity::find_by_id(id).one(&self.db).await? else {
            return Ok(None);
        };

        let authors = self.get_package_authors(&pkg.id).await?;

        Ok(Some(PackageDetails {
            id: pkg.id,
            name: pkg.name,
            description: pkg.description,
            version: pkg.version,
            authors,
            license: pkg.license,
            homepage: pkg.homepage,
            repository: pkg.repository,
            keywords: pkg.keywords.unwrap_or_default(),
            status: status_to_string(&pkg.status),
            verified: pkg.verified,
            download_count: pkg.download_count as u64,
            wasm_size: pkg.wasm_size as u64,
            nodes: pkg.nodes,
            permissions: pkg.permissions,
            price: pkg.price,
            visibility: visibility_to_string(&pkg.visibility),
            created_at: chrono::DateTime::from_naive_utc_and_offset(pkg.created_at, chrono::Utc),
            updated_at: chrono::DateTime::from_naive_utc_and_offset(pkg.updated_at, chrono::Utc),
            published_at: pkg
                .published_at
                .map(|dt| chrono::DateTime::from_naive_utc_and_offset(dt, chrono::Utc)),
        }))
    }

    /// Get authors for a package with user information
    async fn get_package_authors(
        &self,
        package_id: &str,
    ) -> flow_like_types::Result<Vec<AuthorInfo>> {
        let author_records = wasm_package_author::Entity::find()
            .filter(wasm_package_author::Column::PackageId.eq(package_id))
            .all(&self.db)
            .await?;

        let mut authors = Vec::new();
        for record in author_records {
            let user_info = user::Entity::find_by_id(&record.user_id)
                .one(&self.db)
                .await?;

            authors.push(AuthorInfo {
                user_id: record.user_id,
                username: user_info.as_ref().and_then(|u| u.username.clone()),
                name: user_info.as_ref().and_then(|u| u.name.clone()),
                avatar: user_info.and_then(|u| u.avatar),
                role: record.role,
            });
        }

        Ok(authors)
    }

    /// Build a RegistryEntry from a package model
    async fn build_registry_entry(
        &self,
        pkg: wasm_package::Model,
    ) -> flow_like_types::Result<RegistryEntry> {
        use crate::entity::sea_orm_active_enums::WasmPackageStatus;

        let versions = wasm_package_version::Entity::find()
            .filter(wasm_package_version::Column::PackageId.eq(&pkg.id))
            .filter(wasm_package_version::Column::Status.eq(WasmPackageStatus::Active))
            .order_by_desc(wasm_package_version::Column::PublishedAt)
            .all(&self.db)
            .await?;

        // Get authors from junction table
        let author_infos = self.get_package_authors(&pkg.id).await?;
        let authors: Vec<flow_like_wasm::manifest::PackageAuthor> = author_infos
            .into_iter()
            .map(|a| flow_like_wasm::manifest::PackageAuthor {
                name: a.name.or(a.username).unwrap_or(a.user_id),
                email: None,
                url: None,
            })
            .collect();

        let manifest = PackageManifest {
            manifest_version: flow_like_wasm::manifest::MANIFEST_VERSION,
            id: pkg.id.clone(),
            name: pkg.name.clone(),
            description: pkg.description.clone(),
            version: pkg.version.clone(),
            authors,
            license: pkg.license.clone(),
            homepage: pkg.homepage.clone(),
            repository: pkg.repository.clone(),
            keywords: pkg.keywords.unwrap_or_default(),
            nodes: serde_json::from_value(pkg.nodes.clone()).unwrap_or_default(),
            permissions: serde_json::from_value(pkg.permissions.clone()).unwrap_or_default(),
            min_flow_like_version: None,
            wasm_path: Some(pkg.wasm_path.clone()),
            wasm_hash: Some(pkg.wasm_hash.clone()),
            metadata: Default::default(),
        };

        let package_versions: Vec<PackageVersion> = versions
            .into_iter()
            .map(|v| PackageVersion {
                version: v.version,
                wasm_hash: v.wasm_hash,
                wasm_size: v.wasm_size as u64,
                download_url: None,
                published_at: chrono::DateTime::from_naive_utc_and_offset(
                    v.published_at,
                    chrono::Utc,
                ),
                min_flow_like_version: v.min_flow_like_version,
                release_notes: v.release_notes,
                yanked: v.yanked,
            })
            .collect();

        let vis = visibility_to_string(&pkg.visibility);
        let price = pkg.price;

        Ok(RegistryEntry {
            id: pkg.id,
            manifest,
            versions: package_versions,
            status: match pkg.status {
                WasmPackageStatus::Active => PackageStatus::Active,
                WasmPackageStatus::Deprecated => PackageStatus::Deprecated,
                _ => PackageStatus::Disabled,
            },
            download_count: pkg.download_count as u64,
            created_at: chrono::DateTime::from_naive_utc_and_offset(pkg.created_at, chrono::Utc),
            updated_at: chrono::DateTime::from_naive_utc_and_offset(pkg.updated_at, chrono::Utc),
            source: PackageSource::Remote {
                registry_url: String::new(),
                download_url: String::new(),
            },
            verified: pkg.verified,
            price,
            visibility: vis,
            current_user_permission: None,
        })
    }

    /// Search packages with filters
    pub async fn search(&self, filters: &SearchFilters) -> flow_like_types::Result<SearchResults> {
        use crate::entity::sea_orm_active_enums::WasmPackageStatus;

        let mut query = wasm_package::Entity::find();

        // Only show active packages unless including deprecated
        if !filters.include_deprecated {
            query = query.filter(wasm_package::Column::Status.eq(WasmPackageStatus::Active));
        }

        // Only show public-facing packages in the basic search
        query = query.filter(
            sea_orm::Condition::any()
                .add(wasm_package::Column::Visibility.eq(WasmPackageVisibility::Public))
                .add(wasm_package::Column::Visibility.eq(WasmPackageVisibility::PublicRequestAccess)),
        );

        // Filter by verified only
        if filters.verified_only {
            query = query.filter(wasm_package::Column::Verified.eq(true));
        }

        // Text search (name, description, keywords)
        if let Some(q) = &filters.query {
            let pattern = format!("%{}%", q.to_lowercase());
            query = query.filter(
                wasm_package::Column::Name
                    .contains(&pattern)
                    .or(wasm_package::Column::Description.contains(&pattern))
                    .or(wasm_package::Column::Id.contains(&pattern)),
            );
        }

        // Get total count before pagination
        let total_count = query.clone().count(&self.db).await? as usize;

        // Apply sorting
        query = match filters.sort_by {
            SortField::Downloads => {
                if filters.sort_desc {
                    query.order_by_desc(wasm_package::Column::DownloadCount)
                } else {
                    query.order_by_asc(wasm_package::Column::DownloadCount)
                }
            }
            SortField::Name => {
                if filters.sort_desc {
                    query.order_by_desc(wasm_package::Column::Name)
                } else {
                    query.order_by_asc(wasm_package::Column::Name)
                }
            }
            SortField::UpdatedAt => {
                if filters.sort_desc {
                    query.order_by_desc(wasm_package::Column::UpdatedAt)
                } else {
                    query.order_by_asc(wasm_package::Column::UpdatedAt)
                }
            }
            SortField::CreatedAt => {
                if filters.sort_desc {
                    query.order_by_desc(wasm_package::Column::CreatedAt)
                } else {
                    query.order_by_asc(wasm_package::Column::CreatedAt)
                }
            }
            SortField::Relevance => {
                // For relevance, sort by downloads as a proxy for popularity
                if filters.sort_desc {
                    query.order_by_desc(wasm_package::Column::DownloadCount)
                } else {
                    query.order_by_asc(wasm_package::Column::DownloadCount)
                }
            }
        };

        // Apply pagination
        let packages = query
            .offset(filters.offset as u64)
            .limit(filters.limit as u64)
            .all(&self.db)
            .await?;

        let language = filters.language.as_deref().unwrap_or("en");
        let meta_map = self.fetch_meta_map(&packages, language).await?;

        let summaries: Vec<PackageSummary> = packages
            .into_iter()
            .map(|pkg| {
                let vis = visibility_to_string(&pkg.visibility);
                let resolved_meta = meta_map
                    .get(&pkg.id)
                    .and_then(|metas| MetaSummary::pick_best(metas, language))
                    .map(MetaSummary::from_model);
                PackageSummary {
                    id: pkg.id,
                    name: pkg.name,
                    description: pkg.description,
                    latest_version: pkg.version,
                    download_count: pkg.download_count as u64,
                    status: match pkg.status {
                        WasmPackageStatus::Active => PackageStatus::Active,
                        WasmPackageStatus::Deprecated => PackageStatus::Deprecated,
                        _ => PackageStatus::Disabled,
                    },
                    keywords: pkg.keywords.unwrap_or_default(),
                    verified: pkg.verified,
                    price: pkg.price,
                    visibility: vis,
                    metadata: resolved_meta,
                }
            })
            .collect();

        Ok(SearchResults {
            packages: summaries,
            total_count,
            offset: filters.offset,
            limit: filters.limit,
        })
    }

    /// Search packages with visibility filtering.
    /// Public packages are always returned. When `include_own` is true and a
    /// caller_id is provided, private packages the caller has access to are
    /// included as well.
    pub async fn search_with_visibility(
        &self,
        filters: &SearchFilters,
        caller_id: Option<&str>,
        include_own: bool,
    ) -> flow_like_types::Result<SearchResults> {
        use crate::entity::sea_orm_active_enums::WasmPackageStatus;
        use sea_orm::Condition;

        let mut query = wasm_package::Entity::find();

        if !filters.include_deprecated {
            query = query.filter(wasm_package::Column::Status.eq(WasmPackageStatus::Active));
        }

        if filters.verified_only {
            query = query.filter(wasm_package::Column::Verified.eq(true));
        }

        // Visibility filtering
        match (caller_id, include_own) {
            (Some(uid), true) => {
                let user_package_ids: Vec<String> = wasm_package_user::Entity::find()
                    .filter(wasm_package_user::Column::UserId.eq(uid))
                    .all(&self.db)
                    .await?
                    .into_iter()
                    .map(|r| r.package_id)
                    .collect();

                query = query.filter(
                    Condition::any()
                        .add(
                            wasm_package::Column::Visibility
                                .eq(WasmPackageVisibility::Public),
                        )
                        .add(
                            wasm_package::Column::Visibility
                                .eq(WasmPackageVisibility::PublicRequestAccess),
                        )
                        .add(wasm_package::Column::Id.is_in(user_package_ids)),
                );
            }
            _ => {
                query = query.filter(
                    Condition::any()
                        .add(wasm_package::Column::Visibility.eq(WasmPackageVisibility::Public))
                        .add(wasm_package::Column::Visibility.eq(WasmPackageVisibility::PublicRequestAccess)),
                );
            }
        }

        if let Some(q) = &filters.query {
            let pattern = format!("%{}%", q.to_lowercase());
            query = query.filter(
                wasm_package::Column::Name
                    .contains(&pattern)
                    .or(wasm_package::Column::Description.contains(&pattern))
                    .or(wasm_package::Column::Id.contains(&pattern)),
            );
        }

        let total_count = query.clone().count(&self.db).await? as usize;

        query = match filters.sort_by {
            SortField::Downloads => {
                if filters.sort_desc {
                    query.order_by_desc(wasm_package::Column::DownloadCount)
                } else {
                    query.order_by_asc(wasm_package::Column::DownloadCount)
                }
            }
            SortField::Name => {
                if filters.sort_desc {
                    query.order_by_desc(wasm_package::Column::Name)
                } else {
                    query.order_by_asc(wasm_package::Column::Name)
                }
            }
            SortField::UpdatedAt => {
                if filters.sort_desc {
                    query.order_by_desc(wasm_package::Column::UpdatedAt)
                } else {
                    query.order_by_asc(wasm_package::Column::UpdatedAt)
                }
            }
            SortField::CreatedAt => {
                if filters.sort_desc {
                    query.order_by_desc(wasm_package::Column::CreatedAt)
                } else {
                    query.order_by_asc(wasm_package::Column::CreatedAt)
                }
            }
            SortField::Relevance => {
                if filters.sort_desc {
                    query.order_by_desc(wasm_package::Column::DownloadCount)
                } else {
                    query.order_by_asc(wasm_package::Column::DownloadCount)
                }
            }
        };

        let packages = query
            .offset(filters.offset as u64)
            .limit(filters.limit as u64)
            .all(&self.db)
            .await?;

        let language = filters.language.as_deref().unwrap_or("en");
        let meta_map = self.fetch_meta_map(&packages, language).await?;

        let summaries: Vec<PackageSummary> = packages
            .into_iter()
            .map(|pkg| {
                let vis = visibility_to_string(&pkg.visibility);
                let resolved_meta = meta_map
                    .get(&pkg.id)
                    .and_then(|metas| MetaSummary::pick_best(metas, language))
                    .map(MetaSummary::from_model);
                PackageSummary {
                    id: pkg.id,
                    name: pkg.name,
                    description: pkg.description,
                    latest_version: pkg.version,
                    download_count: pkg.download_count as u64,
                    status: match pkg.status {
                        WasmPackageStatus::Active => PackageStatus::Active,
                        WasmPackageStatus::Deprecated => PackageStatus::Deprecated,
                        _ => PackageStatus::Disabled,
                    },
                    keywords: pkg.keywords.unwrap_or_default(),
                    verified: pkg.verified,
                    price: pkg.price,
                    visibility: vis,
                    metadata: resolved_meta,
                }
            })
            .collect();

        Ok(SearchResults {
            packages: summaries,
            total_count,
            offset: filters.offset,
            limit: filters.limit,
        })
    }

    /// Get download URL for a package (signed URL or CDN URL)
    pub async fn get_wasm_url(
        &self,
        package_id: &str,
        version: Option<&str>,
    ) -> flow_like_types::Result<(String, PackageManifest, String)> {
        let Some(entry) = self.get_package(package_id).await? else {
            return Err(flow_like_types::anyhow!(
                "Package not found: {}",
                package_id
            ));
        };

        let ver = if let Some(v) = version {
            entry
                .get_version(v)
                .ok_or_else(|| flow_like_types::anyhow!("Version not found: {}", v))?
                .clone()
        } else {
            entry
                .latest_version()
                .ok_or_else(|| flow_like_types::anyhow!("No versions available"))?
                .clone()
        };

        let download_url = self.get_download_url(package_id, &ver.version).await?;

        Ok((download_url, entry.manifest, ver.version))
    }

    /// Download package WASM binary directly (for backward compatibility)
    pub async fn download_wasm(
        &self,
        package_id: &str,
        version: Option<&str>,
    ) -> flow_like_types::Result<(Vec<u8>, PackageManifest, String)> {
        let Some(entry) = self.get_package(package_id).await? else {
            return Err(flow_like_types::anyhow!(
                "Package not found: {}",
                package_id
            ));
        };

        let ver = if let Some(v) = version {
            entry
                .get_version(v)
                .ok_or_else(|| flow_like_types::anyhow!("Version not found: {}", v))?
                .clone()
        } else {
            entry
                .latest_version()
                .ok_or_else(|| flow_like_types::anyhow!("No versions available"))?
                .clone()
        };

        let path = Self::wasm_path(package_id, &ver.version);
        let data = self.content_bucket.as_generic().get(&path).await?;
        let bytes = data.bytes().await?.to_vec();

        Ok((bytes, entry.manifest, ver.version))
    }
    /// Two-step publish: fetch WASM from tmp path, hash, move to final location, create DB records
    pub async fn publish_from_tmp(
        &self,
        manifest: PackageManifest,
        tmp_path: &str,
        submitter_id: Option<String>,
        _submitter_email: Option<String>,
    ) -> flow_like_types::Result<PublishResponse> {
        use crate::entity::sea_orm_active_enums::{WasmPackageStatus, WasmReviewAction};

        let now = chrono::Utc::now().naive_utc();

        let existing_version = wasm_package_version::Entity::find()
            .filter(wasm_package_version::Column::PackageId.eq(&manifest.id))
            .filter(wasm_package_version::Column::Version.eq(&manifest.version))
            .one(&self.db)
            .await?;

        if existing_version.is_some() {
            return Err(flow_like_types::anyhow!(
                "Version {} already exists for package {}",
                manifest.version,
                manifest.id
            ));
        }

        let tmp_object_path = Path::from(tmp_path);
        let data = self
            .content_bucket
            .as_generic()
            .get(&tmp_object_path)
            .await
            .map_err(|_| {
                flow_like_types::anyhow!("WASM not found at tmp path — upload may have failed")
            })?;

        let wasm_data = data.bytes().await?.to_vec();

        if wasm_data.len() < 8 || &wasm_data[0..4] != b"\0asm" {
            return Err(flow_like_types::anyhow!("Invalid WASM binary"));
        }

        let hash = blake3::hash(&wasm_data).to_hex().to_string();
        let size = wasm_data.len() as i64;
        let compile_wasm_data = wasm_data.clone();

        // Check for hash duplicates (non-blocking flag)
        let duplicate_info = wasm_package_version::Entity::find()
            .filter(wasm_package_version::Column::WasmHash.eq(&hash))
            .one(&self.db)
            .await?;

        let (dup_pkg_id, dup_version, dup_flagged) = if let Some(dup) = &duplicate_info {
            (
                Some(dup.package_id.clone()),
                Some(dup.version.clone()),
                true,
            )
        } else {
            (None, None, false)
        };

        // Move WASM from tmp to final path
        let final_wasm_path = Self::wasm_path(&manifest.id, &manifest.version);
        self.content_bucket
            .as_generic()
            .put(&final_wasm_path, PutPayload::from(wasm_data))
            .await?;

        let existing_package = wasm_package::Entity::find_by_id(&manifest.id)
            .one(&self.db)
            .await?;

        if let Some(_existing) = existing_package {
            // Existing package: only bump updated_at.
            // Version-specific fields (version, wasm_path, wasm_hash, nodes, etc.)
            // are NOT updated on the parent package until this version is approved.
            let update_model = wasm_package::ActiveModel {
                id: Set(manifest.id.clone()),
                updated_at: Set(now),
                ..Default::default()
            };
            update_model.update(&self.db).await?;
        } else {
            let package_model = wasm_package::ActiveModel {
                id: Set(manifest.id.clone()),
                name: Set(manifest.name.clone()),
                description: Set(manifest.description.clone()),
                version: Set(manifest.version.clone()),
                license: Set(manifest.license.clone()),
                homepage: Set(manifest.homepage.clone()),
                repository: Set(manifest.repository.clone()),
                keywords: Set(Some(manifest.keywords.clone())),
                status: Set(WasmPackageStatus::PendingReview),
                visibility: Set(WasmPackageVisibility::Private),
                verified: Set(false),
                download_count: Set(0),
                wasm_path: Set(final_wasm_path.to_string()),
                wasm_hash: Set(hash.clone()),
                wasm_size: Set(size),
                nodes: Set(serde_json::to_value(&manifest.nodes)?),
                permissions: Set(serde_json::to_value(&manifest.permissions)?),
                readme: Set(None),
                price: Set(0),
                created_at: Set(now),
                updated_at: Set(now),
                published_at: Set(None),
            };
            package_model.insert(&self.db).await?;

            if let Some(ref user_id) = submitter_id {
                let user_model = wasm_package_user::ActiveModel {
                    id: Set(create_id()),
                    package_id: Set(manifest.id.clone()),
                    user_id: Set(user_id.clone()),
                    permission: Set(
                        crate::permission::wasm_package_permission::WasmPackagePermission::Owner
                            .bits(),
                    ),
                    granted_by: Set(None),
                    granted_at: Set(now),
                };
                user_model.insert(&self.db).await?;
            }

            let review_model = wasm_package_review::ActiveModel {
                id: Set(create_id()),
                package_id: Set(manifest.id.clone()),
                reviewer_id: Set(submitter_id
                    .clone()
                    .unwrap_or_else(|| "anonymous".to_string())),
                action: Set(WasmReviewAction::Submitted),
                comment: Set(None),
                internal_note: Set(None),
                security_score: Set(None),
                code_quality_score: Set(None),
                documentation_score: Set(None),
                created_at: Set(now),
            };
            review_model.insert(&self.db).await?;

            // Auto-create default English meta from manifest
            let meta_model = meta::ActiveModel {
                id: Set(create_id()),
                lang: Set("en".to_string()),
                name: Set(manifest.name.clone()),
                description: Set(Some(manifest.description.clone())),
                long_description: Set(None),
                tags: Set(if manifest.keywords.is_empty() {
                    None
                } else {
                    Some(manifest.keywords.clone())
                }),
                icon: Set(None),
                thumbnail: Set(None),
                website: Set(manifest.homepage.clone()),
                support_url: Set(None),
                docs_url: Set(None),
                use_case: Set(None),
                release_notes: Set(None),
                preview_media: Set(None),
                age_rating: Set(None),
                wasm_package_id: Set(Some(manifest.id.clone())),
                app_id: Set(None),
                bit_id: Set(None),
                course_id: Set(None),
                template_id: Set(None),
                widget_id: Set(None),
                organization_specific_values: Set(None),
                created_at: Set(now),
                updated_at: Set(now),
            };
            meta_model.insert(&self.db).await?;
        }

        let version_id = create_id();
        let compile_hash = hash.clone();
        let version_model = wasm_package_version::ActiveModel {
            id: Set(version_id.clone()),
            package_id: Set(manifest.id.clone()),
            version: Set(manifest.version.clone()),
            wasm_path: Set(final_wasm_path.to_string()),
            wasm_hash: Set(hash),
            wasm_size: Set(size),
            nodes: Set(serde_json::to_value(&manifest.nodes)?),
            release_notes: Set(None),
            min_flow_like_version: Set(None),
            yanked: Set(false),
            status: Set(WasmPackageStatus::PendingReview),
            compilation_status: Set(WasmCompilationStatus::Pending),
            compiled_platforms: Set(vec![]),
            compilation_error: Set(None),
            duplicate_of_package_id: Set(dup_pkg_id),
            duplicate_of_version: Set(dup_version),
            duplicate_flagged: Set(dup_flagged),
            published_at: Set(now),
            approved_at: Set(None),
        };
        version_model.insert(&self.db).await?;

        // Dispatch compilation based on configured backend
        let compile_db = self.db.clone();
        let compile_content = self.content_bucket.clone();
        let compile_meta = self.meta_bucket.clone();
        let compile_pkg_id = manifest.id.clone();
        let compile_version = manifest.version.clone();
        let compile_wasm_path = final_wasm_path.to_string();

        let use_external = self
            .compilation_dispatcher
            .as_ref()
            .map_or(false, |d| d.backend().is_external());

        // Dispatch compilation inline (not tokio::spawn — Lambda shuts down after response)
        if use_external {
            let dispatcher = self
                .compilation_dispatcher
                .clone()
                .ok_or_else(|| flow_like_types::anyhow!("Compilation dispatcher not configured"))?;
            let sub = submitter_id.clone().unwrap_or_default();
            let params = crate::compilation::DispatchParams {
                package_id: compile_pkg_id.clone(),
                version: compile_version.clone(),
                wasm_path: compile_wasm_path,
                wasm_hash: compile_hash,
            };
            match dispatcher.dispatch(sub, params).await {
                Ok(resp) => {
                    tracing::info!(
                        pkg = %compile_pkg_id,
                        ver = %compile_version,
                        job_id = %resp.job_id,
                        backend = %resp.backend,
                        "Compilation job dispatched"
                    );
                }
                Err(e) => {
                    tracing::warn!(
                        pkg = %compile_pkg_id,
                        ver = %compile_version,
                        err = %e,
                        "Failed to dispatch compilation job"
                    );
                }
            }
        } else {
            let tmp_registry =
                ServerRegistry::new(compile_db.clone(), compile_content, compile_meta);
            match tmp_registry
                .compile_and_store_artifact(
                    &compile_pkg_id,
                    &compile_version,
                    &compile_wasm_data,
                )
                .await
            {
                Ok(platforms) => {
                    let _ = wasm_package_version::ActiveModel {
                        id: Set(version_id.clone()),
                        compilation_status: Set(WasmCompilationStatus::Compiled),
                        compiled_platforms: Set(platforms),
                        compilation_error: Set(None),
                        ..Default::default()
                    }
                    .update(&compile_db)
                    .await;
                }
                Err(e) => {
                    tracing::warn!(
                        pkg = %compile_pkg_id,
                        ver = %compile_version,
                        err = %e,
                        "AOT compilation failed"
                    );
                    let _ = wasm_package_version::ActiveModel {
                        id: Set(version_id.clone()),
                        compilation_status: Set(WasmCompilationStatus::LocalOnly),
                        compilation_error: Set(Some(e.to_string())),
                        ..Default::default()
                    }
                    .update(&compile_db)
                    .await;
                }
            }
        }

        let message = if dup_flagged {
            "Package submitted for review. Note: WASM hash matches an existing package — flagged for review.".to_string()
        } else {
            "Package submitted for review. An admin will review it shortly.".to_string()
        };

        Ok(PublishResponse {
            success: true,
            package_id: manifest.id,
            version: manifest.version,
            message: Some(message),
        })
    }

    /// Increment download count for a package (fire and forget)
    pub async fn increment_downloads(&self, package_id: &str) -> flow_like_types::Result<()> {
        // Use raw SQL for atomic increment
        sea_orm::ConnectionTrait::execute(
            &self.db,
            sea_orm::Statement::from_sql_and_values(
                sea_orm::DatabaseBackend::Postgres,
                r#"UPDATE "WasmPackage" SET "downloadCount" = "downloadCount" + 1 WHERE id = $1"#,
                [package_id.into()],
            ),
        )
        .await?;
        Ok(())
    }

    /// Get all versions for a package (unfiltered — admin/internal use)
    pub async fn get_versions(
        &self,
        package_id: &str,
    ) -> flow_like_types::Result<Vec<PackageVersion>> {
        let versions = wasm_package_version::Entity::find()
            .filter(wasm_package_version::Column::PackageId.eq(package_id))
            .order_by_desc(wasm_package_version::Column::PublishedAt)
            .all(&self.db)
            .await?;

        Ok(versions
            .into_iter()
            .map(|v| PackageVersion {
                version: v.version,
                wasm_hash: v.wasm_hash,
                wasm_size: v.wasm_size as u64,
                download_url: None,
                published_at: chrono::DateTime::from_naive_utc_and_offset(
                    v.published_at,
                    chrono::Utc,
                ),
                min_flow_like_version: v.min_flow_like_version,
                release_notes: v.release_notes,
                yanked: v.yanked,
            })
            .collect())
    }

    /// Get only approved (Active status) versions for a package
    pub async fn get_versions_approved(
        &self,
        package_id: &str,
    ) -> flow_like_types::Result<Vec<PackageVersion>> {
        use crate::entity::sea_orm_active_enums::WasmPackageStatus;

        let versions = wasm_package_version::Entity::find()
            .filter(wasm_package_version::Column::PackageId.eq(package_id))
            .filter(wasm_package_version::Column::Status.eq(WasmPackageStatus::Active))
            .order_by_desc(wasm_package_version::Column::PublishedAt)
            .all(&self.db)
            .await?;

        Ok(versions
            .into_iter()
            .map(|v| PackageVersion {
                version: v.version,
                wasm_hash: v.wasm_hash,
                wasm_size: v.wasm_size as u64,
                download_url: None,
                published_at: chrono::DateTime::from_naive_utc_and_offset(
                    v.published_at,
                    chrono::Utc,
                ),
                min_flow_like_version: v.min_flow_like_version,
                release_notes: v.release_notes,
                yanked: v.yanked,
            })
            .collect())
    }

    // ==================== ADMIN METHODS ====================

    /// List packages for admin (includes all statuses)
    pub async fn list_packages_admin(
        &self,
        status_filter: Option<&str>,
        offset: usize,
        limit: usize,
    ) -> flow_like_types::Result<(Vec<PackageDetails>, usize)> {
        let mut query = wasm_package::Entity::find();

        if let Some(status) = status_filter {
            query = query.filter(wasm_package::Column::Status.eq(status_to_enum(status)));
        }

        let total_count = query.clone().count(&self.db).await? as usize;

        let packages = query
            .order_by_desc(wasm_package::Column::CreatedAt)
            .offset(offset as u64)
            .limit(limit as u64)
            .all(&self.db)
            .await?;

        let mut details: Vec<PackageDetails> = Vec::with_capacity(packages.len());
        for pkg in packages {
            let authors = self.get_package_authors(&pkg.id).await?;
            details.push(PackageDetails {
                id: pkg.id,
                name: pkg.name,
                description: pkg.description,
                version: pkg.version,
                authors,
                license: pkg.license,
                homepage: pkg.homepage,
                repository: pkg.repository,
                keywords: pkg.keywords.unwrap_or_default(),
                status: status_to_string(&pkg.status),
                verified: pkg.verified,
                download_count: pkg.download_count as u64,
                wasm_size: pkg.wasm_size as u64,
                nodes: pkg.nodes,
                permissions: pkg.permissions,
                price: pkg.price,
                visibility: visibility_to_string(&pkg.visibility),
                created_at: chrono::DateTime::from_naive_utc_and_offset(
                    pkg.created_at,
                    chrono::Utc,
                ),
                updated_at: chrono::DateTime::from_naive_utc_and_offset(
                    pkg.updated_at,
                    chrono::Utc,
                ),
                published_at: pkg
                    .published_at
                    .map(|dt| chrono::DateTime::from_naive_utc_and_offset(dt, chrono::Utc)),
            });
        }

        Ok((details, total_count))
    }

    /// Submit a review for a package
    pub async fn submit_review(
        &self,
        package_id: &str,
        reviewer_id: &str,
        review: ReviewRequest,
    ) -> flow_like_types::Result<PackageReview> {
        use crate::entity::sea_orm_active_enums::{WasmPackageStatus, WasmReviewAction};

        let now = chrono::Utc::now().naive_utc();

        // Verify package exists
        let Some(_pkg) = wasm_package::Entity::find_by_id(package_id)
            .one(&self.db)
            .await?
        else {
            return Err(flow_like_types::anyhow!(
                "Package not found: {}",
                package_id
            ));
        };

        let action = match review.action.as_str() {
            "approve" => WasmReviewAction::Approved,
            "reject" => WasmReviewAction::Rejected,
            "request_changes" => WasmReviewAction::RequestedChanges,
            "comment" => WasmReviewAction::Commented,
            "flag" => WasmReviewAction::Flagged,
            _ => {
                return Err(flow_like_types::anyhow!(
                    "Invalid review action: {}",
                    review.action
                ));
            }
        };

        // Update package status based on action
        let new_status = match action {
            WasmReviewAction::Approved => Some(WasmPackageStatus::Active),
            WasmReviewAction::Rejected => Some(WasmPackageStatus::Rejected),
            _ => None,
        };

        if let Some(status) = new_status {
            let mut update_model = wasm_package::ActiveModel {
                id: Set(package_id.to_string()),
                status: Set(status.clone()),
                updated_at: Set(now),
                ..Default::default()
            };

            if status == WasmPackageStatus::Active {
                update_model.published_at = Set(Some(now));
                update_model.visibility = Set(WasmPackageVisibility::Public);

                // Approve all PendingReview versions and promote latest to parent
                let pending_versions = wasm_package_version::Entity::find()
                    .filter(wasm_package_version::Column::PackageId.eq(package_id))
                    .filter(
                        wasm_package_version::Column::Status
                            .eq(WasmPackageStatus::PendingReview),
                    )
                    .order_by_desc(wasm_package_version::Column::PublishedAt)
                    .all(&self.db)
                    .await?;

                for pv in &pending_versions {
                    wasm_package_version::ActiveModel {
                        id: Set(pv.id.clone()),
                        status: Set(WasmPackageStatus::Active),
                        approved_at: Set(Some(now)),
                        ..Default::default()
                    }
                    .update(&self.db)
                    .await?;
                }

                // Update parent package with latest approved version's data
                if let Some(latest) = pending_versions.first() {
                    update_model.version = Set(latest.version.clone());
                    update_model.wasm_path = Set(latest.wasm_path.clone());
                    update_model.wasm_hash = Set(latest.wasm_hash.clone());
                    update_model.wasm_size = Set(latest.wasm_size);
                }
            }

            update_model.update(&self.db).await?;
        }

        // Create review record
        let review_id = create_id();
        let review_model = wasm_package_review::ActiveModel {
            id: Set(review_id.clone()),
            package_id: Set(package_id.to_string()),
            reviewer_id: Set(reviewer_id.to_string()),
            action: Set(action),
            comment: Set(review.comment.clone()),
            internal_note: Set(review.internal_note),
            security_score: Set(review.security_score),
            code_quality_score: Set(review.code_quality_score),
            documentation_score: Set(review.documentation_score),
            created_at: Set(now),
        };
        review_model.insert(&self.db).await?;

        Ok(PackageReview {
            id: review_id,
            package_id: package_id.to_string(),
            reviewer_id: reviewer_id.to_string(),
            action: review.action,
            comment: review.comment,
            security_score: review.security_score,
            code_quality_score: review.code_quality_score,
            documentation_score: review.documentation_score,
            created_at: chrono::DateTime::from_naive_utc_and_offset(now, chrono::Utc),
        })
    }

    /// Get reviews for a package
    pub async fn get_reviews(
        &self,
        package_id: &str,
    ) -> flow_like_types::Result<Vec<PackageReview>> {
        let reviews = wasm_package_review::Entity::find()
            .filter(wasm_package_review::Column::PackageId.eq(package_id))
            .order_by_desc(wasm_package_review::Column::CreatedAt)
            .all(&self.db)
            .await?;

        Ok(reviews
            .into_iter()
            .map(|r| {
                let action_str = match r.action {
                    crate::entity::sea_orm_active_enums::WasmReviewAction::Submitted => "submitted",
                    crate::entity::sea_orm_active_enums::WasmReviewAction::Approved => "approve",
                    crate::entity::sea_orm_active_enums::WasmReviewAction::Rejected => "reject",
                    crate::entity::sea_orm_active_enums::WasmReviewAction::RequestedChanges => {
                        "request_changes"
                    }
                    crate::entity::sea_orm_active_enums::WasmReviewAction::Commented => "comment",
                    crate::entity::sea_orm_active_enums::WasmReviewAction::Flagged => "flag",
                };
                PackageReview {
                    id: r.id,
                    package_id: r.package_id,
                    reviewer_id: r.reviewer_id,
                    action: action_str.to_string(),
                    comment: r.comment,
                    security_score: r.security_score,
                    code_quality_score: r.code_quality_score,
                    documentation_score: r.documentation_score,
                    created_at: chrono::DateTime::from_naive_utc_and_offset(
                        r.created_at,
                        chrono::Utc,
                    ),
                }
            })
            .collect())
    }

    /// Update package status directly (admin)
    pub async fn update_status(
        &self,
        package_id: &str,
        status: &str,
        verified: Option<bool>,
    ) -> flow_like_types::Result<()> {
        let now = chrono::Utc::now().naive_utc();
        let new_status = status_to_enum(status);

        let mut update_model = wasm_package::ActiveModel {
            id: Set(package_id.to_string()),
            status: Set(new_status.clone()),
            updated_at: Set(now),
            ..Default::default()
        };

        if let Some(v) = verified {
            update_model.verified = Set(v);
        }

        if new_status == crate::entity::sea_orm_active_enums::WasmPackageStatus::Active {
            update_model.published_at = Set(Some(now));
        }

        update_model.update(&self.db).await?;
        Ok(())
    }

    /// Delete a package (admin)
    pub async fn delete_package(&self, package_id: &str) -> flow_like_types::Result<()> {
        let versions = wasm_package_version::Entity::find()
            .filter(wasm_package_version::Column::PackageId.eq(package_id))
            .all(&self.db)
            .await?;

        for version in versions {
            let wasm_path = Self::wasm_path(package_id, &version.version);
            let _ = self.content_bucket.as_generic().delete(&wasm_path).await;

            let compiled_base = Path::from(WASM_COMPILED_PATH)
                .child(package_id)
                .child(version.version.as_str());
            for platform in &version.compiled_platforms {
                let cwasm_path = compiled_base.child(format!("{}.cwasm", platform));
                let hash_path = compiled_base.child(format!("{}.cwasm.b3", platform));
                let _ = self.meta_bucket.as_generic().delete(&cwasm_path).await;
                let _ = self.meta_bucket.as_generic().delete(&hash_path).await;
            }
        }

        wasm_package::Entity::delete_by_id(package_id)
            .exec(&self.db)
            .await?;

        Ok(())
    }

    // ==================== AUTHOR MANAGEMENT ====================

    /// Add an author to a package
    pub async fn add_author(
        &self,
        package_id: &str,
        user_id: &str,
        role: Option<String>,
    ) -> flow_like_types::Result<AuthorInfo> {
        let now = chrono::Utc::now().naive_utc();

        // Verify package exists
        let Some(_pkg) = wasm_package::Entity::find_by_id(package_id)
            .one(&self.db)
            .await?
        else {
            return Err(flow_like_types::anyhow!(
                "Package not found: {}",
                package_id
            ));
        };

        // Verify user exists
        let Some(user_record) = user::Entity::find_by_id(user_id).one(&self.db).await? else {
            return Err(flow_like_types::anyhow!("User not found: {}", user_id));
        };

        // Check if already an author
        let existing = wasm_package_author::Entity::find()
            .filter(wasm_package_author::Column::PackageId.eq(package_id))
            .filter(wasm_package_author::Column::UserId.eq(user_id))
            .one(&self.db)
            .await?;

        if existing.is_some() {
            return Err(flow_like_types::anyhow!(
                "User is already an author of this package"
            ));
        }

        let author_model = wasm_package_author::ActiveModel {
            id: Set(create_id()),
            package_id: Set(package_id.to_string()),
            user_id: Set(user_id.to_string()),
            role: Set(role.clone()),
            added_at: Set(now),
        };
        author_model.insert(&self.db).await?;

        Ok(AuthorInfo {
            user_id: user_id.to_string(),
            username: user_record.username,
            name: user_record.name,
            avatar: user_record.avatar,
            role,
        })
    }

    /// Remove an author from a package
    pub async fn remove_author(
        &self,
        package_id: &str,
        user_id: &str,
    ) -> flow_like_types::Result<()> {
        let result = wasm_package_author::Entity::delete_many()
            .filter(wasm_package_author::Column::PackageId.eq(package_id))
            .filter(wasm_package_author::Column::UserId.eq(user_id))
            .exec(&self.db)
            .await?;

        if result.rows_affected == 0 {
            return Err(flow_like_types::anyhow!(
                "Author not found for this package"
            ));
        }

        Ok(())
    }

    /// Get packages authored by a user
    pub async fn get_user_packages(
        &self,
        user_id: &str,
    ) -> flow_like_types::Result<Vec<PackageSummary>> {
        let author_records = wasm_package_author::Entity::find()
            .filter(wasm_package_author::Column::UserId.eq(user_id))
            .all(&self.db)
            .await?;

        let package_ids: Vec<String> = author_records.into_iter().map(|a| a.package_id).collect();

        if package_ids.is_empty() {
            return Ok(Vec::new());
        }

        let packages = wasm_package::Entity::find()
            .filter(wasm_package::Column::Id.is_in(package_ids))
            .all(&self.db)
            .await?;

        Ok(packages
            .into_iter()
            .map(|pkg| {
                let vis = visibility_to_string(&pkg.visibility);
                PackageSummary {
                    id: pkg.id,
                    name: pkg.name,
                    description: pkg.description,
                    latest_version: pkg.version,
                    download_count: pkg.download_count as u64,
                    status: match pkg.status {
                        crate::entity::sea_orm_active_enums::WasmPackageStatus::Active => {
                            PackageStatus::Active
                        }
                        crate::entity::sea_orm_active_enums::WasmPackageStatus::Deprecated => {
                            PackageStatus::Deprecated
                        }
                        _ => PackageStatus::Disabled,
                    },
                    keywords: pkg.keywords.unwrap_or_default(),
                    verified: pkg.verified,
                    price: pkg.price,
                    visibility: vis,
                    metadata: None,
                }
            })
            .collect())
    }
}
