-- Aurora DSQL migration "device_schedules"
-- Generated by packages/api/scripts/dsql-migration.ts (--from-schema prisma/migrations-dsql/schema.snapshot.prisma) and rewritten by dsql-lint 0.2.17.
-- Every statement runs in its own transaction; apps/backend/aws/migration applies them one by one,
-- waits for the async index/validation jobs and records the migration in _prisma_migrations.
-- tables=1 indexes=1 foreign_keys=0 validations=0 statements=2
CREATE TABLE "DeviceScheduleClaim" (
    "appId" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "deviceId" TEXT,
    "placementId" TEXT,
    "releasedBy" TEXT,
    "releasedAt" BIGINT,
    "grantId" TEXT,
    "claimedAt" BIGINT,
    "seenAt" BIGINT,
    "resumeAt" BIGINT,

    CONSTRAINT "DeviceScheduleClaim_pkey" PRIMARY KEY ("appId","eventId")
);

CREATE INDEX ASYNC "DeviceScheduleClaim_grantId_idx" ON "DeviceScheduleClaim"("grantId");
