/* Derived from Chromium third_party/selenium-atoms/atoms.cc (GET_LOCATION) @154.0.8037.92 (Selenium c0b8ff6), Copyright 2011-2014 Software Freedom Conservancy, Apache-2.0; modified by Rheosoph GmbH. See NOTICE. */
function(){return (function(){/*

 Copyright The Closure Library Authors.
 Copyright The Closure Compiler Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var c,h=this||self;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function k(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}
function l(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var d=Object.prototype.toString.call(a);if(d=="[object Window]")return"object";if(d=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(d=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function m(a){var b=l(a);return b=="array"||b=="object"&&typeof a.length=="number"};var p;function r(a,b){for(var d=a.length,e=typeof a==="string"?a.split(""):a,g=0;g<d;g++)g in e&&b.call(void 0,e[g],g,a)}function t(a){var b=a.length;if(b>0){for(var d=Array(b),e=0;e<b;e++)d[e]=a[e];return d}return[]};function u(a,b){this.x=a!==void 0?a:0;this.y=b!==void 0?b:0}c=u.prototype;c.clone=function(){return new u(this.x,this.y)};c.equals=function(a){return a instanceof u&&(this==a?!0:this&&a?this.x==a.x&&this.y==a.y:!1)};c.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};c.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};c.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
c.translate=function(a,b){a instanceof u?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),typeof b==="number"&&(this.y+=b));return this};c.scale=function(a,b){this.x*=a;this.y*=typeof b==="number"?b:a;return this};function v(a,b,d){function e(n){n&&b.appendChild(typeof n==="string"?a.createTextNode(n):n)}for(var g=1;g<d.length;g++){var f=d[g];if(!m(f)||k(f)&&f.nodeType>0)e(f);else{a:{if(f&&typeof f.length=="number"){if(k(f)){var q=typeof f.item=="function"||typeof f.item=="string";break a}if(typeof f==="function"){q=typeof f.item=="function";break a}}q=!1}r(q?t(f):f,e)}}}function w(a){return a.nodeType==9?a:a.ownerDocument||a.document}function x(a){this.g=a||h.document||document}c=x.prototype;
c.getElementsByTagName=function(a,b){return(b||this.g).getElementsByTagName(String(a))};c.createElement=function(a){var b=this.g;a=String(a);b.contentType==="application/xhtml+xml"&&(a=a.toLowerCase());return b.createElement(a)};c.createTextNode=function(a){return this.g.createTextNode(String(a))};c.appendChild=function(a,b){a.appendChild(b)};c.append=function(a,b){v(w(a),a,arguments)};c.canHaveChildren=function(a){if(a.nodeType!=1)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
c.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};c.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function y(a){var b=w(a),d=new u(0,0);if(a==(b?w(b):document).documentElement)return d;try{var e=a.getBoundingClientRect()}catch(g){e={left:0,top:0,right:0,bottom:0}}b=(b?new x(w(b)):p||(p=new x)).g;a=b.scrollingElement?b.scrollingElement:b.body||b.documentElement;b=b.parentWindow||b.defaultView;a=new u(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop);d.x=e.left+a.x;d.y=e.top+a.y;return d}var z=["se_exportedFunctionSymbol"],A=h;
z[0]in A||typeof A.execScript=="undefined"||A.execScript("var "+z[0]);for(var B;z.length&&(B=z.shift());)z.length||y===void 0?A=A[B]&&A[B]!==Object.prototype[B]?A[B]:A[B]={}:A[B]=y;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
