/* Derived from Chromium third_party/selenium-atoms/atoms.cc (GET_LOCATION_IN_VIEW) @154.0.8037.92 (Selenium c0b8ff6), Copyright 2011-2014 Software Freedom Conservancy, Apache-2.0; modified by Rheosoph GmbH. See NOTICE. */
function(){return (function(){/*

 Copyright The Closure Library Authors.
 Copyright The Closure Compiler Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var e,m=this||self;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function q(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}
function r(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function v(a){var b=r(a);return b=="array"||b=="object"&&typeof a.length=="number"};var x;function y(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,g=0;g<c;g++)g in d&&b.call(void 0,d[g],g,a)}function z(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function A(a){return B().indexOf(a)!=-1};function B(){var a=m.navigator;return a&&(a=a.userAgent)?a:""};function C(a){return(a=a.exec(B()))?a[1]:""}(A("iPhone")&&!A("iPod")&&!A("iPad")||A("iPad")||A("iPod")||A("Macintosh"))&&C(/CriOS\/([0-9.]+)/)||C(/Chrome\/([0-9.]+)/);function D(a,b){this.x=a!==void 0?a:0;this.y=b!==void 0?b:0}e=D.prototype;e.clone=function(){return new D(this.x,this.y)};e.equals=function(a){return a instanceof D&&(this==a?!0:this&&a?this.x==a.x&&this.y==a.y:!1)};e.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};e.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};e.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
e.translate=function(a,b){a instanceof D?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),typeof b==="number"&&(this.y+=b));return this};e.scale=function(a,b){this.x*=a;this.y*=typeof b==="number"?b:a;return this};function E(a,b){this.width=a;this.height=b}e=E.prototype;e.clone=function(){return new E(this.width,this.height)};e.aspectRatio=function(){return this.width/this.height};e.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};e.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};e.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
e.scale=function(a,b){this.width*=a;this.height*=typeof b==="number"?b:a;return this};function G(a,b,c){function d(l){l&&b.appendChild(typeof l==="string"?a.createTextNode(l):l)}for(var g=1;g<c.length;g++){var f=c[g];if(!v(f)||q(f)&&f.nodeType>0)d(f);else{a:{if(f&&typeof f.length=="number"){if(q(f)){var h=typeof f.item=="function"||typeof f.item=="string";break a}if(typeof f==="function"){h=typeof f.item=="function";break a}}h=!1}y(h?z(f):f,d)}}}function H(a){return a.nodeType==9?a:a.ownerDocument||a.document}function I(a){this.g=a||m.document||document}e=I.prototype;
e.getElementsByTagName=function(a,b){return(b||this.g).getElementsByTagName(String(a))};function J(a){a=a.g;a=(a.parentWindow||a.defaultView||window).document;a=a.compatMode=="CSS1Compat"?a.documentElement:a.body;return new E(a.clientWidth,a.clientHeight)}e.createElement=function(a){var b=this.g;a=String(a);b.contentType==="application/xhtml+xml"&&(a=a.toLowerCase());return b.createElement(a)};e.createTextNode=function(a){return this.g.createTextNode(String(a))};e.appendChild=function(a,b){a.appendChild(b)};
e.append=function(a,b){G(H(a),a,arguments)};e.canHaveChildren=function(a){if(a.nodeType!=1)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
e.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};e.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function K(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}e=K.prototype;e.clone=function(){return new K(this.top,this.right,this.bottom,this.left)};e.contains=function(a){return this&&a?a instanceof K?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
e.expand=function(a,b,c,d){q(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=Number(b),this.bottom+=Number(c),this.left-=Number(d));return this};e.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
e.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};e.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
e.translate=function(a,b){a instanceof D?(this.left+=a.x,this.right+=a.x,this.top+=a.y,this.bottom+=a.y):(this.left+=a,this.right+=a,typeof b==="number"&&(this.top+=b,this.bottom+=b));return this};e.scale=function(a,b){b=typeof b==="number"?b:a;this.left*=a;this.right*=a;this.top*=b;this.bottom*=b;return this};function L(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}e=L.prototype;e.clone=function(){return new L(this.left,this.top,this.width,this.height)};e.intersection=function(a){var b=Math.max(this.left,a.left),c=Math.min(this.left+this.width,a.left+a.width);if(b<=c){var d=Math.max(this.top,a.top);a=Math.min(this.top+this.height,a.top+a.height);if(d<=a)return this.left=b,this.top=d,this.width=c-b,this.height=a-d,!0}return!1};
e.difference=function(a){b:{var b=Math.max(this.left,a.left);var c=Math.min(this.left+this.width,a.left+a.width);if(b<=c){var d=Math.max(this.top,a.top),g=Math.min(this.top+this.height,a.top+a.height);if(d<=g){b=new L(b,d,c-b,g-d);break b}}b=null}if(b&&b.height&&b.width){b=[];c=this.top;d=this.height;g=this.left+this.width;var f=this.top+this.height,h=a.left+a.width,l=a.top+a.height;a.top>this.top&&(b.push(new L(this.left,this.top,this.width,a.top-this.top)),c=a.top,d-=a.top-this.top);l<f&&(b.push(new L(this.left,
l,this.width,f-l)),d=l-c);a.left>this.left&&b.push(new L(this.left,c,a.left-this.left,d));h<g&&b.push(new L(h,c,g-h,d));a=b}else a=[this.clone()];return a};e.contains=function(a){return a instanceof D?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};e.getSize=function(){return new E(this.width,this.height)};
e.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};e.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};e.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
e.translate=function(a,b){a instanceof D?(this.left+=a.x,this.top+=a.y):(this.left+=a,typeof b==="number"&&(this.top+=b));return this};e.scale=function(a,b){b=typeof b==="number"?b:a;this.left*=a;this.width*=a;this.top*=b;this.height*=b;return this};function M(a,b){var c=H(a);return c.defaultView&&c.defaultView.getComputedStyle&&(a=c.defaultView.getComputedStyle(a,null))?a[b]||a.getPropertyValue(b)||"":""}function O(a){try{return a.getBoundingClientRect()}catch(b){return{left:0,top:0,right:0,bottom:0}}}
function P(a){var b=H(a),c=new D(0,0);if(a==(b?H(b):document).documentElement)return c;a=O(a);var d=(b?new I(H(b)):x||(x=new I)).g;b=d.scrollingElement?d.scrollingElement:d.body||d.documentElement;d=d.parentWindow||d.defaultView;b=new D(d.pageXOffset||b.scrollLeft,d.pageYOffset||b.scrollTop);c.x=a.left+b.x;c.y=a.top+b.y;return c}function Q(a){if(a.nodeType==1)return a=O(a),new D(a.left,a.top);a=a.changedTouches?a.changedTouches[0]:a;return new D(a.clientX,a.clientY)};var R=typeof ShadowRoot==="function";function S(a,b){b=P(b);var c=P(a);b=new D(b.x-c.x,b.y-c.y);var d=M(a,"borderLeftWidth");var g=M(a,"borderRightWidth");c=M(a,"borderTopWidth");a=M(a,"borderBottomWidth");a=new K(parseFloat(c),parseFloat(g),parseFloat(a),parseFloat(d));b.x-=a.left;b.y-=a.top;return b}
function T(a,b,c){function d(w,p,t,n,F){var u=n=new L(t.x+n.left,t.y+n.top,n.width,n.height);t=[0,0];p=[p.width,p.height];n=[u.left,u.top];u=[u.width,u.height];for(var k=0;k<2;k++)if(u[k]>p[k])t[k]=F?n[k]+u[k]/2-p[k]/2:n[k];else{var N=n[k]-p[k]+u[k];N>0?t[k]=N:n[k]<0&&(t[k]=n[k])}F=new D(t[0],t[1]);w.scrollLeft+=F.x;w.scrollTop+=F.y}function g(w){var p=w.parentNode;R&&p instanceof ShadowRoot&&(p=w.host);return p}for(var f=H(a),h=g(a),l;h&&h!=f.documentElement&&h!=f.body;)l=S(h,a),d(h,new E(h.clientWidth,
h.clientHeight),l,b,c),h=g(h);l=Q(a);a=J(a?new I(H(a)):x||(x=new I));d(f.documentElement,a,l,b,c);f.body&&d(f.body,a,l,b,c)};function U(a,b,c){c||(c=new L(0,0,a.offsetWidth,a.offsetHeight));a!=a.ownerDocument.documentElement&&T(a,c,b);a=Q(a);return new D(a.x+c.left,a.y+c.top)}var V=["se_exportedFunctionSymbol"],W=m;V[0]in W||typeof W.execScript=="undefined"||W.execScript("var "+V[0]);for(var X;V.length&&(X=V.shift());)V.length||U===void 0?W=W[X]&&W[X]!==Object.prototype[X]?W[X]:W[X]={}:W[X]=U;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
