/* Derived from Chromium third_party/selenium-atoms/atoms.cc (IS_DISPLAYED) @154.0.8037.92 (Selenium c0b8ff6), Copyright 2011-2014 Software Freedom Conservancy, Apache-2.0; modified by Rheosoph GmbH. See NOTICE. */
function(){return (function(){/*

 Copyright The Closure Library Authors.
 Copyright The Closure Compiler Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var g,l=l||{},p=this||self;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function q(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}
function ba(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ca(a){var b=ba(a);return b=="array"||b=="object"&&typeof a.length=="number"};function da(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function ea(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function fa(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}function ha(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var ia={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var t="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),ja=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,ka=/^#(?:[0-9a-f]{3}){1,2}$/i,la=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,ma=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function v(a,b){this.code=a;this.state=w[a]||y;this.message=b||"";a=this.state.replace(/((?:^|\s+)[a-z])/g,function(c){return c.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(b<0||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}(function(){function a(){}a.prototype=Error.prototype;v.prototype=new a;v.prototype.constructor=v})();var y="unknown error",w={15:"element not selectable",11:"element not visible"};w[31]=y;w[30]=y;
w[24]="invalid cookie domain";w[29]="invalid element coordinates";w[12]="invalid element state";w[32]="invalid selector";w[51]="invalid selector";w[52]="invalid selector";w[17]="javascript error";w[405]="unsupported operation";w[34]="move target out of bounds";w[27]="no such alert";w[7]="no such element";w[8]="no such frame";w[23]="no such window";w[28]="script timeout";w[33]="session not created";w[10]="stale element reference";w[21]="timeout";w[25]="unable to set cookie";w[26]="unexpected alert open";
w[13]=y;w[9]="unknown command";var na=l.h&&String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function A(a){return B().indexOf(a)!=-1};function B(){var a=p.navigator;return a&&(a=a.userAgent)?a:""};function oa(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})};function C(a){return(a=a.exec(B()))?a[1]:""}(A("iPhone")&&!A("iPod")&&!A("iPad")||A("iPad")||A("iPod")||A("Macintosh"))&&C(/CriOS\/([0-9.]+)/)||C(/Chrome\/([0-9.]+)/);function D(a,b){this.x=a!==void 0?a:0;this.y=b!==void 0?b:0}g=D.prototype;g.clone=function(){return new D(this.x,this.y)};g.equals=function(a){return a instanceof D&&(this==a?!0:this&&a?this.x==a.x&&this.y==a.y:!1)};g.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};g.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};g.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.translate=function(a,b){a instanceof D?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),typeof b==="number"&&(this.y+=b));return this};g.scale=function(a,b){this.x*=a;this.y*=typeof b==="number"?b:a;return this};function E(a,b){this.width=a;this.height=b}g=E.prototype;g.clone=function(){return new E(this.width,this.height)};g.aspectRatio=function(){return this.width/this.height};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.scale=function(a,b){this.width*=a;this.height*=typeof b==="number"?b:a;return this};function pa(a,b,c){function d(k){k&&b.appendChild(typeof k==="string"?a.createTextNode(k):k)}for(var e=1;e<c.length;e++){var f=c[e];if(!ca(f)||q(f)&&f.nodeType>0)d(f);else{a:{if(f&&typeof f.length=="number"){if(q(f)){var h=typeof f.item=="function"||typeof f.item=="string";break a}if(typeof f==="function"){h=typeof f.item=="function";break a}}h=!1}da(h?ha(f):f,d)}}}function F(a){return a.nodeType==9?a:a.ownerDocument||a.document}
function qa(a,b){a&&(a=a.parentNode);for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function G(a){this.g=a||p.document||document}g=G.prototype;g.getElementsByTagName=function(a,b){return(b||this.g).getElementsByTagName(String(a))};g.createElement=function(a){var b=this.g;a=String(a);b.contentType==="application/xhtml+xml"&&(a=a.toLowerCase());return b.createElement(a)};g.createTextNode=function(a){return this.g.createTextNode(String(a))};g.appendChild=function(a,b){a.appendChild(b)};
g.append=function(a,b){pa(F(a),a,arguments)};g.canHaveChildren=function(a){if(a.nodeType!=1)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};g.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function H(a,b){b&&typeof b!=="string"&&(b=b.toString());return a instanceof HTMLFormElement?!!a&&a.nodeType==1&&(!b||"FORM"==b):!!a&&a.nodeType==1&&(!b||a.tagName.toUpperCase()==b)};function I(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}g=I.prototype;g.clone=function(){return new I(this.top,this.right,this.bottom,this.left)};g.contains=function(a){return this&&a?a instanceof I?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
g.expand=function(a,b,c,d){q(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=Number(b),this.bottom+=Number(c),this.left-=Number(d));return this};g.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};g.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.translate=function(a,b){a instanceof D?(this.left+=a.x,this.right+=a.x,this.top+=a.y,this.bottom+=a.y):(this.left+=a,this.right+=a,typeof b==="number"&&(this.top+=b,this.bottom+=b));return this};g.scale=function(a,b){b=typeof b==="number"?b:a;this.left*=a;this.right*=a;this.top*=b;this.bottom*=b;return this};function J(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}g=J.prototype;g.clone=function(){return new J(this.left,this.top,this.width,this.height)};g.intersection=function(a){var b=Math.max(this.left,a.left),c=Math.min(this.left+this.width,a.left+a.width);if(b<=c){var d=Math.max(this.top,a.top);a=Math.min(this.top+this.height,a.top+a.height);if(d<=a)return this.left=b,this.top=d,this.width=c-b,this.height=a-d,!0}return!1};
g.difference=function(a){b:{var b=Math.max(this.left,a.left);var c=Math.min(this.left+this.width,a.left+a.width);if(b<=c){var d=Math.max(this.top,a.top),e=Math.min(this.top+this.height,a.top+a.height);if(d<=e){b=new J(b,d,c-b,e-d);break b}}b=null}if(b&&b.height&&b.width){b=[];c=this.top;d=this.height;e=this.left+this.width;var f=this.top+this.height,h=a.left+a.width,k=a.top+a.height;a.top>this.top&&(b.push(new J(this.left,this.top,this.width,a.top-this.top)),c=a.top,d-=a.top-this.top);k<f&&(b.push(new J(this.left,
k,this.width,f-k)),d=k-c);a.left>this.left&&b.push(new J(this.left,c,a.left-this.left,d));h<e&&b.push(new J(h,c,e-h,d));a=b}else a=[this.clone()];return a};g.contains=function(a){return a instanceof D?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};g.getSize=function(){return new E(this.width,this.height)};
g.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};g.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.translate=function(a,b){a instanceof D?(this.left+=a.x,this.top+=a.y):(this.left+=a,typeof b==="number"&&(this.top+=b));return this};g.scale=function(a,b){b=typeof b==="number"?b:a;this.left*=a;this.width*=a;this.top*=b;this.height*=b;return this};var ra=typeof ShadowRoot==="function";function K(a){for(a=a.parentNode;a&&a.nodeType!=1&&a.nodeType!=9&&a.nodeType!=11;)a=a.parentNode;return H(a)?a:null}
function M(a,b){b=oa(b);if(b=="float"||b=="cssFloat"||b=="styleFloat")b="cssFloat";a:{var c=b;var d=F(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,null))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}a=c||N(a,b);if(a===null)a=null;else{b:if(typeof t==="string")b=typeof b!=="string"||b.length!=1?-1:t.indexOf(b,0);else{for(c=0;c<t.length;c++)if(c in t&&t[c]===b){b=c;break b}b=-1}if(b>=0){b:{var e=a.match(la);if(e&&(b=Number(e[1]),c=Number(e[2]),d=Number(e[3]),
e=Number(e[4]),b>=0&&b<=255&&c>=0&&c<=255&&d>=0&&d<=255&&e>=0&&e<=1)){b=[b,c,d,e];break b}b=null}if(!b)b:{if(d=a.match(ma))if(b=Number(d[1]),c=Number(d[2]),d=Number(d[3]),b>=0&&b<=255&&c>=0&&c<=255&&d>=0&&d<=255){b=[b,c,d,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=ia[b.toLowerCase()];if(!c&&(c=b.charAt(0)=="#"?b:"#"+b,c.length==4&&(c=c.replace(ja,"#$1$1$2$2$3$3")),!ka.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+
")":a}}return a}function N(a,b){var c=a.currentStyle||a.style,d=c[b];d===void 0&&typeof c.getPropertyValue==="function"&&(d=c.getPropertyValue(b));return d!="inherit"?d!==void 0?d:null:(a=K(a))?N(a,b):null}
function O(a,b,c){function d(h){var k=P(h);if(k.height>0&&k.width>0)return!0;if(H(h,"PATH")&&(k.height>0||k.width>0))return h=M(h,"stroke-width"),!!h&&parseInt(h,10)>0;k=M(h,"visibility");return k!="collapse"&&k!="hidden"&&c(h)?M(h,"overflow")!="hidden"&&ea(h.childNodes,function(x){return x.nodeType==3?(x=x.nodeValue,/^[\s]*$/.test(x)&&/[\n\r\t]/.test(x)?!1:!0):H(x)&&d(x)}):!1}function e(h){return R(h)==S&&fa(h.childNodes,function(k){return!H(k)||e(k)||!d(k)})}if(!H(a))throw Error("Argument to isShown must be of type Element");
if(H(a,"BODY"))return!0;if(H(a,"OPTION")||H(a,"OPTGROUP"))return a=qa(a,function(h){return H(h,"SELECT")}),!!a&&O(a,!0,c);var f=T(a);if(f)return!!f.image&&f.rect.width>0&&f.rect.height>0&&O(f.image,b,c);if(H(a,"INPUT")&&a.type.toLowerCase()=="hidden"||H(a,"NOSCRIPT"))return!1;f=M(a,"visibility");return f!="collapse"&&f!="hidden"&&c(a)&&(b||U(a)!=0)&&d(a)?!e(a):!1}var S="hidden";
function R(a){function b(m){function n(Q){if(Q==h)return!0;var Y=M(Q,"display");return Y.lastIndexOf("inline",0)==0||Y=="contents"||Z=="absolute"&&M(Q,"position")=="static"?!1:!0}var Z=M(m,"position");if(Z=="fixed")return aa=!0,m==h?null:h;for(m=K(m);m&&!n(m);)m=K(m);return m}function c(m){var n=m;if(x=="visible")if(m==h&&k)n=k;else if(m==k)return{x:"visible",y:"visible"};n={x:M(n,"overflow-x"),y:M(n,"overflow-y")};m==h&&(n.x=n.x=="visible"?"auto":n.x,n.y=n.y=="visible"?"auto":n.y);return n}function d(m){if(m==
h){var n=(new G(f)).g;m=n.scrollingElement?n.scrollingElement:n.body||n.documentElement;n=n.parentWindow||n.defaultView;m=new D(n.pageXOffset||m.scrollLeft,n.pageYOffset||m.scrollTop)}else m=new D(m.scrollLeft,m.scrollTop);return m}var e=sa(a),f=F(a),h=f.documentElement,k=f.body,x=M(h,"overflow"),aa;for(a=b(a);a;a=b(a)){var r=c(a);if(r.x!="visible"||r.y!="visible"){var u=P(a);if(u.width==0||u.height==0)return S;var z=e.right<u.left,L=e.bottom<u.top;if(z&&r.x=="hidden"||L&&r.y=="hidden")return S;if(z&&
r.x!="visible"||L&&r.y!="visible"){z=d(a);L=e.bottom<u.top-z.y;if(e.right<u.left-z.x&&r.x!="visible"||L&&r.x!="visible")return S;e=R(a);return e==S?S:"scroll"}z=e.left>=u.left+u.width;u=e.top>=u.top+u.height;if(z&&r.x=="hidden"||u&&r.y=="hidden")return S;if(z&&r.x!="visible"||u&&r.y!="visible"){if(aa&&(r=d(a),e.left>=h.scrollWidth-r.x||e.right>=h.scrollHeight-r.y))return S;e=R(a);return e==S?S:"scroll"}}}return"none"}
function P(a){var b=T(a);if(b)return b.rect;if(H(a,"HTML"))return a=F(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a=a.compatMode=="CSS1Compat"?a.documentElement:a.body,a=new E(a.clientWidth,a.clientHeight),new J(0,0,a.width,a.height);try{var c=a.getBoundingClientRect()}catch(d){return new J(0,0,0,0)}return new J(c.left,c.top,c.right-c.left,c.bottom-c.top)}
function T(a){var b=H(a,"MAP");if(!b&&!H(a,"AREA"))return null;var c=b?a:H(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;if(c&&c.name){d='*[usemap="#'+c.name+'"]';c=F(c);if(!d)throw new v(32,"No selector specified");d=na(d);try{var f=c.querySelector(d)}catch(h){throw new v(32,"An invalid or illegal selector was specified");}if(d=f&&f.nodeType==1?f:null)e=P(d),b||a.shape.toLowerCase()=="default"||(a=ta(a),b=Math.min(Math.max(a.left,0),e.width),f=Math.min(Math.max(a.top,0),e.height),e=new J(b+
e.left,f+e.top,Math.min(a.width,e.width-b),Math.min(a.height,e.height-f)))}return{image:d,rect:e||new J(0,0,0,0)}}
function ta(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if(b=="rect"&&a.length==4){b=a[0];var c=a[1];return new J(b,c,a[2]-b,a[3]-c)}if(b=="circle"&&a.length==3)return b=a[2],new J(a[0]-b,a[1]-b,2*b,2*b);if(b=="poly"&&a.length>2){b=a[0];c=a[1];for(var d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new J(b,c,d-b,e-c)}return new J(0,0,0,0)}function sa(a){a=P(a);return new I(a.top,a.left+a.width,a.top+a.height,a.left)}
function U(a){var b=1,c=M(a,"opacity");c&&(b=Number(c));(a=K(a))&&(b*=U(a));return b};function ua(a,b){function c(d){if(H(d)&&(M(d,"display")=="none"||M(d,"content-visibility")=="hidden"))return!1;a:{var e=d.parentNode;if(d.getDestinationInsertionPoints){var f=d.getDestinationInsertionPoints();if(f.length>0){e=f[f.length-1];break a}}e=e&&e.shadowRoot&&d.assignedSlot!==void 0?d.assignedSlot?d.assignedSlot.parentNode:null:e}return ra&&e instanceof ShadowRoot||e&&(e.nodeType==9||e.nodeType==11)?!0:e&&H(e,"DETAILS")&&!e.open&&!H(d,"SUMMARY")?!1:!!e&&c(e)}return O(a,!!b,c)}
var V=["se_exportedFunctionSymbol"],W=p;V[0]in W||typeof W.execScript=="undefined"||W.execScript("var "+V[0]);for(var X;V.length&&(X=V.shift());)V.length||ua===void 0?W=W[X]&&W[X]!==Object.prototype[X]?W[X]:W[X]={}:W[X]=ua;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
