/* Derived from Chromium third_party/selenium-atoms/atoms.cc (IS_SELECTED) @154.0.8037.92 (Selenium c0b8ff6), Copyright 2011-2014 Software Freedom Conservancy, Apache-2.0; modified by Rheosoph GmbH. See NOTICE. */
function(){return (function(){/*

 Copyright The Closure Library Authors.
 Copyright The Closure Compiler Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var c,aa=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},g=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");}var ca=ba(this);function h(a,b){if(b)a:{var d=ca;a=a.split(".");for(var e=0;e<a.length-1;e++){var f=a[e];if(!(f in d))break a;d=d[f]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&b!=null&&g(d,a,{configurable:!0,writable:!0,value:b})}}var l;
if(typeof Object.setPrototypeOf=="function")l=Object.setPrototypeOf;else{var m;a:{var da={a:!0},n={};try{n.__proto__=da;m=n.a;break a}catch(a){}m=!1}l=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var p=l;
function q(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(p)p(a,b);else for(var d in b)if(d!="prototype")if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d];a.G=b.prototype}function ea(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
h("Symbol",function(a){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new d(e+(k||"")+"_"+f++,k)}function d(k,x){this.C=k;g(this,"description",{configurable:!0,writable:!0,value:x})}if(a)return a;d.prototype.toString=function(){return this.C};var e="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",f=0;return b});
h("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");g(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(ea(this))}});return a});function fa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}function ha(a,b){a instanceof String&&(a+="");var d=0,e=!1,f={next:function(){if(!e&&d<a.length){var k=d++;return{value:b(k,a[k]),done:!1}}e=!0;return{done:!0,value:void 0}}};f[Symbol.iterator]=function(){return f};return f}
h("Array.prototype.keys",function(a){return a?a:function(){return ha(this,function(b){return b})}});var r=this||self;try{var t=window}catch(a){t=r};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function u(a,b){function d(){}d.prototype=b.prototype;a.G=b.prototype;a.prototype=new d;a.prototype.constructor=a;a.H=function(e,f,k){for(var x=Array(arguments.length-2),z=2;z<arguments.length;z++)x[z-2]=arguments[z];return b.prototype[f].apply(e,x)}};function v(a,b){this.code=a;this.state=w[a]||y;this.message=b||"";a=this.state.replace(/((?:^|\s+)[a-z])/g,function(d){return d.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(b<0||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}u(v,Error);var y="unknown error",w={15:"element not selectable",11:"element not visible"};w[31]=y;w[30]=y;w[24]="invalid cookie domain";w[29]="invalid element coordinates";w[12]="invalid element state";
w[32]="invalid selector";w[51]="invalid selector";w[52]="invalid selector";w[17]="javascript error";w[405]="unsupported operation";w[34]="move target out of bounds";w[27]="no such alert";w[7]="no such element";w[8]="no such frame";w[23]="no such window";w[28]="script timeout";w[33]="session not created";w[10]="stale element reference";w[21]="timeout";w[25]="unable to set cookie";w[26]="unexpected alert open";w[13]=y;w[9]="unknown command";function ia(a,b){for(var d=a.length,e=typeof a==="string"?a.split(""):a,f=0;f<d;f++)f in e&&b.call(void 0,e[f],f,a)};function A(a){return B().indexOf(a)!=-1};function B(){var a=r.navigator;return a&&(a=a.userAgent)?a:""};var C=A("Macintosh"),D=A("Windows");function E(a){return(a=a.exec(B()))?a[1]:""}(A("iPhone")&&!A("iPod")&&!A("iPad")||A("iPad")||A("iPod")||A("Macintosh"))&&E(/CriOS\/([0-9.]+)/)||E(/Chrome\/([0-9.]+)/);function ja(a,b){a&&(a=a.parentNode);for(var d=0;a&&!b(a);)a=a.parentNode,d++};function F(a,b){b&&typeof b!=="string"&&(b=b.toString());return a instanceof HTMLFormElement?!!a&&a.nodeType==1&&(!b||"FORM"==b):!!a&&a.nodeType==1&&(!b||a.tagName.toUpperCase()==b)}function G(a){return F(a,"OPTION")?!0:F(a,"INPUT")?(a=a.type.toLowerCase(),a=="checkbox"||a=="radio"):!1};function H(){this.B=t.document.documentElement;var a=this.B;a=a.nodeType==9?a:a.ownerDocument||a.document;try{var b=a&&a.activeElement;var d=b&&b.nodeName?b:null}catch(e){d=null}d&&ka(this,d)}function ka(a,b){a.B=b;F(b,"OPTION")&&ja(b,function(d){return F(d,"SELECT")})};function I(a,b){this.D=a[r.Symbol.iterator]();this.F=b}I.prototype[Symbol.iterator]=function(){return this};I.prototype.next=function(){var a=this.D.next();return{value:a.done?void 0:this.F.call(void 0,a.value),done:a.done}};function la(a,b){return new I(a,b)};function J(){}J.prototype.next=function(){return K};var K={done:!0,value:void 0};J.prototype.l=function(){return this};function L(a){if(a instanceof M||a instanceof N||a instanceof O)return a;if(typeof a.next=="function")return new M(function(){return a});if(typeof a[Symbol.iterator]=="function")return new M(function(){return a[Symbol.iterator]()});if(typeof a.l=="function")return new M(function(){return a.l()});throw Error("Not an iterator or iterable.");}function M(a){this.u=a}M.prototype.l=function(){return new N(this.u())};M.prototype[Symbol.iterator]=function(){return new O(this.u())};M.prototype.A=function(){return new O(this.u())};
function N(a){this.m=a}q(N,J);N.prototype.next=function(){return this.m.next()};N.prototype[Symbol.iterator]=function(){return new O(this.m)};N.prototype.A=function(){return new O(this.m)};function O(a){M.call(this,function(){return a});this.m=a}q(O,M);O.prototype.next=function(){return this.m.next()};function P(a,b){this.j={};this.i=[];this.o=this.size=0;var d=arguments.length;if(d>1){if(d%2)throw Error("Uneven number of arguments");for(var e=0;e<d;e+=2)this.set(arguments[e],arguments[e+1])}else a&&this.addAll(a)}function Q(a){R(a);return a.i.concat()}c=P.prototype;c.has=function(a){return S(this.j,a)};c.equals=function(a,b){if(this===a)return!0;if(this.size!=a.size)return!1;b=b||ma;R(this);for(var d,e=0;d=this.i[e];e++)if(!b(this.get(d),a.get(d)))return!1;return!0};
function ma(a,b){return a===b}c.clear=function(){this.j={};this.o=this.size=this.i.length=0};c.remove=function(a){return this.delete(a)};c.delete=function(a){return S(this.j,a)?(delete this.j[a],--this.size,this.o++,this.i.length>2*this.size&&R(this),!0):!1};function R(a){if(a.size!=a.i.length){for(var b=0,d=0;b<a.i.length;){var e=a.i[b];S(a.j,e)&&(a.i[d++]=e);b++}a.i.length=d}if(a.size!=a.i.length){var f={};for(d=b=0;b<a.i.length;)e=a.i[b],S(f,e)||(a.i[d++]=e,f[e]=1),b++;a.i.length=d}}
c.get=function(a,b){return S(this.j,a)?this.j[a]:b};c.set=function(a,b){S(this.j,a)||(this.size+=1,this.i.push(a),this.o++);this.j[a]=b};c.addAll=function(a){if(a instanceof P)for(var b=Q(a),d=0;d<b.length;d++)this.set(b[d],a.get(b[d]));else for(b in a)this.set(b,a[b])};c.forEach=function(a,b){for(var d=Q(this),e=0;e<d.length;e++){var f=d[e],k=this.get(f);a.call(b,k,f,this)}};c.clone=function(){return new P(this)};c.keys=function(){return L(this.l(!0)).A()};c.values=function(){return L(this.l(!1)).A()};
c.entries=function(){var a=this;return la(this.keys(),function(b){return[b,a.get(b)]})};c.l=function(a){R(this);var b=0,d=this.o,e=this,f=new J;f.next=function(){if(d!=e.o)throw Error("The map has changed since the iterator was created");if(b>=e.i.length)return K;var k=e.i[b++];return{value:a?k:e.j[k],done:!1}};return f};function S(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var T={};function U(a,b,d){var e=typeof a;(e=="object"&&a!=null||e=="function")&&(a=a.g);a=new na(a);!b||b in T&&!d||(T[b]={key:a,shift:!1},d&&(T[d]={key:a,shift:!0}));return a}function na(a){this.code=a}U(8);U(9);U(13);var oa=U(16),pa=U(17),qa=U(18);U(19);U(20);U(27);U(32," ");U(33);U(34);U(35);U(36);U(37);U(38);U(39);U(40);U(44);U(45);U(46);U(48,"0",")");U(49,"1","!");U(50,"2","@");U(51,"3","#");U(52,"4","$");U(53,"5","%");U(54,"6","^");U(55,"7","&");U(56,"8","*");U(57,"9","(");U(65,"a","A");
U(66,"b","B");U(67,"c","C");U(68,"d","D");U(69,"e","E");U(70,"f","F");U(71,"g","G");U(72,"h","H");U(73,"i","I");U(74,"j","J");U(75,"k","K");U(76,"l","L");U(77,"m","M");U(78,"n","N");U(79,"o","O");U(80,"p","P");U(81,"q","Q");U(82,"r","R");U(83,"s","S");U(84,"t","T");U(85,"u","U");U(86,"v","V");U(87,"w","W");U(88,"x","X");U(89,"y","Y");U(90,"z","Z");var ra=U(D?{h:91,g:91}:C?{h:224,g:91}:{h:0,g:91});U(D?{h:92,g:92}:C?{h:224,g:93}:{h:0,g:92});U(D?{h:93,g:93}:C?{h:0,g:0}:{h:93,g:null});U({h:96,g:96},"0");
U({h:97,g:97},"1");U({h:98,g:98},"2");U({h:99,g:99},"3");U({h:100,g:100},"4");U({h:101,g:101},"5");U({h:102,g:102},"6");U({h:103,g:103},"7");U({h:104,g:104},"8");U({h:105,g:105},"9");U({h:106,g:106},"*");U({h:107,g:107},"+");U({h:109,g:109},"-");U({h:110,g:110},".");U({h:111,g:111},"/");U(144);U(112);U(113);U(114);U(115);U(116);U(117);U(118);U(119);U(120);U(121);U(122);U(123);U({h:107,g:187},"=","+");U(108,",");U({h:109,g:189},"-","_");U(188,",","<");U(190,".",">");U(191,"/","?");U(192,"`","~");
U(219,"[","{");U(220,"\\","|");U(221,"]","}");U({h:59,g:186},";",":");U(222,"'",'"');var V=new P;V.set(1,oa);V.set(2,pa);V.set(4,qa);V.set(8,ra);(function(a){var b=new P;ia(Q(a),function(d){b.set(a.get(d).code,d)});return b})(V);function W(){H.call(this)}u(W,H);(function(a){a.v=void 0;a.I=function(){return a.v?a.v:a.v=new a}})(W);function sa(a){if(G(a)){if(!G(a))throw new v(15,"Element is not selectable");var b="selected",d=a.type&&a.type.toLowerCase();if("checkbox"==d||"radio"==d)b="checked";a=!!a[b]}else a=!1;return a}var X=["se_exportedFunctionSymbol"],Y=r;X[0]in Y||typeof Y.execScript=="undefined"||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||sa===void 0?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=sa;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
